# SSI V5 Laboratory Module - Coupon Laboratory
# ==============================================
#
# ETAP: 5.2.6.4 - Coupon Laboratory Foundation
# Data: 2026-08-04
#
# Odpowiedzialnosc:
# - Zarzadzanie eksperymentami kuponowymi
# - Tworzenie, porownywanie i ewaluacja kuponow
# - Zapis i odczyt historii eksperymentow
# - Integracja z PredictionTraceManager i StrategyMemory
#
# ZASADY:
# 1. TYLKO LABORATORIUM - nie wplywa na produkcje
# 2. Izolacja: eksperymenty sa niezalezne od systemu produkcyjnego
# 3. Historycznosc: wszystkie eksperymenty sa zapisywane
# 4. Reprodukowalnosc: ten sam input = ten sam output
# 5. NIE modyfikuje TrustManager, AgentRuntime, Pipeline, CollectiveManager
#
# Architektura:
# StrategyMemory -> StrategyLab -> PredictionTraceManager -> CouponLab -> Evaluation
#
# Generated by Mistral Vibe.
# Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import os
import json
import logging
from pathlib import Path
from typing import Dict, List, Any, Optional, Tuple
from datetime import datetime
from dataclasses import asdict
from threading import RLock
import copy

from .coupon_experiment import (
    CouponExperiment, 
    CouponEvaluation, 
    CouponResult,
    CouponStatus,
    CouponType
)

# Typy dla lepszego typowania
from SSI_V5.trace.prediction_trace import PredictionTraceRecord, PredictionTraceManager


class CouponLaboratory:
    """
    Laboratorium kuponowe - zarzadza eksperymentami kuponowymi.
    
    Odpowiedzialnosc:
    - Tworzenie eksperymentow kuponowych z PredictionTrace
    - Porownywanie wariantow kuponow
    - Ewaluacja jakości eksperymentow
    - Zapis i odczyt historii
    
    ZASADA: Izolowane srodowisko - nie wplywa na produkcje.
    """
    
    def __init__(self, storage_path: str = "data/coupon_experiments.json",
                 max_history: int = 1000):
        """
        Inicjalizacja laboratorium kuponowego.
        
        Args:
            storage_path: Sciezka do pliku przechowujacego historiê
            max_history: Maksymalna liczba eksperymentow w pamieci
        """
        self.storage_path = Path(storage_path)
        self.max_history = max_history
        self.experiments: Dict[str, CouponExperiment] = {}
        self._lock = RLock()
        self._history_loaded = False
        
        # Konfiguracja logowania
        self._setup_logging()
        
        # Zaladuj histogram (leniwie)
        self._ensure_storage_dir()
    
    def _setup_logging(self) -> None:
        """Konfiguracja logowania"""
        self.logger = logging.getLogger('CouponLaboratory')
        if not self.logger.handlers:
            handler = logging.StreamHandler()
            handler.setFormatter(logging.Formatter(
                '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
            ))
            self.logger.addHandler(handler)
            self.logger.setLevel(logging.INFO)
    
    def _ensure_storage_dir(self) -> None:
        """Zapewnia, ze katalog storage istnieje"""
        storage_dir = self.storage_path.parent
        if not storage_dir.exists():
            storage_dir.mkdir(parents=True, exist_ok=True)
            self.logger.info(f"Utworzono katalog storage: {storage_dir}")
    
    def _load_history(self) -> None:
        """Leniwe ladowanie historii z pliku"""
        if self._history_loaded:
            return
        
        if not self.storage_path.exists():
            self.logger.info("Plik historii nie istnieje, zaczynam z pustym stanem")
            self._history_loaded = True
            return
        
        try:
            with open(self.storage_path, 'r', encoding='utf-8') as f:
                data = json.load(f)
                for coupon_data in data.get('experiments', []):
                    try:
                        experiment = CouponExperiment.from_dict(coupon_data)
                        self.experiments[experiment.coupon_id] = experiment
                    except Exception as e:
                        self.logger.error(f"Blad ladowania eksperymentu: {e}")
            
            self.logger.info(f"Zaladowano {len(self.experiments)} eksperymentow z historii")
            self._history_loaded = True
            
        except Exception as e:
            self.logger.error(f"Blad ladowania historii: {e}")
            self._history_loaded = True
    
    def _save_history(self) -> None:
        """Zapis historii do pliku"""
        with self._lock:
            try:
                data = {
                    'experiments': [exp.to_dict() for exp in self.experiments.values()],
                    'last_updated': datetime.now().isoformat()
                }
                
                with open(self.storage_path, 'w', encoding='utf-8') as f:
                    json.dump(data, f, indent=2, default=str, ensure_ascii=False)
                
                self.logger.info(f"Zapisano {len(self.experiments)} eksperymentow do historii")
                
            except Exception as e:
                self.logger.error(f"Blad zapisu historii: {e}")
    
    def _generate_deterministic_coupon_id(
        self, 
        prediction_trace_ids: List[str],
        strategy_id: str,
        strategy_version: str,
        selection_rules: Dict[str, Any]
    ) -> str:
        """
        Generuje deterministyczne coupon_id.
        
        Args:
            prediction_trace_ids: Lista ID sladow predykcji
            strategy_id: ID strategii
            strategy_version: Wersja strategii
            selection_rules: Regu³y selekcji
            
        Returns:
            str: Deterministyczne coupon_id
        """
        import hashlib
        import json
        
        sorted_traces = sorted(prediction_trace_ids)
        rules_str = json.dumps(selection_rules, sort_keys=True, default=str)
        traces_str = ",".join(sorted_traces)
        
        combined = f"{strategy_id}:{strategy_version}:{traces_str}:{rules_str}"
        return f"coupon_{hashlib.sha256(combined.encode('utf-8')).hexdigest()[:12]}"
    
    # ===== METODY PUBLICZNE =====
    
    def create_experiment(
        self,
        prediction_trace_ids: List[str],
        strategy_id: str,
        strategy_version: str = "1.0.0",
        selection_rules: Optional[Dict[str, Any]] = None,
        strategy_experiment_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> CouponExperiment:
        """
        Tworzy nowy eksperyment kuponowy.
        
        Args:
            prediction_trace_ids: Lista ID sladow predykcji
            strategy_id: ID strategii
            strategy_version: Wersja strategii
            selection_rules: Regu³y selekcji predykcji
            strategy_experiment_id: ID powiazanego eksperymentu strategii
            metadata: Dodatkowe metadane
            
        Returns:
            CouponExperiment: Utworzony eksperyment
            
        Raises:
            ValueError: Jesli brak prediction_trace_ids
        """
        if not prediction_trace_ids:
            raise ValueError("prediction_trace_ids nie moze byc puste")
        
        if not strategy_id:
            raise ValueError("strategy_id nie moze byc puste")
        
        # Ustaw domyslne selection_rules
        if selection_rules is None:
            selection_rules = {
                'min_confidence': 0.0,
                'max_odds': float('inf'),
                'max_predictions': 10
            }
        
        # Generuj deterministyczne coupon_id
        coupon_id = self._generate_deterministic_coupon_id(
            prediction_trace_ids, 
            strategy_id, 
            strategy_version, 
            selection_rules
        )
        
        # Sprawdz, czy eksperyment juz istnieje (reprodukowalnosc)
        if coupon_id in self.experiments:
            self.logger.info(f"Eksperyment {coupon_id} juz istnieje - zwracam istniejacy")
            return self.experiments[coupon_id]
        
        # Utworz nowy eksperyment
        experiment = CouponExperiment(
            coupon_id=coupon_id,
            strategy_id=strategy_id,
            strategy_version=strategy_version,
            prediction_trace_ids=list(prediction_trace_ids),
            selection_rules=copy.deepcopy(selection_rules) if selection_rules else {},
            strategy_experiment_id=strategy_experiment_id,
            status=CouponStatus.CREATED,
            metadata=copy.deepcopy(metadata) if metadata else {}
        )
        
        # Zapisz w pamieci
        with self._lock:
            self.experiments[coupon_id] = experiment
            # Usun najstarsze, jesli przekroczono limit
            if len(self.experiments) > self.max_history:
                self._trim_history()
        
        self.logger.info(f"Utworzono eksperyment kuponowy: {coupon_id} "
                        f"(strategy: {strategy_id}, traces: {len(prediction_trace_ids)})")
        
        return experiment
    
    def create_experiment_from_prediction_traces(
        self,
        prediction_traces: List[PredictionTraceRecord],
        strategy_id: str,
        strategy_version: str = "1.0.0",
        selection_rules: Optional[Dict[str, Any]] = None,
        strategy_experiment_id: Optional[str] = None,
        metadata: Optional[Dict[str, Any]] = None
    ) -> CouponExperiment:
        """
        Tworzy eksperyment kuponowy bezposrednio z obiekty PredictionTraceRecord.
        
        Args:
            prediction_traces: Lista obiekty PredictionTraceRecord
            strategy_id: ID strategii
            strategy_version: Wersja strategii
            selection_rules: Regu³y selekcji
            strategy_experiment_id: ID powiazanego eksperymentu strategii
            metadata: Dodatkowe metadane
            
        Returns:
            CouponExperiment: Utworzony eksperyment
        """
        prediction_trace_ids = [trace.trace_id for trace in prediction_traces]
        
        # Wyciuagnij dodatkowe informacje z predykcji
        if selection_rules is None:
            selection_rules = {}
        
        # Dodaj informacje o pewnosci i kursach do selection_rules
        if prediction_traces:
            confidences = [trace.prediction.confidence for trace in prediction_traces]
            selection_rules['actual_min_confidence'] = min(confidences) if confidences else 0.0
            selection_rules['actual_max_confidence'] = max(confidences) if confidences else 0.0
            selection_rules['actual_avg_confidence'] = sum(confidences) / len(confidences) if confidences else 0.0
        
        return self.create_experiment(
            prediction_trace_ids=prediction_trace_ids,
            strategy_id=strategy_id,
            strategy_version=strategy_version,
            selection_rules=selection_rules,
            strategy_experiment_id=strategy_experiment_id,
            metadata=metadata
        )
    
    def link_prediction_trace(
        self,
        coupon_id: str,
        trace_id: str
    ) -> bool:
        """
        Powiazuje dodatkowy PredictionTrace z eksperymentem kuponowym.
        
        Args:
            coupon_id: ID kuponu
            trace_id: ID sladu predykcji
            
        Returns:
            bool: True jesli powiazanie sie powiodlo
        """
        with self._lock:
            if coupon_id not in self.experiments:
                self.logger.warning(f"Eksperyment {coupon_id} nie istnieje")
                return False
            
            experiment = self.experiments[coupon_id]
            
            if trace_id in experiment.prediction_trace_ids:
                self.logger.info(f"Trace {trace_id} juz jest powiazany z {coupon_id}")
                return True
            
            # Studie - recalculujemy coupon_id, jesli to konieczne
            # Dla reprodukowalnosci nie zmieniamy istnieacego coupon_id
            experiment.prediction_trace_ids.append(trace_id)
            experiment.status = CouponStatus.LOADED
            
            self.logger.info(f"Powiazano trace {trace_id} z eksperymentem {coupon_id}")
            return True
    
    def evaluate_experiment(
        self,
        coupon_id: str,
        prediction_manager: Optional[PredictionTraceManager] = None
    ) -> Optional[CouponEvaluation]:
        """
        Oblicza metryki ewaluacji dla eksperymentu kuponowego.
        
        Args:
            coupon_id: ID eksperymentu kuponowego
            prediction_manager: Opcjonalny PredictionTraceManager do pobrania detali
            
        Returns:
            CouponEvaluation: Metryki ewaluacji lub None jesli blad
        """
        with self._lock:
            if coupon_id not in self.experiments:
                self.logger.error(f"Eksperyment {coupon_id} nie istnieje")
                return None
            
            experiment = self.experiments[coupon_id]
            
            if not experiment.prediction_trace_ids:
                self.logger.warning(f"Eksperyment {coupon_id} nie ma powiazanych predykcji")
                return None
            
            # Inicjalizuj metryki
            evaluation = CouponEvaluation()
            evaluation.total_predictions = len(experiment.prediction_trace_ids)
            
            # Jesli mamy PredictionTraceManager, pobierz dodatkowe informacje
            if prediction_manager:
                confidences = []
                expected_values = []
                odds_list = []
                
                for trace_id in experiment.prediction_trace_ids:
                    trace = prediction_manager.get_trace(trace_id)
                    if trace:
                        confidences.append(trace.prediction.confidence)
                        # Wyciuagnij expected_value z metadanych lub oblicz
                        ev = trace.evaluation_metrics.get('expected_value', trace.prediction.confidence)
                        expected_values.append(ev)
                        # Kursy z metadanych
                        if 'odds' in trace.metadata:
                            odds_list.append(float(trace.metadata['odds']))
                
                if confidences:
                    evaluation.confidence_aggregate = sum(confidences) / len(confidences)
                
                if expected_values:
                    evaluation.expected_value = sum(expected_values) / len(expected_values)
                
                if odds_list:
                    evaluation.risk_score = max(odds_list)
            else:
                #domyslne wartosci
                evaluation.confidence_aggregate = experiment.confidence_score
                evaluation.expected_value = experiment.expected_value
                evaluation.risk_score = experiment.risk_profile.get('max_odds', 0.0)
            
            # Ustaw domyslne wartosci
            evaluation.accuracy = 0.0  # Brakuje danych do obliczenia
            evaluation.roi = 0.0  # Brakuje danych do obliczenia
            evaluation.sharpe_ratio = 0.0
            evaluation.volatility = 0.0
            
            # Zapisz ewaluacje w eksperymencie
            experiment.evaluation = evaluation
            experiment.status = CouponStatus.EVALUATED
            
            self.experiments[coupon_id] = experiment
            
            self.logger.info(f"Ewaluacja eksperymentu {coupon_id}: "
                           f"confidence={evaluation.confidence_aggregate:.3f}, "
                           f"expected_value={evaluation.expected_value:.3f}, "
                           f"risk_score={evaluation.risk_score:.3f}")
            
            return evaluation
    
    def compare_experiments(
        self,
        coupon_ids: List[str],
        metric: str = "expected_value",
        ascending: bool = False
    ) -> List[CouponExperiment]:
        """
        Porownuje wiele eksperymentow kuponowych według metryki.
        
        Args:
            coupon_ids: Lista ID eksperymentow do porownania
            metric: Metryka do porownania (expected_value, confidence_score, risk_score, etc.)
            ascending: Czy sortowac rosnaco (domyslnie False = malejaco)
            
        Returns:
            List[CouponExperiment]: Posortowana lista eksperymentow
        """
        with self._lock:
            valid_experiments = []
            
            for coupon_id in coupon_ids:
                if coupon_id in self.experiments:
                    valid_experiments.append(self.experiments[coupon_id])
                else:
                    self.logger.warning(f"Eksperyment {coupon_id} nie istnieje - pomijam")
            
            if not valid_experiments:
                return []
            
            # Pobierz wartosc metryki dla kazdego eksperymentu
            def get_metric_value(exp: CouponExperiment) -> float:
                if metric == "expected_value":
                    return exp.expected_value
                elif metric == "confidence_score":
                    return exp.confidence_score
                elif metric == "risk_score":
                    return exp.risk_profile.get('risk_score', 0.0)
                elif metric == "accuracy" and exp.evaluation:
                    return exp.evaluation.accuracy
                elif metric == "roi" and exp.evaluation:
                    return exp.evaluation.roi
                elif metric == "created_time":
                    return exp.created_time.timestamp() if exp.created_time else 0.0
                else:
                    # Spróbuj pobrac z evaluation
                    if exp.evaluation and hasattr(exp.evaluation, metric):
                        return getattr(exp.evaluation, metric, 0.0)
                    return 0.0
            
            # Sortuj po metryce
            sorted_experiments = sorted(
                valid_experiments,
                key=get_metric_value,
                reverse=not ascending
            )
            
            self.logger.info(f"Porownano {len(valid_experiments)} eksperymentow po metryce '{metric}'")
            return sorted_experiments
    
    def save_experiment(self, experiment: CouponExperiment) -> bool:
        """
        Zapisuje pojedynczy eksperyment do pamieci i na dysk.
        
        Args:
            experiment: Eksperyment do zapisu
            
        Returns:
            bool: True jesli zapis sie powiodl
        """
        with self._lock:
            self.experiments[experiment.coupon_id] = experiment
            
            # Zapis do pliku
            try:
                self._save_history()
                self.logger.info(f"Zapisano eksperyment {experiment.coupon_id}")
                return True
            except Exception as e:
                self.logger.error(f"Blad zapisu eksperymentu {experiment.coupon_id}: {e}")
                return False
    
    def load_experiment(self, coupon_id: str) -> Optional[CouponExperiment]:
        """
        Laduje eksperyment po ID.
        
        Args:
            coupon_id: ID eksperymentu
            
        Returns:
            CouponExperiment: Zaladowany eksperyment lub None
        """
        # Leniwe ladowanie historii
        self._load_history()
        
        with self._lock:
            if coupon_id in self.experiments:
                return copy.deepcopy(self.experiments[coupon_id])
            
            self.logger.warning(f"Eksperyment {coupon_id} nie znaleziony")
            return None
    
    def get_history(
        self,
        strategy_id: Optional[str] = None,
        limit: int = 100,
        status_filter: Optional[CouponStatus] = None
    ) -> List[CouponExperiment]:
        """
        Zwraca historiê eksperymentow kuponowych.
        
        Args:
            strategy_id: Opcjonalny filtr po ID strategii
            limit: Maksymalna liczba wynikow
            status_filter: Opcjonalny filtr po statusie
            
        Returns:
            List[CouponExperiment]: Lista eksperymentow
        """
        # Leniwe ladowanie historii
        self._load_history()
        
        with self._lock:
            experiments = list(self.experiments.values())
            
            # Filtry
            if strategy_id:
                experiments = [exp for exp in experiments if exp.strategy_id == strategy_id]
            
            if status_filter:
                experiments = [exp for exp in experiments if exp.status == status_filter]
            
            # Sortuj po czasie (od najnowszego)
            experiments = sorted(
                experiments,
                key=lambda exp: exp.created_time.timestamp() if exp.created_time else 0,
                reverse=True
            )
            
            # Limit
            return experiments[:limit]
    
    def get_experiments_by_strategy(
        self,
        strategy_id: str,
        strategy_version: Optional[str] = None
    ) -> List[CouponExperiment]:
        """
        Zwraca eksperymenty dla danej strategii.
        
        Args:
            strategy_id: ID strategii
            strategy_version: Opcjonalna wersja strategii
            
        Returns:
            List[CouponExperiment]: Lista eksperymentow
        """
        with self._lock:
            experiments = []
            for exp in self.experiments.values():
                if exp.strategy_id == strategy_id:
                    if strategy_version is None or exp.strategy_version == strategy_version:
                        experiments.append(exp)
            
            return sorted(
                experiments,
                key=lambda exp: exp.created_time.timestamp() if exp.created_time else 0,
                reverse=True
            )
    
    def update_experiment_result(
        self,
        coupon_id: str,
        succeeded: bool,
        payout: Optional[float] = None,
        actual_value: float = 0.0,
        outcome: str = "win"
    ) -> bool:
        """
        Aktualizuje wynik eksperymentu kuponowego.
        
        Args:
            coupon_id: ID eksperymentu
            succeeded: Czy kupon sie powiodl
            payout: Wyplata (symulowana)
            actual_value: Rzeczywista wartosc
            outcome: Wynik (win/lose/void)
            
        Returns:
            bool: True jesli aktualizacja sie powiodla
        """
        with self._lock:
            if coupon_id not in self.experiments:
                self.logger.error(f"Eksperyment {coupon_id} nie istnieje")
                return False
            
            experiment = self.experiments[coupon_id]
            
            experiment.result = CouponResult(
                succeeded=succeeded,
                payout=payout,
                actual_value=actual_value,
                outcome=outcome,
                settled_time=datetime.now()
            )
            
            experiment.status = CouponStatus.COMPLETED
            self.experiments[coupon_id] = experiment
            
            self.logger.info(f"Zaktualizowano wynik eksperymentu {coupon_id}: "
                           f"succeeded={succeeded}, payout={payout}, outcome={outcome}")
            
            # Zapis do historii
            try:
                self._save_history()
            except Exception as e:
                self.logger.error(f"Blad zapisu po aktualizacji wyniku: {e}")
            
            return True
    
    def _trim_history(self) -> None:
        """Przycina hiostorie, jesli przekroczono limit"""
        with self._lock:
            if len(self.experiments) <= self.max_history:
                return
            
            # Sortuj po czasie i usun najstarsze
            sorted_experiments = sorted(
                self.experiments.items(),
                key=lambda x: x[1].created_time.timestamp() if x[1].created_time else 0
            )
            
            # Usun 20% najstarszych
            to_remove = max(1, len(sorted_experiments) // 5)
            for i in range(to_remove):
                old_coupon_id = sorted_experiments[i][0]
                del self.experiments[old_coupon_id]
                self.logger.info(f"Usunieto stary eksperyment: {old_coupon_id}")
    
    def get_statistics(self) -> Dict[str, Any]:
        """
        Zwraca statystyki laboratorium.
        
        Returns:
            Dict[str, Any]: Statystyki
        """
        with self._lock:
            total = len(self.experiments)
            
            status_counts = {status.value: 0 for status in CouponStatus}
            strategy_counts = {}
            
            for exp in self.experiments.values():
                status_counts[exp.status.value] += 1
                
                strategy_key = f"{exp.strategy_id}@{exp.strategy_version}"
                strategy_counts[strategy_key] = strategy_counts.get(strategy_key, 0) + 1
            
            return {
                'total_experiments': total,
                'status_distribution': status_counts,
                'strategy_distribution': strategy_counts,
                'max_history': self.max_history
            }
    
    def clear_history(self) -> None:
        """Czysci historiê eksperymentow"""
        with self._lock:
            self.experiments.clear()
            try:
                if self.storage_path.exists():
                    self.storage_path.unlink()
                self.logger.info("Wyczyszczono historiê eksperymentow")
            except Exception as e:
                self.logger.error(f"Blad czyszczenia historii: {e}")
    
    def deactivate_experiment(self, coupon_id: str) -> bool:
        """
        Dezaktywuje eksperyment (archiwizuje).
        
        Args:
            coupon_id: ID eksperymentu
            
        Returns:
            bool: True jesli dezaktywacja sie powiodla
        """
        with self._lock:
            if coupon_id not in self.experiments:
                return False
            
            experiment = self.experiments[coupon_id]
            experiment.status = CouponStatus.ARCHIVED
            self.experiments[coupon_id] = experiment
            
            self.logger.info(f"Zarchiwizowano eksperyment: {coupon_id}")
            return True
