"""
SSI V5 Market Aggregator Module
=================================

ETAP: 5.2.6.5 - OddsAggregator and MarketTrendsAnalyzer

Moduł agregacji i analizy trendów rynkowych.

Odowiedzialność:
- Agregacja kursów z wielu źródeł (OddsAggregator)
- Analiza trendów i generowanie sygnałów (MarketTrendsAnalyzer)
- Wykrywanie okazji value betting i arbitrażowych
- Predykcja ruchu kursów

Zasady:
1. NIE MODYFIKUJE istniejących modułów
2. V TYLKO OBSERWACJA i ANALIZA
3. Współpracuje z existing market/ i laboratory/

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

from .odds_aggregator import (
    # Enums
    OddsSource,
    OddsType,
    MarketType,
    AggregationMethod,
    
    # Data Models
    RawOddsData,
    AggregatedOdds,
    OddsMovement,
    
    # Main Class
    OddsAggregator
)

from .market_trends_analyzer import (
    # Enums
    TrendType,
    MarketCondition,
    SignalType,
    TimeFrame,
    TREND_THRESHOLDS,
    
    # Data Models
    TrendData,
    MarketTrendAnalysis,
    MarketSignal,
    
    # Main Class
    MarketTrendsAnalyzer
)

__version__ = "1.0.0"
__etap__ = "5.2.6.5"
__name__ = "SSI_V5_MARKET_AGGREGATOR"

__all__ = [
    # OddsAggregator exports
    'OddsSource',
    'OddsType', 
    'MarketType',
    'AggregationMethod',
    'RawOddsData',
    'AggregatedOdds',
    'OddsMovement',
    'OddsAggregator',
    
    # MarketTrendsAnalyzer exports
    'TrendType',
    'MarketCondition',
    'SignalType',
    'TimeFrame',
    'TREND_THRESHOLDS',
    'TrendData',
    'MarketTrendAnalysis',
    'MarketSignal',
    'MarketTrendsAnalyzer',
    
    # Metadata
    '__version__',
    '__etap__',
    '__name__'
]

# Inicjalizacja - rejestracja modułu
print(f"[AGGREGATOR] Moduł {__name__} v{__version__} (ETAP {__etap__}) załadowany")
