"""
SSI V5 Market Intelligence - Market Trends Analyzer
====================================================

ETAP: 5.2.6.5 - MarketTrendsAnalyzer Implementation

Odpowiedzialność:
- Analiza trendów rynkowych i kursowych
- Wykrywanie wzorców i anomalii
- Predykcja kierunku ruchu kursów
- Integracja z OddsAggregator

Zasady:
1. NIE MODYFIKUJE istniejących modułów (market, laboratory, trace)
2. TYLKO ANALIZA - nie podejmuje decyzji
3. Dostarcza wiedzę analityczną dla kolejnych warstw
4. Współpracuje z OddsAggregator

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

import json
import os
from datetime import datetime, timedelta
from typing import Dict, List, Optional, Tuple, Any, Callable
from dataclasses import dataclass, field
from enum import Enum
from threading import RLock
from collections import defaultdict
import statistics
import numpy as np
from sklearn.linear_model import LinearRegression
from sklearn.preprocessing import PolynomialFeatures


# ============================================================================
# ENUMS AND CONSTANTS
# ============================================================================

class TrendType(Enum):
    """Typy trendów"""
    STRONG_UP = "strong_up"        # Silny wzrost
    MODERATE_UP = "moderate_up"    # Umiarkowany wzrost
    WEAK_UP = "weak_up"           # Słaby wzrost
    STABLE = "stable"             # Stabilny
    WEAK_DOWN = "weak_down"       # Słaby spadek
    MODERATE_DOWN = "moderate_down"  # Umiarkowany spadek
    STRONG_DOWN = "strong_down"   # Silny spadek
    VOLATILE = "volatile"         # Zmienny
    OSCILLATING = "oscillating"   # Oscylujący


class MarketCondition(Enum):
    """Warunki rynkowe"""
    NORMAL = "normal"
    BULLISH = "bullish"           # Kursy rosną (wzrost popularności)
    BEARISH = "bearish"          # Kursy spadają (spadek popularności)
    SHARP_MOVEMENT = "sharp_movement"  # Gwałtowne ruchy
    STABLE = "stable"            # Stabilny
    UNCERTAIN = "uncertain"      # Niepewny


class SignalType(Enum):
    """Typy sygnałów"""
    BUY = "buy"                  # Sygnał zakupu (value)
    SELL = "sell"                # Sygnał sprzedaży (overpriced)
    HOLD = "hold"                # Trzymaj
    CAUTION = "caution"          # Uwaga (wysoka zmienność)
    STRONG_BUY = "strong_buy"   # Silny sygnał zakupu
    STRONG_SELL = "strong_sell" # Silny sygnał sprzedaży


class TimeFrame(Enum):
    """Ramki czasowe"""
    SHORT_TERM = "15min"         # 15 minut
    MEDIUM_TERM = "1h"          # 1 godzina
    LONG_TERM = "24h"           # 24 godziny
    CUSTOM = "custom"           # Niestandardowy


# Progi dla klasyfikacji trendów
TREND_THRESHOLDS = {
    'strong': 0.3,      # 30% zmiana
    'moderate': 0.15,   # 15% zmiana
    'weak': 0.05,       # 5% zmiana
    'volatile': 0.2     # 20% odchylenie standardowe
}


# ============================================================================
# DATA MODELS
# ============================================================================

@dataclass
class TrendData:
    """Dane trendowe dla pojedynczego outcome"""
    match_id: str
    market_type: str
    outcome: str
    
    # Historia kursów
    timestamps: List[datetime] = field(default_factory=list)
    odds_values: List[float] = field(default_factory=list)
    
    # Analiza trendowa
    current_odds: float = 0.0
    trend_type: TrendType = TrendType.STABLE
    trend_strength: float = 0.0  # 0-1
    slope: float = 0.0          # Nachylenie regresji
    r_squared: float = 0.0     # Współczynnik determinacji
    
    # Statystyki
    mean: float = 0.0
    std_dev: float = 0.0
    min_odds: float = float('inf')
    max_odds: float = 0.0
    
    # Predykcja
    predicted_next: float = 0.0
    prediction_confidence: float = 0.0
    
    # Sygnały
    signals: List[Dict[str, Any]] = field(default_factory=list)
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'match_id': self.match_id,
            'market_type': self.market_type,
            'outcome': self.outcome,
            'current_odds': self.current_odds,
            'trend_type': self.trend_type.value,
            'trend_strength': self.trend_strength,
            'slope': self.slope,
            'r_squared': self.r_squared,
            'mean': self.mean,
            'std_dev': self.std_dev,
            'min_odds': self.min_odds,
            'max_odds': self.max_odds,
            'predicted_next': self.predicted_next,
            'prediction_confidence': self.prediction_confidence,
            'signal_count': len(self.signals),
            'signals': self.signals,
            'history': [
                {'timestamp': t.isoformat(), 'odds': o}
                for t, o in zip(self.timestamps, self.odds_values)
            ]
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'TrendData':
        trend = cls(
            match_id=data.get('match_id', ''),
            market_type=data.get('market_type', ''),
            outcome=data.get('outcome', ''),
            current_odds=data.get('current_odds', 0.0),
            trend_type=TrendType(data.get('trend_type', 'stable')),
            trend_strength=data.get('trend_strength', 0.0),
            slope=data.get('slope', 0.0),
            r_squared=data.get('r_squared', 0.0),
            mean=data.get('mean', 0.0),
            std_dev=data.get('std_dev', 0.0),
            min_odds=data.get('min_odds', float('inf')),
            max_odds=data.get('max_odds', 0.0),
            predicted_next=data.get('predicted_next', 0.0),
            prediction_confidence=data.get('prediction_confidence', 0.0),
            signals=data.get('signals', [])
        )
        
        # Load history
        for item in data.get('history', []):
            trend.timestamps.append(datetime.fromisoformat(item['timestamp']))
            trend.odds_values.append(item['odds'])
        
        return trend


@dataclass
class MarketTrendAnalysis:
    """Kompleksowa analiza trendów rynkowych"""
    match_id: str
    market_type: str
    
    # Ogólne statystyki
    overall_trend: TrendType = TrendType.STABLE
    market_condition: MarketCondition = MarketCondition.NORMAL
    
    # Per-outcome trends
    outcome_trends: Dict[str, TrendData] = field(default_factory=dict)
    
    # Korelacje między outcome'ami
    correlations: Dict[str, Dict[str, float]] = field(default_factory=dict)
    
    # Sygnały
    signals: List[Dict[str, Any]] = field(default_factory=list)
    
    # Rekomendacje
    recommendations: List[Dict[str, Any]] = field(default_factory=list)
    
    # Metadane
    timestamp: datetime = field(default_factory=datetime.now)
    analysis_duration: float = 0.0  # Czas analizy w sekundach
    data_points: int = 0
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'match_id': self.match_id,
            'market_type': self.market_type,
            'overall_trend': self.overall_trend.value,
            'market_condition': self.market_condition.value,
            'outcome_trends': {k: v.to_dict() for k, v in self.outcome_trends.items()},
            'correlations': {
                k: {kk: round(vv, 4) for kk, vv in v.items()}
                for k, v in self.correlations.items()
            },
            'signals': self.signals,
            'recommendations': self.recommendations,
            'timestamp': self.timestamp.isoformat(),
            'analysis_duration': self.analysis_duration,
            'data_points': self.data_points
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'MarketTrendAnalysis':
        analysis = cls(
            match_id=data.get('match_id', ''),
            market_type=data.get('market_type', ''),
            overall_trend=TrendType(data.get('overall_trend', 'stable')),
            market_condition=MarketCondition(data.get('market_condition', 'normal')),
            signals=data.get('signals', []),
            recommendations=data.get('recommendations', []),
            timestamp=datetime.fromisoformat(data.get('timestamp', datetime.now().isoformat())),
            analysis_duration=data.get('analysis_duration', 0.0),
            data_points=data.get('data_points', 0)
        )
        
        for outcome, trend_data in data.get('outcome_trends', {}).items():
            analysis.outcome_trends[outcome] = TrendData.from_dict(trend_data)
        
        for outcome, corr_dict in data.get('correlations', {}).items():
            analysis.correlations[outcome] = corr_dict
        
        return analysis


@dataclass
class MarketSignal:
    """Sygnał rynkowy"""
    signal_type: SignalType
    strength: float  # 0-1
    confidence: float  # 0-1
    
    source_outcome: str
    target_outcome: Optional[str] = None
    
    # Kontekst
    current_odds: float = 0.0
    expected_odds: float = 0.0
    fair_odds: float = 0.0
    
    # Metryki
    expected_value: float = 0.0
    probability: float = 0.0
    risk_level: str = "medium"
    
    # Timing
    timestamp: datetime = field(default_factory=datetime.now)
    urgency: str = "medium"  # high, medium, low
    
    # Opis
    description: str = ""
    reasoning: str = ""
    
    def to_dict(self) -> Dict[str, Any]:
        return {
            'signal_type': self.signal_type.value,
            'strength': self.strength,
            'confidence': self.confidence,
            'source_outcome': self.source_outcome,
            'target_outcome': self.target_outcome,
            'current_odds': self.current_odds,
            'expected_odds': self.expected_odds,
            'fair_odds': self.fair_odds,
            'expected_value': self.expected_value,
            'probability': self.probability,
            'risk_level': self.risk_level,
            'timestamp': self.timestamp.isoformat(),
            'urgency': self.urgency,
            'description': self.description,
            'reasoning': self.reasoning
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'MarketSignal':
        return cls(
            signal_type=SignalType(data.get('signal_type', 'hold')),
            strength=data.get('strength', 0.0),
            confidence=data.get('confidence', 0.0),
            source_outcome=data.get('source_outcome', ''),
            target_outcome=data.get('target_outcome'),
            current_odds=data.get('current_odds', 0.0),
            expected_odds=data.get('expected_odds', 0.0),
            fair_odds=data.get('fair_odds', 0.0),
            expected_value=data.get('expected_value', 0.0),
            probability=data.get('probability', 0.0),
            risk_level=data.get('risk_level', 'medium'),
            timestamp=datetime.fromisoformat(data.get('timestamp', datetime.now().isoformat())),
            urgency=data.get('urgency', 'medium'),
            description=data.get('description', ''),
            reasoning=data.get('reasoning', '')
        )


# ============================================================================
# MARKET TRENDS ANALYZER MAIN CLASS
# ============================================================================

class MarketTrendsAnalyzer:
    """
    Główna klasa do analizy trendów rynkowych i kursowych.
    
    Funkcjonalności:
    - Analiza trendów historycznych
    - Predykcja kierunku ruchu kursów
    - Wykrywanie sygnałówValue betting
    - Wykrywanie anomalii i szans arbitrażowych
    - Integracja z OddsAggregator
    """
    
    def __init__(
        self,
        odds_aggregator: 'OddsAggregator' = None,
        data_dir: str = None,
        max_history: int = 1000,
        min_data_points: int = 5
    ):
        """
        Inicjalizacja MarketTrendsAnalyzer.
        
        Args:
            odds_aggregator: Powiązany OddsAggregator
            data_dir: Katalog do zapisywania danych
            max_history: Maksymalna historia trendów
            min_data_points: Minimalna liczba punktów do analizy
        """
        self.odds_aggregator = odds_aggregator
        self.min_data_points = min_data_points
        
        if data_dir is None:
            from ..config.path_config import PathConfig
            data_dir = PathConfig.MARKET_DATA_DIR
        
        self.data_dir = os.path.join(data_dir, "trends")
        self.max_history = max_history
        
        # Cache
        self._trend_cache: Dict[str, TrendData] = {}
        self._analysis_cache: Dict[str, MarketTrendAnalysis] = {}
        self._signal_cache: Dict[str, MarketSignal] = {}
        
        # Historia
        self._trend_history: List[TrendData] = []
        self._analysis_history: List[MarketTrendAnalysis] = []
        
        # Lock dla bezpieczeństwa wątkowego
        self._lock = RLock()
        
        # Statystyki
        self.stats = {
            'total_analyses': 0,
            'total_signals': 0,
            'total_recommendations': 0
        }
        
        # Tworzymy katalog danych
        os.makedirs(self.data_dir, exist_ok=True)
        
        # Wczytanie danych z dysku
        self._load_from_disk()
    
    # ========================================================================
    # CORE ANALYSIS FUNCTIONS
    # ========================================================================
    
    def analyze_trends(
        self,
        match_id: str,
        market_type: str = "match_result",
        timeframe: TimeFrame = TimeFrame.MEDIUM_TERM
    ) -> MarketTrendAnalysis:
        """
        Wykonająckompleksową analizę trendów.
        
        Args:
            match_id: ID meczu
            market_type: Typ rynku
            timeframe: Rama czasowa analizy
            
        Returns:
            Obiekt MarketTrendAnalysis
        """
        import time
        start_time = time.time()
        
        with self._lock:
            # 1. Pobierz historię kursów z OddsAggregator
            if self.odds_aggregator:
                movement_data = self.odds_aggregator.get_odds_movement(
                    match_id, 
                    self._convert_market_type(market_type)
                )
            else:
                raise ValueError("OddsAggregator not configured")
            
            if not movement_data:
                raise ValueError(f"No movement data found for {match_id}")
            
            # 2. Utwórz i przeanalizuj trendy per-outcome
            outcome_trends = {}
            all_timestamps = set()
            
            for outcome, movement in movement_data.items():
                trend_data = self._create_trend_data(
                    match_id, 
                    market_type, 
                    outcome, 
                    movement
                )
                
                if len(trend_data.odds_values) >= self.min_data_points:
                    self._analyze_trend(trend_data)
                    outcome_trends[outcome] = trend_data
                    all_timestamps.update(trend_data.timestamps)
            
            if not outcome_trends:
                raise ValueError(f"Insufficient data points for analysis (need >= {self.min_data_points})")
            
            # 3. Oblicz korelacje między outcome'ami
            correlations = self._calculate_correlations(outcome_trends)
            
            # 4. Oblicz ogólne statystyki rynku
            overall_trend, market_condition = self._determine_overall_trend(outcome_trends)
            
            # 5. Wygeneruj sygnały
            signals = self._generate_signals(outcome_trends, correlations)
            
            # 6. Wygeneruj rekomendacje
            recommendations = self._generate_recommendations(
                outcome_trends, correlations, signals
            )
            
            # 7. Utwórz analizę
            analysis = MarketTrendAnalysis(
                match_id=match_id,
                market_type=market_type,
                overall_trend=overall_trend,
                market_condition=market_condition,
                outcome_trends=outcome_trends,
                correlations=correlations,
                signals=signals,
                recommendations=recommendations,
                analysis_duration=time.time() - start_time,
                data_points=len(all_timestamps)
            )
            
            # 8. Zapisz w cache i historii
            cache_key = f"{match_id}_{market_type}_{timeframe.value}"
            self._analysis_cache[cache_key] = analysis
            self._analysis_history.append(analysis)
            
            # 9. Ograniczenie historii
            if len(self._analysis_history) > self.max_history:
                self._analysis_history = self._analysis_history[-self.max_history:]
            
            self.stats['total_analyses'] += 1
            self.stats['total_signals'] += len(signals)
            self.stats['total_recommendations'] += len(recommendations)
            
            return analysis
    
    def _create_trend_data(
        self,
        match_id: str,
        market_type: str,
        outcome: str,
        movement: 'OddsMovement'
    ) -> TrendData:
        """Tworzy TrendData z OddsMovement"""
        trend = TrendData(
            match_id=match_id,
            market_type=market_type,
            outcome=outcome,
            timestamps=movement.timestamp_history[:],
            odds_values=movement.odds_history[:],
            current_odds=movement.current_odds
        )
        
        # Oblicz statystyki
        if trend.odds_values:
            trend.mean = float(statistics.mean(trend.odds_values))
            trend.min_odds = min(trend.odds_values)
            trend.max_odds = max(trend.odds_values)
            
            if len(trend.odds_values) >= 2:
                trend.std_dev = float(statistics.stdev(trend.odds_values))
            else:
                trend.std_dev = 0.0
        
        return trend
    
    def _analyze_trend(self, trend: TrendData) -> None:
        """Analizuje pojedynczy trend"""
        if len(trend.odds_values) < 2:
            trend.trend_type = TrendType.STABLE
            trend.trend_strength = 0.0
            return
        
        # 1. Oblicz resume regresji liniowej
        X = np.array([i for i in range(len(trend.odds_values))]).reshape(-1, 1)
        y = np.array(trend.odds_values)
        
        try:
            model = LinearRegression(fit_intercept=True)
            model.fit(X, y)
            trend.slope = model.coef_[0]
            trend.r_squared = model.score(X, y)
        except:
            trend.slope = 0.0
            trend.r_squared = 0.0
        
        # 2. Predykcja następnej wartości
        if trend.slope != 0:
            next_x = len(trend.odds_values)
            trend.predicted_next = float(model.predict([[next_x]])[0])
        else:
            trend.predicted_next = trend.current_odds
        
        # 3. Predykcja confidence
        if trend.r_squared > 0.7:
            trend.prediction_confidence = min(1.0, trend.r_squared)
        elif trend.r_squared > 0.3:
            trend.prediction_confidence = 0.5 + (trend.r_squared * 0.5)
        else:
            trend.prediction_confidence = trend.r_squared
        
        # 4. Określ typ trendu
        percent_change = abs(trend.slope / trend.mean) * 100 if trend.mean > 0 else 0
        
        if trend.slope > TREND_THRESHOLDS['strong']:
            trend.trend_type = TrendType.STRONG_UP
            trend.trend_strength = min(1.0, percent_change / 30)
        elif trend.slope > TREND_THRESHOLDS['moderate']:
            trend.trend_type = TrendType.MODERATE_UP
            trend.trend_strength = min(1.0, percent_change / 15)
        elif trend.slope > TREND_THRESHOLDS['weak']:
            trend.trend_type = TrendType.WEAK_UP
            trend.trend_strength = min(1.0, percent_change / 5)
        elif trend.slope < -TREND_THRESHOLDS['strong']:
            trend.trend_type = TrendType.STRONG_DOWN
            trend.trend_strength = min(1.0, abs(percent_change) / 30)
        elif trend.slope < -TREND_THRESHOLDS['moderate']:
            trend.trend_type = TrendType.MODERATE_DOWN
            trend.trend_strength = min(1.0, abs(percent_change) / 15)
        elif trend.slope < -TREND_THRESHOLDS['weak']:
            trend.trend_type = TrendType.WEAK_DOWN
            trend.trend_strength = min(1.0, abs(percent_change) / 5)
        else:
            # Sprawdź zmienność
            if trend.std_dev > TREND_THRESHOLDS['volatile']:
                trend.trend_type = TrendType.VOLATILE
                trend.trend_strength = min(1.0, trend.std_dev / 2.0)
            elif trend.std_dev > TREND_THRESHOLDS['volatile'] / 2:
                trend.trend_type = TrendType.OSCILLATING
                trend.trend_strength = min(1.0, trend.std_dev)
            else:
                trend.trend_type = TrendType.STABLE
                trend.trend_strength = 0.0
    
    def _calculate_correlations(
        self, 
        outcome_trends: Dict[str, TrendData]
    ) -> Dict[str, Dict[str, float]]:
        """Oblicza korelacje między outcome'ami"""
        correlations = {}
        outcomes = list(outcome_trends.keys())
        
        for i, outcome1 in enumerate(outcomes):
            correlations[outcome1] = {}
            for outcome2 in outcomes[i+1:]:
                try:
                    values1 = outcome_trends[outcome1].odds_values
                    values2 = outcome_trends[outcome2].odds_values
                    
                    # Dopasuj długości
                    min_len = min(len(values1), len(values2))
                    if min_len >= 3:
                        vec1 = values1[-min_len:]
                        vec2 = values2[-min_len:]
                        corr = float(np.corrcoef(vec1, vec2)[0, 1])
                    else:
                        corr = 0.0
                    
                    correlations[outcome1][outcome2] = corr
                    correlations[outcome2][outcome1] = corr
                except:
                    correlations[outcome1][outcome2] = 0.0
                    correlations[outcome2][outcome1] = 0.0
        
        return correlations
    
    def _determine_overall_trend(
        self, 
        outcome_trends: Dict[str, TrendData]
    ) -> Tuple[TrendType, MarketCondition]:
        """Określa ogólny trend i warunek rynku"""
        if not outcome_trends:
            return TrendType.STABLE, MarketCondition.NORMAL
        
        # Badanie trendów
        up_trends = 0
        down_trends = 0
        stable_trends = 0
        volatile_trends = 0
        
        for trend in outcome_trends.values():
            if trend.trend_type in [TrendType.STRONG_UP, TrendType.MODERATE_UP, TrendType.WEAK_UP]:
                up_trends += 1
            elif trend.trend_type in [TrendType.STRONG_DOWN, TrendType.MODERATE_DOWN, TrendType.WEAK_DOWN]:
                down_trends += 1
            elif trend.trend_type == TrendType.STABLE:
                stable_trends += 1
            else:
                volatile_trends += 1
        
        total = up_trends + down_trends + stable_trends + volatile_trends
        
        # Określ ogólny trend
        if up_trends > down_trends and up_trends > stable_trends:
            if up_trends / total > 0.7:
                overall_trend = TrendType.STRONG_UP
            elif up_trends / total > 0.5:
                overall_trend = TrendType.MODERATE_UP
            else:
                overall_trend = TrendType.WEAK_UP
        elif down_trends > up_trends and down_trends > stable_trends:
            if down_trends / total > 0.7:
                overall_trend = TrendType.STRONG_DOWN
            elif down_trends / total > 0.5:
                overall_trend = TrendType.MODERATE_DOWN
            else:
                overall_trend = TrendType.WEAK_DOWN
        else:
            overall_trend = TrendType.STABLE
        
        # Określ warunek rynku
        avg_volatility = sum(
            t.std_dev for t in outcome_trends.values()
        ) / len(outcome_trends)
        
        if volatile_trends / total > 0.5:
            market_condition = MarketCondition.UNCERTAIN
        elif avg_volatility > TREND_THRESHOLDS['volatile']:
            market_condition = MarketCondition.SHARP_MOVEMENT
        elif up_trends > down_trends * 2:
            market_condition = MarketCondition.BULLISH
        elif down_trends > up_trends * 2:
            market_condition = MarketCondition.BEARISH
        else:
            market_condition = MarketCondition.NORMAL
        
        return overall_trend, market_condition
    
    def _generate_signals(
        self, 
        outcome_trends: Dict[str, TrendData],
        correlations: Dict[str, Dict[str, float]]
    ) -> List[Dict[str, Any]]:
        """Generuje sygnały na podstawie analizy trendów"""
        signals = []
        
        for outcome, trend in outcome_trends.items():
            # 1. Sygnał na podstawie trendaregresji
            if trend.slope != 0 and trend.prediction_confidence > 0.5:
                signal = self._create_trend_based_signal(trend)
                if signal:
                    signals.append(signal.to_dict())
            
            # 2. Sygnal na podstawie odchylenia od fair odds
            if self.odds_aggregator:
                try:
                    # Pobierz zagregowane dane
                    aggregated = self.odds_aggregator.aggregate_odds(
                        trend.match_id,
                        self._convert_market_type(trend.market_type)
                    )
                    
                    if outcome in aggregated.aggregated_values:
                        value_signal = self._create_value_based_signal(
                            trend, aggregated, outcome
                        )
                        if value_signal:
                            signals.append(value_signal.to_dict())
                except:
                    pass
            
            # 3. Sygnał na podstawie korelacji
            correlation_signal = self._create_correlation_based_signal(
                outcome, trend, correlations
            )
            if correlation_signal:
                signals.append(correlation_signal.to_dict())
        
        return signals
    
    def _create_trend_based_signal(self, trend: TrendData) -> Optional[MarketSignal]:
        """Tworzy sygnał na podstawie trendu"""
        if trend.slope == 0:
            return None
        
        # Określ typ sygnału
        if trend.slope < 0:  # Kurs spada (staje się bardziej atrakcyjny)
            if trend.trend_type in [TrendType.STRONG_DOWN, TrendType.MODERATE_DOWN]:
                signal_type = SignalType.STRONG_BUY
                strength = trend.trend_strength
            else:
                signal_type = SignalType.BUY
                strength = trend.trend_strength * 0.7
        else:  # Kurs rośnie (staje się mniej atrakcyjny)
            if trend.trend_type in [TrendType.STRONG_UP, TrendType.MODERATE_UP]:
                signal_type = SignalType.STRONG_SELL
                strength = trend.trend_strength
            else:
                signal_type = SignalType.SELL
                strength = trend.trend_strength * 0.7
        
        return MarketSignal(
            signal_type=signal_type,
            strength=strength,
            confidence=min(0.95, trend.prediction_confidence + 0.1),
            source_outcome=trend.outcome,
            current_odds=trend.current_odds,
            expected_odds=trend.predicted_next,
            expected_value=(trend.predicted_next - trend.current_odds) / trend.current_odds if trend.current_odds > 0 else 0,
            risk_level=self._assess_risk_level(trend),
            urgency=self._assess_urgency(trend),
            description=f"{signal_type.value.replace('_', ' ').title()} signal for {trend.outcome}",
            reasoning=f"Based on trend analysis: {trend.trend_type.value.replace('_', ' ')} ({trend.slope:.4f} slope)"
        )
    
    def _create_value_based_signal(
        self, 
        trend: TrendData,
        aggregated: 'AggregatedOdds',
        outcome: str
    ) -> Optional[MarketSignal]:
        """Tworzy sygnał na podstawie analizy value"""
        current_odds = aggregated.aggregated_values.get(outcome, 0)
        fair_odds = aggregated.fair_odds.get(outcome, current_odds)
        
        if current_odds <= 0 or fair_odds <= 0:
            return None
        
        # Oblicz EV
        prob = 1.0 / fair_odds if fair_odds > 0 else 0
        ev = (current_odds * prob) - 1
        value_rating = ev * 100
        
        # Określ typ sygnału
        if value_rating > 15:  # Wysoka wartość
            signal_type = SignalType.STRONG_BUY
            strength = min(1.0, value_rating / 30)
            confidence = min(0.95, aggregated.confidence_score + 0.1)
        elif value_rating > 5:  # Umiarkowana wartość
            signal_type = SignalType.BUY
            strength = min(1.0, value_rating / 15)
            confidence = min(0.90, aggregated.confidence_score)
        elif value_rating < -15:  # Przewartościowany
            signal_type = SignalType.STRONG_SELL
            strength = min(1.0, abs(value_rating) / 30)
            confidence = min(0.95, aggregated.confidence_score + 0.1)
        elif value_rating < -5:  # Lekko przewartościowany
            signal_type = SignalType.SELL
            strength = min(1.0, abs(value_rating) / 15)
            confidence = min(0.90, aggregated.confidence_score)
        else:
            return None  # Brak sygnału
        
        return MarketSignal(
            signal_type=signal_type,
            strength=strength,
            confidence=confidence,
            source_outcome=outcome,
            current_odds=current_odds,
            expected_odds=fair_odds,
            fair_odds=fair_odds,
            expected_value=ev,
            probability=prob,
            risk_level=self._assess_risk_level_from_odds(current_odds, aggregated),
            urgency=self._assess_urgency_from_ev(ev),
            description=f"{signal_type.value.replace('_', ' ').title()} signal for {outcome}",
            reasoning=f"Value analysis: EV={ev:.3f}, Value Rating={value_rating:.1f}%"
        )
    
    def _create_correlation_based_signal(
        self,
        outcome: str,
        trend: TrendData,
        correlations: Dict[str, Dict[str, float]]
    ) -> Optional[MarketSignal]:
        """Tworzy sygnał na podstawie korelacji"""
        if outcome not in correlations:
            return None
        
        # Znajdź najsilniejszą negatywną korelację
        strongest_negative_corr = 0
        correlated_outcome = None
        
        for other_outcome, corr in correlations[outcome].items():
            if corr < strongest_negative_corr and other_outcome != outcome:
                strongest_negative_corr = corr
                correlated_outcome = other_outcome
        
        # Jeśli silna negatywna korelacja i trend w dół
        if (strongest_negative_corr < -0.8 and 
            trend.trend_type in [TrendType.STRONG_DOWN, TrendType.MODERATE_DOWN]):
            
            other_trend = self._trend_cache.get(f"{trend.match_id}_{trend.market_type}_{correlated_outcome}")
            
            if other_trend and other_trend.trend_type in [TrendType.STRONG_UP, TrendType.MODERATE_UP]:
                return MarketSignal(
                    signal_type=SignalType.STRONG_BUY,
                    strength=0.8,
                    confidence=0.75,
                    source_outcome=outcome,
                    target_outcome=correlated_outcome,
                    current_odds=trend.current_odds,
                    description=f"Strong BUY signal: {outcome} and {correlated_outcome} are negatively correlated",
                    reasoning=f"Negative correlation ({strongest_negative_corr:.3f}) with opposite trends"
                )
        
        return None
    
    def _assess_risk_level(self, trend: TrendData) -> str:
        """Ocenia poziom ryzyka"""
        if trend.std_dev > TREND_THRESHOLDS['volatile']:
            return "very_high"
        elif trend.std_dev > TREND_THRESHOLDS['volatile'] / 2:
            return "high"
        elif trend.trend_strength > 0.7:
            return "medium"
        else:
            return "low"
    
    def _assess_risk_level_from_odds(self, odds: float, aggregated: 'AggregatedOdds') -> str:
        """Ocenia poziom ryzyka na podstawie kursów"""
        if odds > 5.0:
            return "very_high"  # Very long shot
        elif odds > 3.0:
            return "high"
        elif odds > 2.0:
            return "medium"
        else:
            return "low"
    
    def _assess_urgency(self, trend: TrendData) -> str:
        """Ocenia pilność"""
        if trend.trend_strength > 0.8:
            return "high"
        elif trend.trend_strength > 0.5:
            return "medium"
        else:
            return "low"
    
    def _assess_urgency_from_ev(self, ev: float) -> str:
        """Ocenia pilność na podstawie EV"""
        if abs(ev) > 0.2:
            return "high"
        elif abs(ev) > 0.1:
            return "medium"
        else:
            return "low"
    
    def _generate_recommendations(
        self,
        outcome_trends: Dict[str, TrendData],
        correlations: Dict[str, Dict[str, float]],
        signals: List[Dict[str, Any]]
    ) -> List[Dict[str, Any]]:
        """Generuje rekomendacje na podstawie sygnałów"""
        recommendations = []
        
        # Grupa sygnałów po typie
        signals_by_type = defaultdict(list)
        for signal_data in signals:
            signal = MarketSignal.from_dict(signal_data)
            signals_by_type[signal.signal_type].append(signal)
        
        # Rekomendacja ogólna
        buy_count = len(signals_by_type.get(SignalType.STRONG_BUY, [])) + \
                    len(signals_by_type.get(SignalType.BUY, []))
        sell_count = len(signals_by_type.get(SignalType.STRONG_SELL, [])) + \
                     len(signals_by_type.get(SignalType.SELL, []))
        
        if buy_count > sell_count:
            recommendations.append({
                'type': 'overall_position',
                'action': 'consider_betting',
                'strength': min(1.0, buy_count / max(1, len(signals))),
                'confidence': statistics.mean([
                    s.confidence for s in signals_by_type.get(SignalType.STRONG_BUY, []) + 
                    signals_by_type.get(SignalType.BUY, [])
                ]) if (signals_by_type.get(SignalType.STRONG_BUY, []) or signals_by_type.get(SignalType.BUY, [])) else 0.0,
                'rationale': f"{buy_count} BUY signals vs {sell_count} SELL signals",
                'risk_level': 'medium'
            })
        elif sell_count > buy_count:
            recommendations.append({
                'type': 'overall_position',
                'action': 'avoid_betting',
                'strength': min(1.0, sell_count / max(1, len(signals))),
                'confidence': statistics.mean([
                    s.confidence for s in signals_by_type.get(SignalType.STRONG_SELL, []) + 
                    signals_by_type.get(SignalType.SELL, [])
                ]) if (signals_by_type.get(SignalType.STRONG_SELL, []) or signals_by_type.get(SignalType.SELL, [])) else 0.0,
                'rationale': f"{sell_count} SELL signals vs {buy_count} BUY signals",
                'risk_level': 'medium'
            })
        
        # Rekomendacje per-outcome
        for outcome, signals_list in signals_by_type.items():
            if len(signals_list) > 0:
                # Najsilniejszy sygnał dla tego outcome
                strongest_signal = max(signals_list, key=lambda s: s.strength * s.confidence)
                
                recommendations.append({
                    'type': 'outcome_specific',
                    'outcome': strongest_signal.source_outcome,
                    'action': strongest_signal.signal_type.value,
                    'strength': strongest_signal.strength,
                    'confidence': strongest_signal.confidence,
                    'current_odds': strongest_signal.current_odds,
                    'expected_odds': strongest_signal.expected_odds,
                    'expected_value': strongest_signal.expected_value,
                    'risk_level': strongest_signal.risk_level,
                    'urgency': strongest_signal.urgency,
                    'rationale': strongest_signal.description
                })
        
        # Rekomendacje arbitrażowe
        if self.odds_aggregator:
            try:
                arbitrages = self.odds_aggregator.detect_arbitrage_opportunities(
                    list(outcome_trends.values())[0].match_id
                )
                
                for combo, metrics in arbitrages.items():
                    if metrics.get('profit_percent', 0) > 2.0:  # >2% zysk
                        recommendations.append({
                            'type': 'arbitrage_opportunity',
                            'combination': combo,
                            'profit_percent': metrics['profit_percent'],
                            'risk_level': 'low',
                            'confidence': 0.9,
                            'action': 'exploit_arbitrage',
                            'rationale': f"Risk-free opportunity with {metrics['profit_percent']:.2f}% profit"
                        })
            except:
                pass
        
        return recommendations
    
    # ========================================================================
    # PREDICTION FUNCTIONS
    # ========================================================================
    
    def predict_odds_movement(
        self,
        match_id: str,
        market_type: str = "match_result",
        outcome: str = None,
        steps_ahead: int = 3
    ) -> Dict[str, Dict[str, Any]]:
        """
        Przewiduje ruch kursów.
        
        Args:
            match_id: ID meczu
            market_type: Typ rynku
            outcome: Konkretny outcome (opcjonalnie)
            steps_ahead: Ile kroków do przodu
            
        Returns:
            Dict[outcome, prediction_info]
        """
        predictions = {}
        
        # Analiza trendów
        analysis = self.analyze_trends(match_id, market_type)
        
        for out, trend in analysis.outcome_trends.items():
            if outcome and out != outcome:
                continue
            
            if trend.slope == 0:
                predictions[out] = {
                    'predicted_values': [trend.current_odds] * steps_ahead,
                    'confidence': 0.0,
                    'trend_type': trend.trend_type.value,
                    'message': 'No trend detected'
                }
                continue
            
            # Regresja wielomianowa
            try:
                # Przygotuj dane
                X = np.array([i for i in range(len(trend.odds_values))]).reshape(-1, 1)
                y = np.array(trend.odds_values)
                
                # Dopasuj model wielomianowy (stopień 2)
                poly = PolynomialFeatures(degree=2)
                X_poly = poly.fit_transform(X)
                
                from sklearn.linear_model import LinearRegression
                model = LinearRegression(fit_intercept=True)
                model.fit(X_poly, y)
                
                # Przewiduj
                future_steps = [len(trend.odds_values) + i for i in range(1, steps_ahead + 1)]
                X_future = poly.transform(np.array(future_steps).reshape(-1, 1))
                predicted_values = model.predict(X_future).tolist()
                
                # Confidence na podstawie R^2
                r_squared = model.score(X_poly, y)
                confidence = min(0.95, max(0.0, r_squared))
                
                # Sprawdź czy prediction ma sens (tzn. jest dodatni)
                predicted_values = [max(1.01, p) for p in predicted_values]
                
                predictions[out] = {
                    'predicted_values': [float(p) for p in predicted_values],
                    'confidence': float(confidence),
                    'trend_type': trend.trend_type.value,
                    'slope': float(trend.slope),
                    'r_squared': float(trend.r_squared),
                    'current_odds': float(trend.current_odds),
                    'predicted_next': float(trend.predicted_next),
                    'message': f'Predicted based on {trend.trend_type.value} trend'
                }
            except Exception as e:
                predictions[out] = {
                    'predicted_values': [trend.current_odds] * steps_ahead,
                    'confidence': 0.0,
                    'trend_type': trend.trend_type.value,
                    'error': str(e),
                    'message': 'Prediction failed'
                }
        
        return predictions
    
    def detect_market_anomalies(
        self,
        match_id: str,
        market_type: str = "match_result",
        threshold_std: float = 2.0
    ) -> Dict[str, Dict[str, Any]]:
        """
        Wykrywa anomalie rynkowe.
        
        Args:
            match_id: ID meczu
            market_type: Typ rynku
            threshold_std: Próg odchylenia standardowego
            
        Returns:
            Dict[outcome, anomaly_info]
        """
        anomalies = {}
        
        try:
            analysis = self.analyze_trends(match_id, market_type)
            
            # Oblicz średnią i odchylenie standardowe dla całego rynku
            all_odds = []
            for trend in analysis.outcome_trends.values():
                all_odds.extend(trend.odds_values)
            
            if all_odds:
                mean_odds = statistics.mean(all_odds)
                std_odds = statistics.stdev(all_odds) if len(all_odds) > 1 else 0
            else:
                return anomalies
            
            # Sprawdź każdy trend
            for outcome, trend in analysis.outcome_trends.items():
                if not trend.odds_values:
                    continue
                
                current = trend.current_odds
                
                # Anomalia 1: Odchylenie od średniej
                z_score = abs(current - mean_odds) / std_odds if std_odds > 0 else 0
                
                if z_score > threshold_std:
                    anomalies[outcome] = {
                        'type': 'outlier',
                        'z_score': z_score,
                        'value': current,
                        'mean': mean_odds,
                        'std': std_odds,
                        'severity': min(1.0, z_score / 3.0),
                        'message': f"Outlier detected: {z_score:.2f} std deviations from mean"
                    }
                
                # Anomalia 2: Gwałtowne zmiany
                if len(trend.odds_values) >= 2:
                    recent_change = trend.odds_values[-1] - trend.odds_values[-2]
                    avg_change = statistics.mean([
                        trend.odds_values[i] - trend.odds_values[i-1] 
                        for i in range(1, len(trend.odds_values))
                    ]) if len(trend.odds_values) > 1 else 0
                    std_change = statistics.stdev([
                        trend.odds_values[i] - trend.odds_values[i-1] 
                        for i in range(1, len(trend.odds_values))
                    ]) if len(trend.odds_values) > 2 else 0
                    
                    if std_change > 0:
                        change_z_score = abs(recent_change - avg_change) / std_change
                        
                        if change_z_score > 2.5:
                            anomalies[outcome] = {
                                'type': 'sharp_movement',
                                'z_score': change_z_score,
                                'change': recent_change,
                                'message': f"Sharp movement: {change_z_score:.2f} std deviations from average change"
                            }
            
            # Anomalia 3: Niskie korelacje (możliwa błęędna cena)
            for outcome, corr_dict in analysis.correlations.items():
                avg_corr = statistics.mean(list(corr_dict.values())) if corr_dict else 0
                
                if avg_corr < -0.3:  # Ujemna korelacja ( nietypowe)
                    if outcome not in anomalies or anomalies[outcome]['severity'] < 0.7:
                        anomalies[outcome] = {
                            'type': 'negative_correlation',
                            'avg_correlation': avg_corr,
                            'message': f"Unusually low correlation with other outcomes ({avg_corr:.3f})"
                        }
        
        except Exception:
            pass
        
        return anomalies
    
    # ========================================================================
    # MARKET TREND REPORTS
    # ========================================================================
    
    def generate_market_report(
        self,
        match_id: str,
        market_type: str = "match_result"
    ) -> Dict[str, Any]:
        """Generuje kompleksowy raport rynkowy"""
        import time
        start_time = time.time()
        
        report = {
            'match_id': match_id,
            'market_type': market_type,
            'generated_at': datetime.now().isoformat(),
            'sections': {}
        }
        
        try:
            # Sekcja 1: Podsumowanie
            analysis = self.analyze_trends(match_id, market_type)
            report['sections']['summary'] = {
                'overall_trend': analysis.overall_trend.value,
                'market_condition': analysis.market_condition.value,
                'analysis_duration': analysis.analysis_duration,
                'data_points': analysis.data_points,
                'outcomes_analyzed': len(analysis.outcome_trends)
            }
            
            # Sekcja 2: Trendy per outcome
            report['sections']['outcome_trends'] = {
                outcome: {
                    'trend_type': trend.trend_type.value,
                    'trend_strength': trend.trend_strength,
                    'current_odds': trend.current_odds,
                    'slope': trend.slope,
                    'r_squared': trend.r_squared,
                    'mean': trend.mean,
                    'std_dev': trend.std_dev,
                    'predicted_next': trend.predicted_next
                }
                for outcome, trend in analysis.outcome_trends.items()
            }
            
            # Sekcja 3: Korelacje
            report['sections']['correlations'] = {
                outcome: {corr_outcome: round(corr, 4) 
                        for corr_outcome, corr in correlations.items()}
                for outcome, correlations in analysis.correlations.items()
            }
            
            # Sekcja 4: Sygnały
            report['sections']['signals'] = []
            for signal_data in analysis.signals:
                signal = MarketSignal.from_dict(signal_data)
                report['sections']['signals'].append({
                    'type': signal.signal_type.value,
                    'strength': signal.strength,
                    'confidence': signal.confidence,
                    'outcome': signal.source_outcome,
                    'current_odds': signal.current_odds,
                    'expected_value': signal.expected_value,
                    'description': signal.description
                })
            
            # Sekcja 5: Rekomendacje
            report['sections']['recommendations'] = []
            for rec in analysis.recommendations:
                report['sections']['recommendations'].append({
                    'type': rec.get('type', 'unknown'),
                    'action': rec.get('action', ''),
                    'strength': rec.get('strength', 0),
                    'confidence': rec.get('confidence', 0),
                    'rationale': rec.get('rationale', '')
                })
            
            # Sekcja 6: Predykcje
            predictions = self.predict_odds_movement(match_id, market_type)
            report['sections']['predictions'] = {
                outcome: {
                    'predicted_next': info.get('predicted_next'),
                    'confidence': info.get('confidence', 0),
                    'trend_type': info.get('trend_type', 'unknown')
                }
                for outcome, info in predictions.items()
            }
            
            # Sekcja 7: Anomalie
            anomalies = self.detect_market_anomalies(match_id, market_type)
            report['sections']['anomalies'] = anomalies
            
            # Sekcja 8: Statystyki agregatora
            if self.odds_aggregator:
                report['sections']['aggregator_stats'] = self.odds_aggregator.get_statistics()
            
            report['generation_time'] = time.time() - start_time
            report['status'] = 'success'
            
        except Exception as e:
            report['status'] = 'error'
            report['error'] = str(e)
            report['generation_time'] = time.time() - start_time
        
        return report
    
    # ========================================================================
    # UTILITY FUNCTIONS
    # ========================================================================
    
    def _convert_market_type(self, market_type: str) -> 'MarketType':
        """Konwertuje string na MarketType"""
        from .odds_aggregator import MarketType
        
        if isinstance(market_type, MarketType):
            return market_type
        
        try:
            return MarketType(market_type)
        except ValueError:
            return MarketType.MATCH_RESULT
    
    def set_odds_aggregator(self, aggregator: 'OddsAggregator') -> None:
        """Ustawia powiązanie z OddsAggregator"""
        self.odds_aggregator = aggregator
    
    def get_trend_history(
        self,
        match_id: str = None,
        limit: int = 100
    ) -> List[TrendData]:
        """Zwraca historię trendów"""
        with self._lock:
            if match_id:
                return [
                    t for t in self._trend_history 
                    if t.match_id == match_id
                ][-limit:]
            return self._trend_history[-limit:]
    
    def get_analysis_history(
        self,
        match_id: str = None,
        limit: int = 50
    ) -> List[MarketTrendAnalysis]:
        """Zwraca historię analiz"""
        with self._lock:
            if match_id:
                return [
                    a for a in self._analysis_history 
                    if a.match_id == match_id
                ][-limit:]
            return self._analysis_history[-limit:]
    
    def get_statistics(self) -> Dict[str, Any]:
        """Zwraca statystyki analizatora"""
        with self._lock:
            return {
                **self.stats,
                'trend_cache_size': len(self._trend_cache),
                'analysis_cache_size': len(self._analysis_cache),
                'signal_cache_size': len(self._signal_cache),
                'trend_history_size': len(self._trend_history),
                'analysis_history_size': len(self._analysis_history)
            }
    
    def clear_cache(self) -> None:
        """Czyści wszystkie cache"""
        with self._lock:
            self._trend_cache.clear()
            self._analysis_cache.clear()
            self._signal_cache.clear()
            self._trend_history.clear()
            self._analysis_history.clear()
    
    # ========================================================================
    # PERSISTENCE
    # ========================================================================
    
    def save_report(
        self,
        report: Dict[str, Any],
        filename: str = None
    ) -> str:
        """Zapisuje raport do pliku"""
        if filename is None:
            timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
            match_id = report.get('match_id', 'unknown')
            filename = f"market_report_{match_id}_{timestamp}.json"
        
        filepath = os.path.join(self.data_dir, filename)
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(report, f, ensure_ascii=False, indent=2)
        
        return filepath
    
    def load_report(self, filepath: str) -> Dict[str, Any]:
        """Wczytuje raport z pliku"""
        filepath = os.path.join(self.data_dir, filepath)
        
        if os.path.exists(filepath):
            with open(filepath, 'r', encoding='utf-8') as f:
                return json.load(f)
        
        return {}
    
    def save_state(self, filepath: str = None) -> None:
        """Zapisuje stan analizatora"""
        if filepath is None:
            filepath = os.path.join(self.data_dir, "market_trends_analyzer_state.json")
        
        state = {
            'stats': self.stats,
            'trend_cache': [t.to_dict() for t in self._trend_cache.values()],
            'analysis_cache': [a.to_dict() for a in self._analysis_cache.values()]
        }
        
        with open(filepath, 'w', encoding='utf-8') as f:
            json.dump(state, f, ensure_ascii=False, indent=2)
    
    def load_state(self, filepath: str = None) -> None:
        """Wczytuje stan analizatora"""
        if filepath is None:
            filepath = os.path.join(self.data_dir, "market_trends_analyzer_state.json")
        
        if not os.path.exists(filepath):
            return
        
        with open(filepath, 'r', encoding='utf-8') as f:
            state = json.load(f)
        
        with self._lock:
            self.stats.update(state.get('stats', {}))
            
            for trend_dict in state.get('trend_cache', []):
                trend = TrendData.from_dict(trend_dict)
                cache_key = f"{trend.match_id}_{trend.market_type}_{trend.outcome}"
                self._trend_cache[cache_key] = trend
            
            for analysis_dict in state.get('analysis_cache', []):
                analysis = MarketTrendAnalysis.from_dict(analysis_dict)
                cache_key = f"{analysis.match_id}_{analysis.market_type}"
                self._analysis_cache[cache_key] = analysis
