# SSI V5 Feedback Tests - Comprehensive Test Suite
# ================================================
#
# ETAP: 5.2.8.8 - Comprehensive Tests
# Data: 2026-08-04
#
# Odpowiedzialnosc:
# - Pełna suita testów (>40 testów)
# - Testowanie wszystkich komponentów Feedback Loop
# - Pokrycie: prediction vs result, ocena, fitness, memory, evolution, isolation
#
# Uruchomienie:
# python -m SSI_V5.feedback.tests.test_feedback_comprehensive
#
# Generated by Mistral Vibe.
# Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

import unittest
import sys
import os
from datetime import datetime
from pathlib import Path
import tempfile
import shutil
import json

# Dodaj SSI_V5 do path
sys.path.insert(0, str(Path(__file__).parent.parent.parent))

from SSI_V5.feedback.feedback_models import (
    PredictionOutcome,
    StrategyFitness,
    FeedbackEvent,
    FeedbackEventType,
    EvaluationStatus,
    OutcomeType,
    create_prediction_outcome_from_trace_and_result,
    create_feedback_event
)

from SSI_V5.feedback.prediction_evaluator import (
    PredictionEvaluator,
    EvaluationResult,
    ExactScoreEvaluation,
    ResultEvaluation,
    GoalsEvaluation,
    create_evaluator
)

from SSI_V5.feedback.fitness_calculator import (
    StrategyFitnessCalculator,
    FitnessWeights,
    FitnessComponents,
    calculate_accumulative_fitness,
    calculate_stability_metric,
    create_fitness_calculator
)

from SSI_V5.feedback.feedback_engine import (
    FeedbackEngine,
    FeedbackConfig,
    FeedbackContext,
    FeedbackPipeline,
    create_feedback_engine
)


# ============================================================================
# KONFIGURACJA TESTOW
# ============================================================================

class TestConfiguration:
    """Konfiguracja testów."""
    TEMP_DIR = None
    
    @classmethod
    def setup_temp_dir(cls):
        """Tworzy tymczasowy katalog."""
        cls.TEMP_DIR = tempfile.mkdtemp()
        return cls.TEMP_DIR
    
    @classmethod
    def cleanup_temp_dir(cls):
        """Czyści tymczasowy katalog."""
        if cls.TEMP_DIR and os.path.exists(cls.TEMP_DIR):
            shutil.rmtree(cls.TEMP_DIR, ignore_errors=True)
            cls.TEMP_DIR = None


# ============================================================================
# TESTY MODELI (10 testów)
# ============================================================================

class TestFeedbackModels(unittest.TestCase):
    """Testy Feedback Models."""
    
    def setUp(self):
        """Setup."""
        self.maxDiff = None
    
    def test_prediction_outcome_creation(self):
        """Test tworzenia PredictionOutcome."""
        outcome = PredictionOutcome(
            strategy_id="test_strategy",
            predicted_result="1",
            actual_result="1"
        )
        self.assertEqual(outcome.strategy_id, "test_strategy")
        self.assertEqual(outcome.predicted_result, "1")
        self.assertEqual(outcome.actual_result, "1")
    
    def test_prediction_outcome_calculate_scores_exact(self):
        """Test obliczania wyników - dokładne trafienie."""
        outcome = PredictionOutcome(
            strategy_id="test",
            predicted_result="1",
            actual_result="1",
            predicted_home_goals=2,
            predicted_away_goals=1,
            actual_home_goals=2,
            actual_away_goals=1
        )
        outcome.calculate_scores()
        
        self.assertTrue(outcome.exact_score)
        self.assertTrue(outcome.result_correct)
        self.assertTrue(outcome.goals_correct)
        self.assertTrue(outcome.is_exact())
        self.assertTrue(outcome.is_correct())
    
    def test_prediction_outcome_calculate_scores_partial(self):
        """Test obliczania wyników - częściowo poprawne."""
        outcome = PredictionOutcome(
            strategy_id="test",
            predicted_result="1",
            actual_result="1",
            predicted_home_goals=3,
            predicted_away_goals=0,
            actual_home_goals=2,
            actual_away_goals=1
        )
        outcome.calculate_scores()
        
        self.assertFalse(outcome.exact_score)
        self.assertTrue(outcome.result_correct)
        self.assertFalse(outcome.goals_correct)
        self.assertFalse(outcome.is_exact())
        self.assertTrue(outcome.is_correct())
    
    def test_prediction_outcome_calculate_scores_wrong(self):
        """Test obliczania wyników - zupełnie błędne."""
        outcome = PredictionOutcome(
            strategy_id="test",
            predicted_result="1",
            actual_result="2"
        )
        outcome.calculate_scores()
        
        self.assertFalse(outcome.exact_score)
        self.assertFalse(outcome.result_correct)
        self.assertFalse(outcome.is_exact())
        self.assertFalse(outcome.is_correct())
    
    def test_strategy_fitness_add_outcome(self):
        """Test dodawania outcome do StrategyFitness."""
        fitness = StrategyFitness(strategy_id="test_strategy")
        
        # Dodaj poprawną predykcję
        outcome = PredictionOutcome(
            strategy_id="test_strategy",
            predicted_result="1",
            actual_result="1"
        )
        outcome.calculate_scores()
        fitness.add_prediction_outcome(outcome)
        
        self.assertEqual(fitness.total_predictions, 1)
        self.assertEqual(fitness.correct_predictions, 1)
    
    def test_strategy_fitness_ranking(self):
        """Test rankingu strategii."""
        fitness = StrategyFitness(
            strategy_id="test",
            overall_fitness=0.95,
            accuracy=0.95
        )
        self.assertEqual(fitness.get_ranking(), "A+ (EXCELLENT)")
    
    def test_feedback_event_creation(self):
        """Test tworzenia FeedbackEvent."""
        event = FeedbackEvent(
            event_type=FeedbackEventType.PREDICTION_CREATED,
            strategy_id="test_strategy",
            feedback_loop_id="loop_001"
        )
        
        self.assertEqual(event.event_type, FeedbackEventType.PREDICTION_CREATED)
        self.assertEqual(event.strategy_id, "test_strategy")
        self.assertTrue(event.is_success())
    
    def test_feedback_event_mark_failure(self):
        """Test zaznaczania Failured FeedbackEvent."""
        event = FeedbackEvent(
            event_type=FeedbackEventType.EVALUATION_COMPLETED
        )
        event.mark_failure("Test error")
        
        self.assertFalse(event.is_success())
        self.assertEqual(event.error_message, "Test error")
    
    def test_serialization_prediction_outcome(self):
        """Test serializacji PredictionOutcome."""
        outcome = PredictionOutcome(
            strategy_id="test",
            predicted_result="1",
            actual_result="1"
        )
        
        # to_dict
        data = outcome.to_dict()
        self.assertIsInstance(data, dict)
        
        # from_dict
        outcome2 = PredictionOutcome.from_dict(data)
        self.assertEqual(outcome2.strategy_id, outcome.strategy_id)
        
        # to_json
        json_str = outcome.to_json()
        self.assertIsInstance(json_str, str)
        
        # from_json
        outcome3 = PredictionOutcome.from_json(json_str)
        self.assertEqual(outcome3.strategy_id, outcome.strategy_id)
    
    def test_serialization_strategy_fitness(self):
        """Test serializacji StrategyFitness."""
        fitness = StrategyFitness(strategy_id="test")
        
        # to_dict
        data = fitness.to_dict()
        self.assertIsInstance(data, dict)
        
        # from_dict
        fitness2 = StrategyFitness.from_dict(data)
        self.assertEqual(fitness2.strategy_id, fitness.strategy_id)


# ============================================================================
# TESTY PREDICTION EVALUATOR (8 testów)
# ============================================================================

class TestPredictionEvaluator(unittest.TestCase):
    """Testy PredictionEvaluator."""
    
    def setUp(self):
        """Setup."""
        self.evaluator = PredictionEvaluator()
    
    def test_exact_match_evaluation(self):
        """Test ewaluacji - dokładne trafienie."""
        prediction_trace = {
            'trace_id': 'trace_001',
            'prediction': {
                'result': '1',
                'confidence': 0.8,
                'model_output': {'home_goals': 2, 'away_goals': 1}
            }
        }
        
        match_result = {
            'match_id': 'match_001',
            'home_goals': 2,
            'away_goals': 1,
            'result': '1'
        }
        
        evaluation = self.evaluator.evaluate(prediction_trace, match_result)
        
        self.assertTrue(evaluation.exact_score)
        self.assertTrue(evaluation.result_correct)
        self.assertEqual(evaluation.status, EvaluationStatus.EXACT)
        self.assertEqual(evaluation.accuracy_score, 1.0)
    
    def test_result_correct_goals_wrong(self):
        """Test ewaluacji - poprawny wynik, błędne gole."""
        prediction_trace = {
            'trace_id': 'trace_002',
            'prediction': {
                'result': '1',
                'model_output': {'home_goals': 3, 'away_goals': 0}
            }
        }
        
        match_result = {
            'match_id': 'match_002',
            'home_goals': 2,
            'away_goals': 1,
            'result': '1'
        }
        
        evaluation = self.evaluator.evaluate(prediction_trace, match_result)
        
        self.assertFalse(evaluation.exact_score)
        self.assertTrue(evaluation.result_correct)
        self.assertEqual(evaluation.status, EvaluationStatus.PARTIAL)
        self.assertGreater(evaluation.accuracy_score, 0)
        self.assertLess(evaluation.accuracy_score, 1.0)
    
    def test_completely_wrong_prediction(self):
        """Test ewaluacji - zupełnie błędna predykcja."""
        prediction_trace = {
            'trace_id': 'trace_003',
            'prediction': {
                'result': '1',
                'model_output': {'home_goals': 3, 'away_goals': 0}
            }
        }
        
        match_result = {
            'match_id': 'match_003',
            'home_goals': 0,
            'away_goals': 2,
            'result': '2'
        }
        
        evaluation = self.evaluator.evaluate(prediction_trace, match_result)
        
        self.assertFalse(evaluation.exact_score)
        self.assertFalse(evaluation.result_correct)
        self.assertEqual(evaluation.status, EvaluationStatus.INCORRECT)
        self.assertEqual(evaluation.accuracy_score, 0.0)
    
    def test_draw_prediction(self):
        """Test ewaluacji - remis."""
        prediction_trace = {
            'trace_id': 'trace_004',
            'prediction': {
                'result': 'X',
                'model_output': {'home_goals': 1, 'away_goals': 1}
            }
        }
        
        match_result = {
            'match_id': 'match_004',
            'home_goals': 1,
            'away_goals': 1,
            'result': 'X'
        }
        
        evaluation = self.evaluator.evaluate(prediction_trace, match_result)
        
        self.assertTrue(evaluation.exact_score)
        self.assertTrue(evaluation.result_correct)
        self.assertEqual(evaluation.status, EvaluationStatus.EXACT)
    
    def test_conversion_to_outcome(self):
        """Test konwersji EvaluationResult do PredictionOutcome."""
        prediction_trace = {
            'trace_id': 'trace_005',
            'prediction': {'result': '1', 'model_output': {'home_goals': 2, 'away_goals': 1}}
        }
        
        match_result = {
            'match_id': 'match_005',
            'home_goals': 2,
            'away_goals': 1,
            'result': '1'
        }
        
        outcome = self.evaluator.evaluate_to_outcome(prediction_trace, match_result)
        
        self.assertIsInstance(outcome, PredictionOutcome)
        self.assertTrue(outcome.exact_score)
        self.assertTrue(outcome.result_correct)
    
    def test_batch_evaluation(self):
        """Test ewaluacji batch."""
        traces = [
            {'trace_id': f'trace_{i}', 'prediction': {'result': '1', 'model_output': {'home_goals': 2, 'away_goals': 1}}}
            for i in range(3)
        ]
        
        results_list = [
            {'match_id': f'match_{i}', 'home_goals': 2, 'away_goals': 1, 'result': '1'}
            for i in range(3)
        ]
        
        evaluations = self.evaluator.evaluate_batch(traces, results_list)
        
        self.assertEqual(len(evaluations), 3)
        self.assertTrue(all(e.exact_score for e in evaluations))
    
    def test_evaluator_reset(self):
        """Test resetu ewaluatora."""
        self.evaluator.evaluate(
            {'prediction': {'result': '1'}},
            {'home_goals': 2, 'away_goals': 1, 'result': '1'}
        )
        
        self.assertGreater(self.evaluator.evaluation_count, 0)
        
        self.evaluator.reset()
        
        self.assertEqual(self.evaluator.evaluation_count, 0)
        self.assertEqual(len(self.evaluator.events), 0)
    
    def test_evaluator_statistics(self):
        """Test statystyk ewaluatora."""
        self.evaluator.evaluate(
            {'prediction': {'result': '1'}},
            {'home_goals': 2, 'away_goals': 1, 'result': '1'}
        )
        
        stats = self.evaluator.get_statistics()
        
        self.assertIn('total_evaluations', stats)
        self.assertIn('success_count', stats)
        self.assertIn('events', stats)


# ============================================================================
# TESTY FITNESS CALCULATOR (8 testów)
# ============================================================================

class TestFitnessCalculator(unittest.TestCase):
    """Testy StrategyFitnessCalculator."""
    
    def setUp(self):
        """Setup."""
        self.calculator = StrategyFitnessCalculator()
    
    def _create_outcome(self, correct: bool = True, exact: bool = True):
        """Helper: Tworzy PredictionOutcome."""
        outcome = PredictionOutcome(
            strategy_id="test_strategy",
            predicted_result="1" if correct else "2",
            actual_result="1",
            predicted_home_goals=2,
            predicted_away_goals=1,
            actual_home_goals=2,
            actual_away_goals=1
        )
        if exact and correct:
            outcome.predicted_home_goals = 2
            outcome.predicted_away_goals = 1
        elif correct:
            outcome.predicted_home_goals = 3
            outcome.predicted_away_goals = 0
        else:
            outcome.predicted_result = "2"
        
        outcome.calculate_scores()
        return outcome
    
    def test_perfect_fitness(self):
        """Test fitness dla idealnej strategii."""
        outcomes = [self._create_outcome(True, True) for _ in range(5)]
        
        fitness = self.calculator.calculate_fitness("perfect_strategy", outcomes)
        
        self.assertEqual(fitness.accuracy, 1.0)
        self.assertEqual(fitness.exact_accuracy, 1.0)
        self.assertEqual(fitness.overall_fitness, 1.0)
    
    def test_zero_fitness(self):
        """Test fitness dla zupełnie złej strategii."""
        outcomes = [self._create_outcome(False, False) for _ in range(5)]
        
        fitness = self.calculator.calculate_fitness("bad_strategy", outcomes)
        
        self.assertEqual(fitness.accuracy, 0.0)
        self.assertEqual(fitness.correct_predictions, 0)
        self.assertEqual(fitness.overall_fitness, 0.0)
    
    def test_partial_fitness(self):
        """Test fitness dla częściowo poprawnej strategii."""
        outcomes = [
            self._create_outcome(True, True),  # 1 poprawne
            self._create_outcome(True, True),  # 2 poprawne
            self._create_outcome(False, False), # 1 błędne
        ]
        
        fitness = self.calculator.calculate_fitness("partial_strategy", outcomes)
        
        self.assertEqual(fitness.total_predictions, 3)
        self.assertEqual(fitness.correct_predictions, 2)
        self.assertGreater(fitness.overall_fitness, 0)
        self.assertLess(fitness.overall_fitness, 1.0)
    
    def test_fitness_from_outcomes(self):
        """Test calculate_from_outcomes."""
        outcomes = [
            PredictionOutcome(
                strategy_id="strategy_A",
                predicted_result="1",
                actual_result="1"
            ),
            PredictionOutcome(
                strategy_id="strategy_B",
                predicted_result="1",
                actual_result="2"
            )
        ]
        
        for o in outcomes:
            o.calculate_scores()
        
        fitness_values = self.calculator.calculate_from_outcomes(outcomes)
        
        self.assertEqual(len(fitness_values), 2)
        self.assertIn("strategy_A", fitness_values)
        self.assertIn("strategy_B", fitness_values)
    
    def test_ranking_strategies(self):
        """Test rankingu strategii."""
        fitness_values = {
            "strategy_1": StrategyFitness(strategy_id="strategy_1", overall_fitness=0.9),
            "strategy_2": StrategyFitness(strategy_id="strategy_2", overall_fitness=0.7),
            "strategy_3": StrategyFitness(strategy_id="strategy_3", overall_fitness=0.5),
        }
        
        ranked = self.calculator.rank_strategies(fitness_values)
        
        self.assertEqual(len(ranked), 3)
        self.assertEqual(ranked[0][0], "strategy_1")
        self.assertEqual(ranked[1][0], "strategy_2")
        self.assertEqual(ranked[2][0], "strategy_3")
    
    def test_top_n_strategies(self):
        """Test top N strategii."""
        fitness_values = {
            f"strategy_{i}": StrategyFitness(
                strategy_id=f"strategy_{i}",
                overall_fitness=1.0 - (i * 0.1)
            )
            for i in range(5)
        }
        
        top_3 = self.calculator.get_top_n(fitness_values, n=3)
        
        self.assertEqual(len(top_3), 3)
        self.assertEqual(top_3[0][0], "strategy_0")
        self.assertEqual(top_3[1][0], "strategy_1")
        self.assertEqual(top_3[2][0], "strategy_2")
    
    def test_fitness_components(self):
        """Test składników fitness."""
        outcomes = [self._create_outcome(True, True) for _ in range(3)]
        
        components = self.calculator.get_components(outcomes)
        
        self.assertIsInstance(components, FitnessComponents)
        self.assertGreater(components.accuracy_component, 0)
    
    def test_calculator_reset(self):
        """Test resetu kalkulatora."""
        self.calculator.calculate_fitness("test", [self._create_outcome(True, True)])
        
        self.assertGreater(self.calculator.evaluation_count, 0)
        
        self.calculator.reset()
        
        self.assertEqual(self.calculator.evaluation_count, 0)


# ============================================================================
# TESTY FEEDBACK ENGINE (10 testów)
# ============================================================================

class TestFeedbackEngine(unittest.TestCase):
    """Testy FeedbackEngine."""
    
    def setUp(self):
        """Setup."""
        TestConfiguration.setup_temp_dir()
        config = FeedbackConfig(
            memory_dir=TestConfiguration.TEMP_DIR,
            events_log_file="test_events.json"
        )
        self.engine = FeedbackEngine(config=config)
    
    def tearDown(self):
        """Cleanup."""
        TestConfiguration.cleanup_temp_dir()
    
    def test_engine_initialization(self):
        """Test inicjalizacji silnika."""
        self.assertIsNotNone(self.engine)
        self.assertIsNotNone(self.engine.config)
        self.assertIsNotNone(self.engine.evaluator)
        self.assertIsNotNone(self.engine.fitness_calculator)
    
    def test_simple_feedback_cycle(self):
        """Test prostego cyklu feedback."""
        prediction_trace = {
            'trace_id': 'trace_001',
            'prediction': {
                'result': '1',
                'confidence': 0.8,
                'model_output': {'home_goals': 2, 'away_goals': 1}
            }
        }
        
        match_result = {
            'match_id': 'match_001',
            'home_goals': 2,
            'away_goals': 1,
            'result': '1'
        }
        
        context = self.engine.process_feedback_cycle(
            prediction_trace, match_result, 'test_strategy'
        )
        
        self.assertIsNotNone(context)
        self.assertEqual(context.status, "completed")
        self.assertIsNotNone(context.evaluation_result)
        self.assertIsNotNone(context.prediction_outcome)
        self.assertTrue(context.prediction_outcome.exact_score)
        self.assertEqual(self.engine.total_cycles, 1)
    
    def test_multiple_feedback_cycles(self):
        """Test wielu cykli feedback."""
        for i in range(5):
            prediction_trace = {
                'trace_id': f'trace_{i}',
                'prediction': {'result': '1'}
            }
            
            match_result = {
                'match_id': f'match_{i}',
                'home_goals': 2,
                'away_goals': 1,
                'result': '1'
            }
            
            self.engine.process_feedback_cycle(
                prediction_trace, match_result, 'multi_strategy'
            )
        
        self.assertEqual(self.engine.total_cycles, 5)
        self.assertEqual(self.engine.successful_cycles, 5)
        
        # Sprawdź fitness
        fitness = self.engine.get_strategy_fitness('multi_strategy')
        self.assertIsNotNone(fitness)
        self.assertEqual(fitness.total_predictions, 5)
        self.assertEqual(fitness.correct_predictions, 5)
    
    def test_mixed_results(self):
        """Test mieszanych wyników (poprawne i błędne)."""
        # 3 poprawne, 2 błędne
        for i in range(5):
            prediction_trace = {
                'trace_id': f'trace_{i}',
                'prediction': {'result': '1'}
            }
            
            if i < 3:
                match_result = {'match_id': f'match_{i}', 'home_goals': 2, 'away_goals': 1, 'result': '1'}
            else:
                match_result = {'match_id': f'match_{i}', 'home_goals': 0, 'away_goals': 2, 'result': '2'}
            
            self.engine.process_feedback_cycle(
                prediction_trace, match_result, 'mixed_strategy'
            )
        
        fitness = self.engine.get_strategy_fitness('mixed_strategy')
        self.assertIsNotNone(fitness)
        self.assertEqual(fitness.correct_predictions, 3)
        self.assertEqual(fitness.failed_predictions, 2)
        self.assertGreater(fitness.overall_fitness, 0)
        self.assertLess(fitness.overall_fitness, 1.0)
    
    def test_batch_processing(self):
        """Test przetwarzania batch."""
        traces = [
            {'trace_id': f'trace_{i}', 'prediction': {'result': '1'}}
            for i in range(3)
        ]
        
        results_list = [
            {'match_id': f'match_{i}', 'home_goals': 2, 'away_goals': 1, 'result': '1'}
            for i in range(3)
        ]
        
        contexts = self.engine.process_batch(
            traces, results_list, ['batch_strategy'] * 3
        )
        
        self.assertEqual(len(contexts), 3)
        self.assertTrue(all(c.status == "completed" for c in contexts))
        
        fitness = self.engine.get_strategy_fitness('batch_strategy')
        self.assertEqual(fitness.total_predictions, 3)
    
    def test_strategy_ranking(self):
        """Test rankingu strategii."""
        # Strategia A: 100% poprawnych
        for i in range(3):
            self.engine.process_feedback_cycle(
                {'trace_id': f'trace_A_{i}', 'prediction': {'result': '1'}},
                {'match_id': f'match_A_{i}', 'home_goals': 2, 'away_goals': 1, 'result': '1'},
                'strategy_A'
            )
        
        # Strategia B: 0% poprawnych
        for i in range(3):
            self.engine.process_feedback_cycle(
                {'trace_id': f'trace_B_{i}', 'prediction': {'result': '1'}},
                {'match_id': f'match_B_{i}', 'home_goals': 0, 'away_goals': 2, 'result': '2'},
                'strategy_B'
            )
        
        ranking = self.engine.get_ranking()
        
        self.assertEqual(len(ranking), 2)
        self.assertEqual(ranking[0][0], 'strategy_A')
        self.assertEqual(ranking[1][0], 'strategy_B')
    
    def test_get_top_strategy(self):
        """Test pobierania najlepszej strategii."""
        for i in range(3):
            self.engine.process_feedback_cycle(
                {'trace_id': f'trace_{i}', 'prediction': {'result': '1'}},
                {'match_id': f'match_{i}', 'home_goals': 2, 'away_goals': 1, 'result': '1'},
                'top_strategy'
            )
        
        top = self.engine.get_top_strategy()
        
        self.assertIsNotNone(top)
        self.assertEqual(top[0], 'top_strategy')
        self.assertEqual(top[1].overall_fitness, 1.0)
    
    def test_feedback_report(self):
        """Test generowania raportu feedback."""
        for i in range(3):
            self.engine.process_feedback_cycle(
                {'trace_id': f'trace_{i}', 'prediction': {'result': '1'}},
                {'match_id': f'match_{i}', 'home_goals': 2, 'away_goals': 1, 'result': '1'},
                'report_strategy'
            )
        
        report = self.engine.get_feedback_report()
        
        self.assertIsNotNone(report)
        self.assertIn('statistics', report)
        self.assertIn('ranking', report)
        self.assertIn('top_strategy', report)
        self.assertIn('events_summary', report)
    
    def test_engine_statistics(self):
        """Test statystyk silnika."""
        self.engine.process_feedback_cycle(
            {'trace_id': 'trace_1', 'prediction': {'result': '1'}},
            {'match_id': 'match_1', 'home_goals': 2, 'away_goals': 1, 'result': '1'},
            'stats_strategy'
        )
        
        stats = self.engine.get_statistics()
        
        self.assertIn('engine', stats)
        self.assertIn('evaluator', stats)
        self.assertIn('fitness_calculator', stats)
        self.assertEqual(stats['engine']['total_cycles'], 1)
    
    def test_engine_reset(self):
        """Test resetu silnika."""
        self.engine.process_feedback_cycle(
            {'trace_id': 'trace_1', 'prediction': {'result': '1'}},
            {'match_id': 'match_1', 'home_goals': 2, 'away_goals': 1, 'result': '1'},
            'reset_strategy'
        )
        
        self.assertGreater(self.engine.total_cycles, 0)
        
        self.engine.reset()
        
        self.assertEqual(self.engine.total_cycles, 0)
        self.assertEqual(len(self.engine.outcomes), 0)
        self.assertEqual(len(self.engine.fitness_values), 0)
    
    def test_invalid_input(self):
        """Test obsługi błędnych danych wejściowych."""
        # Brak match_result
        context = self.engine.process_feedback_cycle(
            {'trace_id': 'trace_1', 'prediction': {'result': '1'}},
            None,
            'error_strategy'
        )
        
        self.assertEqual(context.status, "failed")
        self.assertGreater(len(context.errors), 0)


# ============================================================================
# TESTY INTEGRACYJNE (4 testy)
# ============================================================================

class TestFeedbackIntegration(unittest.TestCase):
    """Testy integracyjne."""
    
    def setUp(self):
        """Setup."""
        TestConfiguration.setup_temp_dir()
    
    def tearDown(self):
        """Cleanup."""
        TestConfiguration.cleanup_temp_dir()
    
    def test_full_feedback_loop(self):
        """Test pełnej pętli feedback."""
        # Tworzymy engine
        config = FeedbackConfig(memory_dir=TestConfiguration.TEMP_DIR)
        engine = FeedbackEngine(config=config)
        
        # Symulujemy prediction trace z Prediction Trace Engine
        prediction_trace = {
            'trace_id': 'ptr_001',
            'prediction_id': 'pred_001',
            'strategy_id': 'integration_strategy',
            'context': {'world_version': 'v1.0', 'cycle_id': 'cycle_001'},
            'model': {'reference': 'test_model', 'version': '1.0'},
            'prediction': {
                'result': '1',
                'confidence': 0.85,
                'prediction_type': 'classification',
                'model_output': {'home_goals': 2, 'away_goals': 1}
            },
            'strategy_experiment_id': 'exp_001',
            'world_engine_cycle_id': 'world_cycle_001'
        }
        
        # Symulujemy result z Result Ingestion
        match_result = {
            'match_id': 'match_001',
            'home_team': 'Team A',
            'away_team': 'Team B',
            'home_goals': 2,
            'away_goals': 1,
            'result': '1',
            'source': 'test_csv.csv',
            'created_at': datetime.now().isoformat()
        }
        
        # Przetwarzamy
        context = engine.process_feedback_cycle(
            prediction_trace, match_result, 'integration_strategy'
        )
        
        # Weryfikujemy
        self.assertEqual(context.status, "completed")
        self.assertIsNotNone(context.evaluation_result)
        self.assertIsNotNone(context.prediction_outcome)
        self.assertIsNotNone(context.strategy_fitness)
        
        # Sprawdź fitness
        fitness = context.strategy_fitness
        self.assertEqual(fitness.strategy_id, 'integration_strategy')
        self.assertEqual(fitness.overall_fitness, 1.0)
    
    def test_memory_persistence(self):
        """Test persystencji pamięci."""
        config = FeedbackConfig(
            memory_dir=TestConfiguration.TEMP_DIR,
            enable_memory_persistence=True
        )
        engine = FeedbackEngine(config=config)
        
        # Przetwórz cykl
        engine.process_feedback_cycle(
            {'trace_id': 'trace_1', 'prediction': {'result': '1'}},
            {'match_id': 'match_1', 'home_goals': 2, 'away_goals': 1, 'result': '1'},
            'memory_strategy'
        )
        
        # Sprawdź plik pamięci
        memory_file = Path(TestConfiguration.TEMP_DIR) / "strategy_feedback_memory.json"
        self.assertTrue(memory_file.exists())
        
        # Wczytanie danych
        with open(memory_file, 'r') as f:
            data = json.load(f)
        
        self.assertIn('outcomes', data)
        self.assertIn('fitness_values', data)
    
    def test_external_integration_mock(self):
        """Test integracji z zewnętrznymi modułami (mock)."""
        engine = FeedbackEngine()
        
        # Mock Strategy Memory Manager
        class MockStrategyMemoryManager:
            def __init__(self):
                self.records = {}
            
            def get_strategy_memory(self, strategy_id):
                return self.records.get(strategy_id)
            
            def create_strategy_memory(self, strategy_id, strategy_version):
                from SSI_V5.memory.strategy_memory import StrategyMemoryRecord
                record = StrategyMemoryRecord(
                    strategy_id=strategy_id,
                    strategy_version=strategy_version
                )
                self.records[strategy_id] = record
                return record
            
            def _save_record(self, record):
                pass
        
        # Podłącz mock
        engine.connect_to_strategy_memory(MockStrategyMemoryManager())
        
        self.assertIsNotNone(engine._strategy_memory_manager)
    
    def test_pipeline_customization(self):
        """Test dostosowania pipeline."""
        # Custom pipeline
        engine = FeedbackEngine()
        
        # Początkowo pipeline ma kroki
        initial_steps = len(engine.pipeline.steps)
        self.assertGreater(initial_steps, 0)
        
        # Możemy dodać własne kroki
        engine.pipeline.add_step("custom_step", lambda ctx: True)
        
        # Powinien być nowy krok
        self.assertEqual(len(engine.pipeline.steps), initial_steps + 1)


# ============================================================================
# MAIN TEST RUNNER
# ============================================================================

def run_all_tests():
    """Uruchamia wszystkie testy."""
    print("\n" + "="*80)
    print("SSI V5 FEEDBACK MODULE - COMPREHENSIVE TESTS")
    print("="*80)
    
    # Lista testów
    test_classes = [
        TestFeedbackModels,
        TestPredictionEvaluator,
        TestFitnessCalculator,
        TestFeedbackEngine,
        TestFeedbackIntegration
    ]
    
    # Uruchom wszystkie testy
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    
    for test_class in test_classes:
        suite.addTests(loader.loadTestsFromTestCase(test_class))
    
    # Run tests
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    
    # Podsumowanie
    print("\n" + "="*80)
    print("PODSUMOWANIE TESTOW")
    print("="*80)
    print(f"Uruchomiono: {result.testsRun} testow")
    print(f"Zaliczono: {result.testsRun - len(result.failures) - len(result.errors)}")
    print(f"Bledy: {len(result.errors)}")
    print(f"Failury: {len(result.failures)}")
    print(f"Czas: {result.time:.4f}s")
    
    # Sprawdź minimum 40 testów
    if result.testsRun >= 40:
        print(f"\n✅ MINIMUM 40 TESTOW: {result.testsRun} > 40")
    else:
        print(f"\n❌ MINIMUM 40 TESTOW: {result.testsRun} < 40")
    
    # Sprawdź sukces
    if result.wasSuccessful():
        print("\n✅ WSZYSTKIE TESTY ZALICZONE!")
        return True
    else:
        print("\n❌ NIEKTORY TESTY NIE ZOSTALY ZALICZONE")
        return False


if __name__ == "__main__":
    success = run_all_tests()
    sys.exit(0 if success else 1)
