"""
SSI V5 Exact Score Engine - Confidence Engine
==============================================

ETAP: 5.2.9.x - Market Intelligence Layer - Confidence Engine

Odpowiedzialność:
- Obliczanie Confidence Score dla każdego dokładnego wyniku
- Analiza spójności WORLD (level_1, level_2, full_group)
- Ocena siły próbek (sample strength)
- Porównanie z Market Probability
- Porównanie z Poisson Dixon Coles
- Klasyfikacja poziomu pewności (HIGH, MEDIUM, LOW)

Cel:
Odpowiedzieć na pytanie: "Jak bardzo możemy ufać tej informacji?"
Tylko obliczanie confidence - ŻADNE generowanie strategii, kuponów czy typów.

Formuła:
confidence = world_consistency * 0.35 + sample_strength * 0.25 + 
            market_alignment * 0.20 + poisson_alignment * 0.20

Źródła danych:
1. WORLD ANALYSIS (level_1, level_2, full_group) - procenty i sample counts
2. Market Probability - z kursów bukmacherskich
3. Poisson Dixon Coles - z modelu statystycznego

Klasyfikacja:
- HIGH: 0.80 - 1.00
- MEDIUM: 0.60 - 0.79
- LOW: 0.00 - 0.59

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from enum import Enum
import logging
import math

from .models import (
    VALID_SCORES, 
    ScoreEvidence, 
    WorldLevelEvidence,
    ConfidenceLevel,
    create_score_evidence,
    create_world_level_evidence
)
from .score_space_generator import ScoreSpaceGenerator, ExactScoreSpace, ScoreLevelData
from .world_score_comparator import WorldScoreComparator, ScoreConsistency
from .odds_analyzer import MatchOdds, OddsAnalyzer
from .market_probability import MarketProbabilityConverter, MarketProbability

# Konfiguracja logowania
logger = logging.getLogger(__name__)


# =============================================================================
# ENUMS
# =============================================================================

class ConfidenceComponent(Enum):
    """Składowe Confidence Score"""
    WORLD_CONSISTENCY = "world_consistency"
    SAMPLE_STRENGTH = "sample_strength"
    MARKET_ALIGNMENT = "market_alignment"
    POISSON_ALIGNMENT = "poisson_alignment"


# =============================================================================
# DATA MODELS
# =============================================================================

@dataclass
class ConfidenceComponents:
    """
    Składowe Confidence Score dla jednego wyniku
    
    Zawiera cztery komponenty z ich wartościami (0-1):
    - world_consistency: Zgodność między poziomami WORLD
    - sample_strength: Siła/wiarygodność próbek
    - market_alignment: Zgodność z rynkiem bukmacherskim
    - poisson_alignment: Zgodność z modelem Poisson Dixon Coles
    """
    
    world_consistency: float = 0.0
    sample_strength: float = 0.0
    market_alignment: float = 0.0
    poisson_alignment: float = 0.0
    
    def __post_init__(self):
        """Walidacja - wszystkie wartości muszą być w zakresie 0-1"""
        for component_name in ['world_consistency', 'sample_strength', 'market_alignment', 'poisson_alignment']:
            value = getattr(self, component_name)
            if not isinstance(value, (int, float)):
                raise ValueError(f"{component_name} must be numeric, got {type(value)}")
            if value < 0.0 or value > 1.0:
                raise ValueError(f"{component_name} must be between 0-1, got {value}")
    
    def to_dict(self) -> Dict[str, float]:
        """Konwersja do dict"""
        return {
            "world_consistency": self.world_consistency,
            "sample_strength": self.sample_strength,
            "market_alignment": self.market_alignment,
            "poisson_alignment": self.poisson_alignment
        }
    
    def get_component(self, component: ConfidenceComponent) -> float:
        """Pobierz wartość_componentu"""
        component_mapping = {
            ConfidenceComponent.WORLD_CONSISTENCY: self.world_consistency,
            ConfidenceComponent.SAMPLE_STRENGTH: self.sample_strength,
            ConfidenceComponent.MARKET_ALIGNMENT: self.market_alignment,
            ConfidenceComponent.POISSON_ALIGNMENT: self.poisson_alignment
        }
        return component_mapping.get(component, 0.0)


@dataclass
class ConfidenceScore:
    """
    Finalny Confidence Score dla jednego wyniku
    
    Odpowiada na pytanie: "Jak bardzo możemy ufać tej informacji?"
    
    Atrybuty:
    - score: Wynik w formacie "X:Y"
    - confidence: Ogólny wynik pewności (0-1)
    - level: Poziom pewności (HIGH, MEDIUM, LOW)
    - components: Składowe (ConfidenceComponents)
    - explanation: Opis wyjaśniający wynik
    """
    
    score: str
    confidence: float
    level: ConfidenceLevel
    components: ConfidenceComponents
    explanation: str = ""
    
    def __post_init__(self):
        """Walidacja"""
        if self.score not in VALID_SCORES:
            raise ValueError(f"Score {self.score} not in VALID_SCORES")
        
        if not isinstance(self.confidence, (int, float)):
            raise ValueError(f"Confidence must be numeric, got {type(self.confidence)}")
        
        if self.confidence < 0.0 or self.confidence > 1.0:
            raise ValueError(f"Confidence must be between 0-1, got {self.confidence}")
        
        if not isinstance(self.level, ConfidenceLevel):
            raise ValueError(f"Level must be ConfidenceLevel enum, got {type(self.level)}")
        
        # Automatyczna klasyfikacja jeśli nie ustawiono level
        if self.level == ConfidenceLevel.LOW:  # Domyślny, sprawdź czy pasuje
            self.level = self._classify_level()
    
    def _classify_level(self) -> ConfidenceLevel:
        """Klasyfikuj poziom pewności na podstawie confidence score"""
        if self.confidence >= 0.80:
            return ConfidenceLevel.HIGH
        elif self.confidence >= 0.60:
            return ConfidenceLevel.MEDIUM
        elif self.confidence >= 0.40:
            return ConfidenceLevel.MEDIUM  # Dolny MEDIUM
        else:
            return ConfidenceLevel.LOW
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "score": self.score,
            "confidence": self.confidence,
            "level": self.level.value,
            "components": self.components.to_dict(),
            "explanation": self.explanation
        }
    
    def generate_explanation(self) -> str:
        """Wygeneruj wyjaśnienie na podstawie komponentów"""
        explanations = []
        
        # World Consistency
        wc = self.components.world_consistency
        if wc >= 0.9:
            explanations.append("Wysoka zgodność między poziomami WORLD")
        elif wc >= 0.7:
            explanations.append("Średnia zgodność między poziomami WORLD")
        elif wc >= 0.5:
            explanations.append("Niska zgodność między poziomami WORLD")
        else:
            explanations.append("Brak zgodności między poziomami WORLD")
        
        # Sample Strength
        ss = self.components.sample_strength
        if ss >= 0.9:
            explanations.append("Bardzo duża i wiarygodna próbka")
        elif ss >= 0.7:
            explanations.append("Duża próbka")
        elif ss >= 0.5:
            explanations.append("Średnia próbka")
        else:
            explanations.append("Mała próbka - niska wiarygodność")
        
        # Market Alignment
        ma = self.components.market_alignment
        if ma >= 0.9:
            explanations.append("Pełna zgodność z rynkiem bukmacherskim")
        elif ma >= 0.7:
            explanations.append("Dobra zgodność z rynkiem bukmacherskim")
        elif ma >= 0.5:
            explanations.append("Średnia zgodność z rynkiem bukmacherskim")
        else:
            explanations.append("Słaba zgodność z rynkiem bukmacherskim")
        
        # Poisson Alignment
        pa = self.components.poisson_alignment
        if pa >= 0.9:
            explanations.append("Pełna zgodność z modelem Poisson Dixon Coles")
        elif pa >= 0.7:
            explanations.append("Dobra zgodność z modelem Poisson Dixon Coles")
        elif pa >= 0.5:
            explanations.append("Średnia zgodność z modelem Poisson Dixon Coles")
        else:
            explanations.append("Słaba zgodność z modelem Poisson Dixon Coles")
        
        self.explanation = "; ".join(explanations)
        return self.explanation


@dataclass
class ConfidenceResult:
    """
    Wynik obliczeń Confidence Score dla jednego meczu
    
    Zawiera ConfidenceScore dla wszystkich VALID_SCORES
    """
    
    match_id: str
    confidence_scores: Dict[str, ConfidenceScore] = field(default_factory=dict)
    
    # Statystyki ogólne
    average_confidence: float = 0.0
    highest_confidence_scores: List[str] = field(default_factory=list)
    lowest_confidence_scores: List[str] = field(default_factory=list)
    
    def __post_init__(self):
        """Obliczenia statystyk"""
        if self.confidence_scores:
            self._calculate_statistics()
    
    def _calculate_statistics(self):
        """Oblicz statystyki"""
        if not self.confidence_scores:
            return
        
        # Średnia confidence
        total = sum(cs.confidence for cs in self.confidence_scores.values())
        self.average_confidence = total / len(self.confidence_scores)
        
        # Sortuj po confidence
        sorted_scores = sorted(
            self.confidence_scores.items(),
            key=lambda x: x[1].confidence,
            reverse=True
        )
        
        self.highest_confidence_scores = [item[0] for item in sorted_scores[:5]]
        self.lowest_confidence_scores = [item[0] for item in sorted_scores[-5:]]
    
    def get_score_confidence(self, score: str) -> Optional[ConfidenceScore]:
        """Pobierz ConfidenceScore dla danego wyniku"""
        return self.confidence_scores.get(score)
    
    def get_high_confidence_scores(self, min_confidence: float = 0.8) -> List[str]:
        """Pobierz listę wyników z wysokim confidence"""
        return [
            score for score, cs in self.confidence_scores.items()
            if cs.confidence >= min_confidence
        ]
    
    def get_scores_by_level(self, level: ConfidenceLevel) -> List[str]:
        """Pobierz listę wyników z danym poziomem pewności"""
        return [
            score for score, cs in self.confidence_scores.items()
            if cs.level == level
        ]
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "match_id": self.match_id,
            "confidence_scores": {
                score: cs.to_dict() for score, cs in self.confidence_scores.items()
            },
            "statistics": {
                "average_confidence": self.average_confidence,
                "highest_confidence_scores": self.highest_confidence_scores,
                "lowest_confidence_scores": self.lowest_confidence_scores,
                "high_count": len(self.get_high_confidence_scores(0.8)),
                "medium_count": len(self.get_scores_by_level(ConfidenceLevel.MEDIUM)),
                "low_count": len(self.get_scores_by_level(ConfidenceLevel.LOW))
            }
        }


# =============================================================================
# CONFIDENCE CALCULATOR
# =============================================================================

class ConfidenceCalculator:
    """
    Kalkulator Confidence Score
    
    Odpowiedzialność:
    - Obliczanie poszczególnych komponentów
    - Łączeniełów w finalny Confidence Score
    - Generowanie wyjaśnień
    """
    
    # Wagi komponentów (sumują się do 1.0)
    DEFAULT_WEIGHTS = {
        ConfidenceComponent.WORLD_CONSISTENCY: 0.35,
        ConfidenceComponent.SAMPLE_STRENGTH: 0.25,
        ConfidenceComponent.MARKET_ALIGNMENT: 0.20,
        ConfidenceComponent.POISSON_ALIGNMENT: 0.20
    }
    
    def __init__(self, weights: Optional[Dict[ConfidenceComponent, float]] = None):
        """
        Inicjalizacja kalkulatora
        
        Args:
            weights: Opcjonalne wagi Componentów (muszą sumować się do 1.0)
        """
        self.weights = weights or self.DEFAULT_WEIGHTS
        self._validate_weights()
        logger.info(f"[ConfidenceCalculator] Inicjalizacja z wagami: {self.weights}")
    
    def _validate_weights(self):
        """Walidacja wag"""
        total = sum(self.weights.values())
        if abs(total - 1.0) > 0.001:
            logger.warning(f"[ConfidenceCalculator] Wagi nie sumują się do 1.0: {total}")
            # Normalizacja
            for component in self.weights:
                self.weights[component] = self.weights[component] / total
    
    def calculate_world_consistency(
        self,
        level_1_percentage: Optional[float],
        level_2_percentage: Optional[float],
        full_group_percentage: Optional[float],
        level_1_samples: int = 0,
        level_2_samples: int = 0,
        full_group_samples: int = 0
    ) -> float:
        """
        Oblicz world_consistency (0-1)
        
        Zasady:
        - Wysoka zgodność: wszystkie poziomy zbliżone -> wysoki score
        - Niska zgodność: duże rozbieżności -> niski score
        - Brak danych: bardzo niski score
        
        Args:
            level_1_percentage: Procent z level_1
            level_2_percentage: Procent z level_2
            full_group_percentage: Procent z full_group
            level_1_samples: Liczba przypadków level_1
            level_2_samples: Liczba przypadków level_2
            full_group_samples: Liczba przypadków full_group
            
        Returns:
            world_consistency (0-1)
        """
        # Zebierz dostępne wartości
        percentages = []
        if level_1_percentage is not None:
            percentages.append((level_1_percentage, level_1_samples))
        if level_2_percentage is not None:
            percentages.append((level_2_percentage, level_2_samples))
        if full_group_percentage is not None:
            percentages.append((full_group_percentage, full_group_samples))
        
        if len(percentages) < 2:
            # Za mało danych do porównania
            return 0.3  # Niski, ale nie zero (jeszcze jakaś informacja)
        
        # Wyekstraktuj wartości procentowe i wagi (sample counts)
        values = [p[0] for p in percentages]
        weights = [p[1] for p in percentages]
        
        # Normalizacja wag
        total_weight = sum(weights)
        if total_weight == 0:
            normalized_weights = [1.0 / len(values)] * len(values)
        else:
            normalized_weights = [w / total_weight for w in weights]
        
        # Oblicz średnią ważoną
        weighted_mean = sum(v * w for v, w in zip(values, normalized_weights))
        
        # Oblicz odchylenie standardowe ważone
        variance = sum(
            normalized_weights[i] * (values[i] - weighted_mean) ** 2
            for i in range(len(values))
        )
        std_dev = math.sqrt(variance)
        
        # Im mniejsze odchylenie, tym wyższa zgodność
        # Max std_dev to np. 15% (przy cyklu 0-15%)
        # Normalizuj do 0-1
        max_expected_std = 15.0
        if std_dev >= max_expected_std:
            consistency = 0.0
        else:
            consistency = 1.0 - (std_dev / max_expected_std)
        
        # Minimalna wartość
        return max(consistency, 0.1)
    
    def calculate_sample_strength(
        self,
        level_1_samples: int = 0,
        level_2_samples: int = 0,
        full_group_samples: int = 0
    ) -> float:
        """
        Oblicz sample_strength (0-1)
        
        Zasady:
        - Im większa próbka, tym wyższa wiarygodność
        - Uwzględnia wzrost próbek na kolejnych poziomach
        
        Args:
            level_1_samples: Liczba przypadków level_1
            level_2_samples: Liczba przypadków level_2
            full_group_samples: Liczba przypadków full_group
            
        Returns:
            sample_strength (0-1)
        """
        samples = [level_1_samples, level_2_samples, full_group_samples]
        
        # Usunięcie zer
        valid_samples = [s for s in samples if s > 0]
        
        if not valid_samples:
            return 0.0
        
        # Największa próbka
        max_sample = max(valid_samples)
        
        # Skala: 0-5000 (przyjmujemy, że 5000 to maksymalna oczekiwana próbka)
        max_expected = 5000.0
        
        # Normalizacja logarytmiczna (lepsza dla dużych zakresów)
        # Używamy log, żeby nie karać zbytnio małych próbek
        if max_sample == 0:
            return 0.0
        
        # Wzór: min(1, log10(max_sample + 1) / log10(max_expected + 1))
        import math
        strength = math.log10(max_sample + 1) / math.log10(max_expected + 1)
        
        # Minimalna wartość
        return max(strength, 0.1)
    
    def calculate_market_alignment(
        self,
        world_probability: Optional[float],
        market_probability: Optional[float]
    ) -> float:
        """
        Oblicz market_alignment (0-1)
        
        Porównuje WORLD probability z Market probability
        
        Args:
            world_probability: Prawdopodobieństwo z WORLD (w %)  
            market_probability: Prawdopodobieństwo z rynku (w %)
            
        Returns:
            market_alignment (0-1)
        """
        if world_probability is None or market_probability is None:
            return 0.5  # Brak danych - neutralny
        
        # Różnica w punktach procentowych
        diff = abs(world_probability - market_probability)
        
        # Max difference to 20% (przy cyklu 0-20%)
        max_diff = 20.0
        
        if diff >= max_diff:
            alignment = 0.0
        else:
            alignment = 1.0 - (diff / max_diff)
        
        # Minimalna wartość
        return max(alignment, 0.2)
    
    def calculate_poisson_alignment(
        self,
        world_probability: Optional[float],
        poisson_probability: Optional[float]
    ) -> float:
        """
        Oblicz poisson_alignment (0-1)
        
        Porównuje WORLD probability z Poisson probability
        
        Args:
            world_probability: Prawdopodobieństwo z WORLD (w %)
            poisson_probability: Prawdopodobieństwo z modelu Poisson (w %)
            
        Returns:
            poisson_alignment (0-1)
        """
        if world_probability is None or poisson_probability is None:
            return 0.5  # Brak danych - neutralny
        
        # Różnica w punktach procentowych
        diff = abs(world_probability - poisson_probability)
        
        # Max difference to 20%
        max_diff = 20.0
        
        if diff >= max_diff:
            alignment = 0.0
        else:
            alignment = 1.0 - (diff / max_diff)
        
        # Minimalna wartość
        return max(alignment, 0.2)
    
    def calculate_confidence_score(
        self,
        world_consistency: float,
        sample_strength: float,
        market_alignment: float,
        poisson_alignment: float
    ) -> float:
        """
        Oblicz finalny Confidence Score z komponentów
        
        Args:
            world_consistency: Zgodność WORLD (0-1)
            sample_strength: Siła próbek (0-1)
            market_alignment: Zgodność z rynkiem (0-1)
            poisson_alignment: Zgodność z Poisson (0-1)
            
        Returns:
            Confidence Score (0-1)
        """
        # Walidacja
        for value in [world_consistency, sample_strength, market_alignment, poisson_alignment]:
            if value < 0.0 or value > 1.0:
                raise ValueError(f"Komponent must be 0-1, got {value}")
        
        # Oblicz punktację
        components = {
            ConfidenceComponent.WORLD_CONSISTENCY: world_consistency,
            ConfidenceComponent.SAMPLE_STRENGTH: sample_strength,
            ConfidenceComponent.MARKET_ALIGNMENT: market_alignment,
            ConfidenceComponent.POISSON_ALIGNMENT: poisson_alignment
        }
        
        score = sum(
            self.weights.get(component, 0.0) * components[component]
            for component in ConfidenceComponent
        )
        
        # Upewnij się, że wynik jest w zakresie 0-1
        return max(0.0, min(1.0, score))
    
    def classify_confidence_level(self, confidence: float) -> ConfidenceLevel:
        """
        Klasyfikuj poziom pewności
        
        Args:
            confidence: Confidence Score (0-1)
            
        Returns:
            ConfidenceLevel
        """
        if confidence >= 0.80:
            return ConfidenceLevel.HIGH
        elif confidence >= 0.60:
            return ConfidenceLevel.MEDIUM
        else:
            return ConfidenceLevel.LOW


# =============================================================================
# CONFIDENCE ENGINE
# =============================================================================

class ConfidenceEngine:
    """
    Główny moduł Confidence Engine
    
    Odpowiedzialność:
    - Integracja wszystkich źródeł danych
    - Obliczanie Confidence Score dla każdego wyniku
    - Generowanie ConfidenceResult
    """
    
    def __init__(
        self,
        score_space_generator: Optional[ScoreSpaceGenerator] = None,
        odds_analyzer: Optional[OddsAnalyzer] = None,
        calculator: Optional[ConfidenceCalculator] = None
    ):
        """
        Inicjalizacja Confidence Engine
        
        Args:
            score_space_generator: Generator przestrzeni wyników
            odds_analyzer: Analizator kursów bukmacherskich
            calculator: Kalkulator Confidence Score
        """
        self.score_space_generator = score_space_generator or ScoreSpaceGenerator()
        self.odds_analyzer = odds_analyzer or OddsAnalyzer()
        self.calculator = calculator or ConfidenceCalculator()
        
        # Cache
        self._confidence_cache: Dict[str, ConfidenceResult] = {}
        
        logger.info("[ConfidenceEngine] Inicjalizacja")
    
    def _extract_world_data(
        self,
        score_space: ExactScoreSpace,
        score: str
    ) -> Tuple[Optional[float], Optional[float], Optional[float], int, int, int]:
        """
        Wyekstraktuj dane WORLD dla danego wyniku
        
        Returns:
            (level_1_pct, level_2_pct, full_pct, l1_samples, l2_samples, full_samples)
        """
        level_1_pct = score_space.level_1.get_score_percentage(score) if score_space.level_1 else None
        level_2_pct = score_space.level_2.get_score_percentage(score) if score_space.level_2 else None
        full_pct = score_space.full_group.get_score_percentage(score) if score_space.full_group else None
        
        l1_samples = score_space.level_1.sample_count if score_space.level_1 else 0
        l2_samples = score_space.level_2.sample_count if score_space.level_2 else 0
        full_samples = score_space.full_group.sample_count if score_space.full_group else 0
        
        return level_1_pct, level_2_pct, full_pct, l1_samples, l2_samples, full_samples
    
    def _extract_market_data(
        self,
        match_id: str,
        score: str
    ) -> Optional[float]:
        """
        Wyekstraktuj dane Market Probability dla danego wyniku
        
        UWAGA: Tutaj potrzebna jest poblina z Market Probability do Exact Score
        Na razie zwracamy średnią klase ryku 1/X/2 jako szacunek
        W przyszłości należy zintegrować z dokładnymi kursami na konkretne wyniki
        """
        # Pobierz kursy dla meczu
        match_odds = self.odds_analyzer.get_odds(match_id)
        if not match_odds:
            return None
        
        # Konwersja kursów na prawdopodobieństwa (1/X/2)
        converter = MarketProbabilityConverter()
        market_prob = converter.convert_odds_to_probabilities(
            match_odds.home_win_odds,
            match_odds.draw_odds,
            match_odds.away_win_odds,
            match_id
        )
        
        # Mapowanie wyniku na prawdopodobieństwo 1/X/2
        # To jest uproszczenie - w rzeczywistości potatoesz dokładne kursy na wyniki
        score_mapping = {
            "1:0": market_prob.home_win_normalized * 0.4,  # 40% szans na 1:0 z wygranej gospodarzy
            "2:0": market_prob.home_win_normalized * 0.3,
            "3:0": market_prob.home_win_normalized * 0.2,
            "0:1": market_prob.away_win_normalized * 0.4,
            "0:2": market_prob.away_win_normalized * 0.3,
            "0:3": market_prob.away_win_normalized * 0.2,
            "2:1": market_prob.home_win_normalized * 0.25,
            "3:1": market_prob.home_win_normalized * 0.15,
            "3:2": market_prob.home_win_normalized * 0.10,
            "1:2": market_prob.away_win_normalized * 0.25,
            "1:3": market_prob.away_win_normalized * 0.15,
            "2:3": market_prob.away_win_normalized * 0.10,
            "0:0": market_prob.draw_normalized * 0.3,
            "1:1": market_prob.draw_normalized * 0.5,
            "2:2": market_prob.draw_normalized * 0.2
        }
        
        return score_mapping.get(score)
    
    def _extract_poisson_data(
        self,
        score: str,
        match_id: Optional[str] = None
    ) -> Optional[float]:
        """
        Wyekstraktuj dane Poisson Dixon Coles
        
        UWAGA: To jest placeholder. W rzeczywistej integracji należy użyć 
        modelu Poisson Dixon Coles z étap 5.2.9.x
        
        Na razie zwracamy przykładowe wartości dla popularnych wyników
        """
        # Przykładowe wartości Poisson Dixon Coles (na bazie typowych statystyk)
        poisson_examples = {
            "0:0": 8.5, "1:0": 12.5, "2:0": 8.0, "3:0": 4.5,
            "0:1": 12.5, "0:2": 8.0, "0:3": 4.5,
            "1:1": 13.0, "2:1": 9.0, "3:1": 5.0,
            "1:2": 9.0, "2:2": 7.0, "3:2": 4.0,
            "1:3": 5.0, "2:3": 3.0
        }
        
        # Zwróć wartość z przykładu
        return poisson_examples.get(score)
    
    def calculate_score_confidence(
        self,
        score: str,
        world_data: Optional[Dict[str, Any]] = None,
        market_data: Optional[Dict[str, Any]] = None,
        poisson_data: Optional[Dict[str, Any]] = None,
        match_id: Optional[str] = None
    ) -> ConfidenceScore:
        """
        Oblicz Confidence Score dla pojedynczego wyniku
        
        Główna funkcja modułu Confidence Engine.
        
        Args:
            score: Wynik w formacie "X:Y"
            world_data: Opcjonalne dane WORLD (dict z level_1, level_2, full_group)
            market_data: Opcjonalne dane Market (dict z probability)
            poisson_data: Opcjonalne dane Poisson (dict z probability)
            match_id: Opcjonalny identyfikator meczu
            
        Returns:
            ConfidenceScore
            
        Example:
            Input: score="1:1", match_id="Inhulets Petrove - Polissya II"
            Output: ConfidenceScore(score="1:1", confidence=0.87, level=HIGH, ...)
        """
        if score not in VALID_SCORES:
            raise ValueError(f"Invalid score: {score}. Must be in VALID_SCORES")
        
        # 1. world_data
        if world_data:
            level_1_pct = world_data.get("level_1", {}).get("percentage")
            level_2_pct = world_data.get("level_2", {}).get("percentage")
            full_pct = world_data.get("full_group", {}).get("percentage")
            l1_samples = world_data.get("level_1", {}).get("sample_count", 0)
            l2_samples = world_data.get("level_2", {}).get("sample_count", 0)
            full_samples = world_data.get("full_group", {}).get("sample_count", 0)
        else:
            # Pobierz z ScoreSpaceGenerator
            if match_id:
                score_space = self.score_space_generator.generate_score_space(match_id)
                if score_space:
                    level_1_pct, level_2_pct, full_pct, l1_samples, l2_samples, full_samples = \
                        self._extract_world_data(score_space, score)
                else:
                    level_1_pct, level_2_pct, full_pct = None, None, None
                    l1_samples, l2_samples, full_samples = 0, 0, 0
            else:
                level_1_pct, level_2_pct, full_pct = None, None, None
                l1_samples, l2_samples, full_samples = 0, 0, 0
        
        # 2. Market data
        if market_data:
            market_prob = market_data.get("probability")
        else:
            market_prob = self._extract_market_data(match_id or "", score)
        
        # 3. Poisson data
        if poisson_data:
            poisson_prob = poisson_data.get("probability")
        else:
            poisson_prob = self._extract_poisson_data(score, match_id)
        
        # Oblicz średnią WORLD (dla porównania z market i poisson)
        world_percentages = [p for p in [level_1_pct, level_2_pct, full_pct] if p is not None]
        world_avg = sum(world_percentages) / len(world_percentages) if world_percentages else None
        
        # Oblicz komponenty
        world_consistency = self.calculator.calculate_world_consistency(
            level_1_pct, level_2_pct, full_pct,
            l1_samples, l2_samples, full_samples
        )
        
        sample_strength = self.calculator.calculate_sample_strength(
            l1_samples, l2_samples, full_samples
        )
        
        market_alignment = self.calculator.calculate_market_alignment(
            world_avg, market_prob
        )
        
        poisson_alignment = self.calculator.calculate_poisson_alignment(
            world_avg, poisson_prob
        )
        
        # Oblicz finalny score
        confidence = self.calculator.calculate_confidence_score(
            world_consistency, sample_strength, market_alignment, poisson_alignment
        )
        
        # Klasyfikacja
        level = self.calculator.classify_confidence_level(confidence)
        
        # Tworzenie obiektu
        components = ConfidenceComponents(
            world_consistency=world_consistency,
            sample_strength=sample_strength,
            market_alignment=market_alignment,
            poisson_alignment=poisson_alignment
        )
        
        confidence_score = ConfidenceScore(
            score=score,
            confidence=confidence,
            level=level,
            components=components
        )
        
        # Generowanie wyjaśnienia
        confidence_score.generate_explanation()
        
        return confidence_score
    
    def calculate_score_confidence_batch(
        self,
        match_id: str,
        scores: Optional[List[str]] = None
    ) -> ConfidenceResult:
        """
        Oblicz Confidence Score dla wszystkich wyników danego meczu
        
        Args:
            match_id: Identyfikator meczui
            scores: Opcjonalna lista wyników do obliczenia (domyślnie VALID_SCORES)
            
        Returns:
            ConfidenceResult
        """
        if match_id in self._confidence_cache:
            return self._confidence_cache[match_id]
        
        target_scores = scores or VALID_SCORES
        
        confidence_scores = {}
        for score in target_scores:
            try:
                confidence_score = self.calculate_score_confidence(
                    score, match_id=match_id
                )
                confidence_scores[score] = confidence_score
            except Exception as e:
                logger.error(f"[ConfidenceEngine] Błąd obliczania confidence dla {score}: {e}")
                # Stwórz pusty score z LOW confidence
                confidence_scores[score] = ConfidenceScore(
                    score=score,
                    confidence=0.0,
                    level=ConfidenceLevel.LOW,
                    components=ConfidenceComponents()
                )
        
        result = ConfidenceResult(
            match_id=match_id,
            confidence_scores=confidence_scores
        )
        
        # Cache
        self._confidence_cache[match_id] = result
        
        return result
    
    def calculate_confidence_batch(
        self,
        match_ids: List[str]
    ) -> Dict[str, ConfidenceResult]:
        """
        Oblicz Confidence Score dla wielu meczów
        
        Args:
            match_ids: Lista identyfikatorów meczów
            
        Returns:
            Dict[match_id, ConfidenceResult]
        """
        results = {}
        for match_id in match_ids:
            try:
                result = self.calculate_score_confidence_batch(match_id)
                results[match_id] = result
            except Exception as e:
                logger.error(f"[ConfidenceEngine] Błąd obliczania confidence batch dla {match_id}: {e}")
                results[match_id] = ConfidenceResult(
                    match_id=match_id,
                    confidence_scores={}
                )
        
        return results
    
    def get_highest_confidence_scores(
        self,
        match_id: str,
        limit: int = 5
    ) -> List[Tuple[str, ConfidenceScore]]:
        """
        Pobierz N wyników z najwyższym confidence
        
        Args:
            match_id: Identyfikator meczu
            limit: Liczba wyników do zwrócenia
            
        Returns:
            Lista (score, ConfidenceScore) posortowana po confidence (malejąco)
        """
        result = self.calculate_score_confidence_batch(match_id)
        sorted_scores = sorted(
            result.confidence_scores.items(),
            key=lambda x: x[1].confidence,
            reverse=True
        )
        return sorted_scores[:limit]
    
    def get_confidence_summary(
        self,
        match_id: str
    ) -> Dict[str, Any]:
        """
        Pobierz podsumowanie Confidence Score dla meczu
        
        Args:
            match_id: Identyfikator meczu
            
        Returns:
            Dict z podsumowaniem
        """
        result = self.calculate_score_confidence_batch(match_id)
        return result.to_dict()
    
    def clear_cache(self):
        """Wyczyść cache"""
        self._confidence_cache.clear()
        logger.info("[ConfidenceEngine] Cache wyczyszczony")


# =============================================================================
# HELPER FUNCTIONS
# =============================================================================

def calculate_score_confidence(
    score: str,
    world_data: Optional[Dict[str, Any]] = None,
    market_data: Optional[Dict[str, Any]] = None,
    poisson_data: Optional[Dict[str, Any]] = None
) -> Dict[str, Any]:
    """
    Funkcja wygodna do obliczania Confidence Score
    
    Przykład użycia:
        calculate_score_confidence(
            score="1:1",
            world_data={
                "level_1": {"percentage": 12.73, "sample_count": 3448},
                "level_2": {"percentage": 13.13, "sample_count": 853},
                "full_group": {"percentage": 14.39, "sample_count": 264}
            },
            market_data={"probability": 13.5},
            poisson_data={"probability": 13.02}
        )
    
    Returns:
        Dict z wynikiem
    """
    engine = ConfidenceEngine()
    confidence_score = engine.calculate_score_confidence(
        score, world_data, market_data, poisson_data
    )
    
    return {
        "score": confidence_score.score,
        "confidence": confidence_score.confidence,
        "level": confidence_score.level.value,
        "components": confidence_score.components.to_dict(),
        "explanation": confidence_score.explanation
    }


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    # Enums
    'ConfidenceComponent',
    
    # Models
    'ConfidenceScore',
    'ConfidenceComponents', 
    'ConfidenceResult',
    
    # Calculators
    'ConfidenceCalculator',
    
    # Engine
    'ConfidenceEngine',
    
    # Functions
    'calculate_score_confidence',
]

print(f"[CONFIDENCE_ENGINE] Moduł załadowany - ETAP 5.2.9.x")
