"""
SSI V5 Exact Score Engine - Exact Score Ranker
==============================================

ETAP: 5.2.9.x - Market Intelligence Layer - Exact Score Ranker

Odpowiedzialnosc:
- Tworzenie rankingów dokładnych wyników (Exact Scores)
- Ranking pojedynczych wyników na podstawie wielokryterialnej analizy
- Ranking grup wyników strategicznych
- Ranking scenariuszy meczowych
- Generowanie ExactScoreRanking dla Strategy Laboratory
- PRZYGOTOWANIE DANYCH DLA Exact Score Market Builder

ZASADY:
- TYLKO analiza i ranking wiedzy
- NIE generuje kuponów, obstawiania, strategii
- NIE modyfikuje Feedback Engine, Strategy Evolution, Prediction Trace
- NIE modyfikuje istniejących agentów
- Output: ExactScoreRanking z danymi rynkowymi dla Market Builder

ARCHITEKTURA:
ExactScoreRanker -> ExactScoreMarketBuilder -> Strategy Laboratory

Formuła rankingowa:
ranking_score = (combined_probability * 0.4) + (confidence * 0.3) + (group_confidence * 0.2) + (value_score * 0.1)

DANE DLA EXACT SCORE MARKET BUILDER:
Każdy pojedynczy wynik (1:0, 2:0, 1:1 itd.) otrzymuje:
- combined_probability: Łączne prawdopodobieństwo z WORLD + MARKET + POISSON
- fair_odds: Kurs sprawiedliwy (1 / combined_probability)
- market_value: Wartość rynkowa (combined_probability * confidence)
- risk_reward_ratio: Stosunek ryzyko-nagroda

Każda grupa wyników otrzymuje:
- total_probability: Suma prawdopodobieństw wszystkich wyników w grupie
- group_fair_odds: Kurs sprawiedliwy dla grupy (1 / total_probability)
- group_market_value: Wartość rynkowa grupy

Źródła danych:
1. Market Probability - z kursów bukmacherskich
2. WORLD Probability - z WORLD DATABASE (level_1, level_2, full_group)
3. Poisson Dixon Coles - z modelu statystycznego
4. Confidence Score - z Confidence Engine
5. Group Confidence - z Score Group Builder

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from enum import Enum
import logging
import math
from datetime import datetime

from .models import (
    VALID_SCORES,
    ExactScoreCandidate,
    ExactScoreKnowledge,
    ScoreGroupType,
    ConfidenceLevel
)
from .confidence_engine import ConfidenceScore, ConfidenceEngine
from .score_group_builder import ScoreGroupBuilder, ScoreGroupCollection, GroupScore, GROUP_DEFINITIONS, ScoreGroup

# Konfiguracja logowania
logger = logging.getLogger(__name__)


# =============================================================================
# ENUMS
# =============================================================================

class RankingType(Enum):
    """Typy rankingów"""
    INDIVIDUAL_SCORES = "individual_scores"      # Pojedyncze wyniki
    SCENARIO_GROUPS = "scenario_groups"         # Grupy strategiczne
    MATCH_SCENARIOS = "match_scenarios"          # Scenariusze meczowe


class ScenarioType(Enum):
    """Typy scenariuszy meczowych"""
    HOME_VICTORY = "home_victory"            # Zwycięstwo gospodarzy
    AWAY_VICTORY = "away_victory"            # Zwycięstwo gości
    DRAW = "draw"                            # Remis
    HIGH_SCORING = "high_scoring"          # Wysoki wynik (3+ gole)
    LOW_SCORING = "low_scoring"            # Niski wynik (0-1 gole)
    BALANCED = "balanced"                   # Zrównoważony mecz
    OFFENSIVE = "offensive"                # Ofensywny mecz
    DEFENSIVE = "defensive"                # Defensywny mecz


# =============================================================================
# MODELE DANYCH
# =============================================================================

@dataclass
class ScoreRankingData:
    """
    Dane rankingowe dla pojedynczego wyniku
    
    Zawiera wszystkie metryki używane do obliczenia rankingu
    + dane dla Exact Score Market Builder (fair_odds, market_value itp.)
    """
    score: str  # Wynik w formacie "X:Y"
    
    # Prawdopodobieństwa z różnych źródeł (0-100%)
    world_probability: float = 0.0
    market_probability: float = 0.0
    poisson_probability: float = 0.0
    combined_probability: float = 0.0
    
    # Pewność i confidence
    confidence_score: float = 0.0  # 0-1
    confidence_level: ConfidenceLevel = ConfidenceLevel.LOW
    
    # Group confidence (jeśli należy do grupy)
    group_confidence: float = 0.0
    group_type: Optional[Any] = None  # ScoreGroupType z score_group_builder
    
    # Dodatkowe metryki
    sample_strength: float = 0.0  # Siła próbek (0-1)
    market_alignment: float = 0.0  # Zgodność z rynkiem (0-1)
    poisson_alignment: float = 0.0  # Zgodność z Poisson (0-1)
    
    # Wartość kursowa
    value_score: float = 0.0
    
    # Ryzyko
    risk_score: float = 0.0
    
    # Finalny ranking score (do sortowania)
    ranking_score: float = 0.0
    
    # Pozycja w rankingu
    rank: int = 0
    
    # DANE DLA EXACT SCORE MARKET BUILDER
    # Fair odds (1 / probability) - kurs sprawiedliwy
    fair_odds: float = 0.0
    
    # Market value - wartość rynkowa (prawdopodobieństwo * confidence)
    market_value: float = 0.0
    
    # Risk-reward ratio (value_score / risk_score)
    risk_reward_ratio: float = 0.0
    
    def __post_init__(self):
        """Walidacja danych"""
        if self.score not in VALID_SCORES:
            raise ValueError(f"Score {self.score} not in VALID_SCORES")
        
        for attr in ['world_probability', 'market_probability', 'poisson_probability', 
                     'combined_probability', 'confidence_score', 'group_confidence',
                     'sample_strength', 'market_alignment', 'poisson_alignment',
                     'value_score', 'risk_score', 'ranking_score', 'fair_odds',
                     'market_value', 'risk_reward_ratio']:
            value = getattr(self, attr)
            if not isinstance(value, (int, float)):
                raise ValueError(f"{attr} must be numeric, got {type(value)}")
    
    def to_dict(self) -> Dict[str, Any]:
        """Serializacja do dict"""
        return {
            "score": self.score,
            "probabilities": {
                "world": self.world_probability,
                "market": self.market_probability,
                "poisson": self.poisson_probability,
                "combined": self.combined_probability
            },
            "confidence": {
                "score": self.confidence_score,
                "level": self.confidence_level.value,
                "sample_strength": self.sample_strength,
                "market_alignment": self.market_alignment,
                "poisson_alignment": self.poisson_alignment
            },
            "group": {
                "confidence": self.group_confidence,
                "type": self.group_type.value if self.group_type else None
            },
            "value_score": self.value_score,
            "risk_score": self.risk_score,
            "ranking_score": self.ranking_score,
            "rank": self.rank,
            # DANE DLA EXACT SCORE MARKET BUILDER
            "market_data": {
                "fair_odds": self.fair_odds,
                "market_value": self.market_value,
                "risk_reward_ratio": self.risk_reward_ratio
            }
        }


@dataclass
class GroupRankingData:
    """
    Dane rankingowe dla grupy wyników
    """
    group_type: Any  # ScoreGroupType z score_group_builder
    name: str
    description: str
    
    # Statystyki grupy
    average_confidence: float = 0.0
    group_confidence: float = 0.0
    total_sample_count: int = 0
    
    # Prawdopodobieństwa
    average_probability: float = 0.0
    total_probability: float = 0.0  # Suma prawdopodobieństw wszystkich wyników w grupie
    
    # DANE DLA EXACT SCORE MARKET BUILDER
    # Fair odds dla grupy (1 / total_probability_normalized)
    group_fair_odds: float = 0.0
    
    # Wartość rynkowa grupy
    group_market_value: float = 0.0
    
    # Ranking score
    ranking_score: float = 0.0
    
    # Pozycja w rankingu
    rank: int = 0
    
    # Wyniki należące do grupy
    scores: List[str] = field(default_factory=list)
    
    def __post_init__(self):
        """Walidacja"""
        for attr in ['group_confidence', 'ranking_score', 'average_probability', 
                     'total_probability', 'group_fair_odds', 'group_market_value']:
            value = getattr(self, attr)
            if not isinstance(value, (int, float)):
                raise ValueError(f"{attr} must be numeric, got {type(value)}")
    
    def to_dict(self) -> Dict[str, Any]:
        """Serializacja do dict"""
        return {
            "group_type": self.group_type.value,
            "name": self.name,
            "description": self.description,
            "statistics": {
                "average_confidence": self.average_confidence,
                "group_confidence": self.group_confidence,
                "total_sample_count": self.total_sample_count,
                "average_probability": self.average_probability,
                "total_probability": self.total_probability
            },
            "market_data": {
                "group_fair_odds": self.group_fair_odds,
                "group_market_value": self.group_market_value
            },
            "ranking_score": self.ranking_score,
            "rank": self.rank,
            "scores": self.scores
        }


@dataclass
class ScenarioRankingData:
    """
    Dane rankingowe dla scenariusza meczowego
    """
    scenario_type: ScenarioType
    name: str
    description: str
    
    # Prawdopodobieństwo scenariusza
    probability: float = 0.0
    
    # Pewność scenariusza
    confidence: float = 0.0
    confidence_level: ConfidenceLevel = ConfidenceLevel.LOW
    
    # Ranking score
    ranking_score: float = 0.0
    
    # Pozycja w rankingu
    rank: int = 0
    
    # Powiązane wyniki
    related_scores: List[str] = field(default_factory=list)
    
    # Grupy powiązane
    related_groups: List[ScoreGroupType] = field(default_factory=list)
    
    def __post_init__(self):
        """Walidacja"""
        for attr in ['probability', 'confidence', 'ranking_score']:
            value = getattr(self, attr)
            if not isinstance(value, (int, float)):
                raise ValueError(f"{attr} must be numeric, got {type(value)}")
    
    def to_dict(self) -> Dict[str, Any]:
        """Serializacja do dict"""
        return {
            "scenario_type": self.scenario_type.value,
            "name": self.name,
            "description": self.description,
            "probability": self.probability,
            "confidence": self.confidence,
            "confidence_level": self.confidence_level.value,
            "ranking_score": self.ranking_score,
            "rank": self.rank,
            "related_scores": self.related_scores,
            "related_groups": [g.value for g in self.related_groups]
        }


@dataclass
class ExactScoreRanking:
    """
    Finalny obiekt rankingowy dla Strategy Laboratory
    
    Zawiera:
    - Ranking pojedynczych wyników
    - Ranking grup strategicznych
    - Ranking scenariuszy meczowych
    - Metadane i statystyki
    """
    
    # Identyfikator meczu
    match_id: str
    match_name: str
    
    # Czas generowania
    generated_at: str = ""
    
    # Ranking pojedynczych wyników (posortowany po rankingu)
    individual_scores: List[ScoreRankingData] = field(default_factory=list)
    
    # Ranking grup strategicznych (posortowany po rankingu)
    scenario_groups: List[GroupRankingData] = field(default_factory=list)
    
    # Ranking scenariuszy meczowych (posortowany po rankingu)
    match_scenarios: List[ScenarioRankingData] = field(default_factory=list)
    
    # Statystyki
    statistics: Dict[str, Any] = field(default_factory=dict)
    
    # Metadane
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Inicjalizacja i sortowanie"""
        if not self.generated_at:
            self.generated_at = datetime.now().isoformat()
        
        # Sortuj rankingi po ranking_score (malejąco)
        self.individual_scores.sort(key=lambda x: x.ranking_score, reverse=True)
        self.scenario_groups.sort(key=lambda x: x.ranking_score, reverse=True)
        self.match_scenarios.sort(key=lambda x: x.ranking_score, reverse=True)
        
        # Uaktualnij pozycje rankingowe
        self._update_ranks()
        
        # Oblicz statystyki
        self._calculate_statistics()
    
    def _update_ranks(self):
        """Uaktualnij pozycje w rankingu"""
        for i, score_data in enumerate(self.individual_scores, 1):
            score_data.rank = i
        
        for i, group_data in enumerate(self.scenario_groups, 1):
            group_data.rank = i
            
        for i, scenario_data in enumerate(self.match_scenarios, 1):
            scenario_data.rank = i
    
    def _calculate_statistics(self):
        """Oblicz statystyki"""
        # Statystyki dla pojedynczych wyników
        if self.individual_scores:
            total_score = sum(s.ranking_score for s in self.individual_scores)
            avg_score = total_score / len(self.individual_scores)
            
            high_confidence = len([s for s in self.individual_scores if s.confidence_score >= 0.8])
            medium_confidence = len([s for s in self.individual_scores if 0.6 <= s.confidence_score < 0.8])
            low_confidence = len([s for s in self.individual_scores if s.confidence_score < 0.6])
            
            self.statistics['individual_scores'] = {
                'count': len(self.individual_scores),
                'average_ranking_score': avg_score,
                'high_confidence': high_confidence,
                'medium_confidence': medium_confidence,
                'low_confidence': low_confidence
            }
        
        # Statystyki dla grup
        if self.scenario_groups:
            total_group_score = sum(g.ranking_score for g in self.scenario_groups)
            avg_group_score = total_group_score / len(self.scenario_groups)
            
            self.statistics['scenario_groups'] = {
                'count': len(self.scenario_groups),
                'average_ranking_score': avg_group_score
            }
        
        # Statystyki dla scenariuszy
        if self.match_scenarios:
            total_scenario_score = sum(s.ranking_score for s in self.match_scenarios)
            avg_scenario_score = total_scenario_score / len(self.match_scenarios)
            
            self.statistics['match_scenarios'] = {
                'count': len(self.match_scenarios),
                'average_ranking_score': avg_scenario_score
            }
    
    def to_dict(self) -> Dict[str, Any]:
        """Serializacja do dict"""
        return {
            "match_id": self.match_id,
            "match_name": self.match_name,
            "generated_at": self.generated_at,
            "rankings": {
                "individual_scores": [s.to_dict() for s in self.individual_scores],
                "scenario_groups": [g.to_dict() for g in self.scenario_groups],
                "match_scenarios": [s.to_dict() for s in self.match_scenarios]
            },
            "statistics": self.statistics,
            "metadata": self.metadata
        }
    
    def to_json(self, indent: int = 2) -> str:
        """Serializacja do JSON"""
        import json
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)
    
    def get_top_individual_scores(self, n: int = 3) -> List[ScoreRankingData]:
        """Pobierz N najlepszych pojedynczych wyników"""
        return self.individual_scores[:n]
    
    def get_top_scenario_groups(self, n: int = 3) -> List[GroupRankingData]:
        """Pobierz N najlepszych grup"""
        return self.scenario_groups[:n]
    
    def get_top_match_scenarios(self, n: int = 3) -> List[ScenarioRankingData]:
        """Pobierz N najlepszych scenariuszy"""
        return self.match_scenarios[:n]
    
    def get_best_score(self) -> Optional[ScoreRankingData]:
        """Pobierz najlepszy pojedynczy wynik"""
        return self.individual_scores[0] if self.individual_scores else None
    
    def get_best_scenario(self) -> Optional[ScenarioRankingData]:
        """Pobierz najlepszy scenariusz"""
        return self.match_scenarios[0] if self.match_scenarios else None


# =============================================================================
# KONFIGURACJA RANKINGU
# =============================================================================

# Wagi dla obliczania ranking_score pojedynczego wyniku
INDIVIDUAL_RANKING_WEIGHTS = {
    "combined_probability": 0.40,   # Największa waga - prawdopodobieństwo
    "confidence_score": 0.30,        # Pewność
    "group_confidence": 0.20,        # Pewność grupy
    "value_score": 0.10              # Wartość kursowa
}

# Wagi dla obliczania ranking_score grupy
GROUP_RANKING_WEIGHTS = {
    "average_confidence": 0.40,      # Średnia pewność w grupie
    "group_confidence": 0.30,        # Pewność grupy
    "average_probability": 0.20,     # Średnie prawdopodobieństwo
    "sample_strength": 0.10          # Siła próbek
}

# Wagi dla obliczania ranking_score scenariusza
SCENARIO_RANKING_WEIGHTS = {
    "probability": 0.50,              # Prawdopodobieństwo scenariusza
    "confidence": 0.30,               # Pewność scenariusza
    "group_support": 0.20            # Wsparcie od grup
}


# =============================================================================
# EXACT SCORE RANKER
# =============================================================================

class ExactScoreRanker:
    """
    Główny moduł Exact Score Ranker
    
    Odpowiedzialność:
    - Tworzenie rankingów na podstawie wielokryterialnej analizy
    - Integracja danych z Market, WORLD, Poisson i Confidence Engine
    - Generowanie ExactScoreRanking dla Strategy Laboratory
    """
    
    def __init__(
        self,
        confidence_engine: Optional[ConfidenceEngine] = None,
        group_builder: Optional[ScoreGroupBuilder] = None
    ):
        """
        Inicjalizacja Ranker
        
        Args:
            confidence_engine: Opcjonalny Confidence Engine
            group_builder: Opcjonalny Score Group Builder
        """
        self.confidence_engine = confidence_engine or ConfidenceEngine()
        self.group_builder = group_builder or ScoreGroupBuilder()
        
        logger.info("[ExactScoreRanker] Inicjalizacja")
    
    def _calculate_combined_probability(
        self,
        world_prob: float,
        market_prob: float,
        poisson_prob: float
    ) -> float:
        """
        Oblicz łączne prawdopodobieństwo (średnia ważona)
        
        Args:
            world_prob: Prawdopodobieństwo WORLD (0-100%)
            market_prob: Prawdopodobieństwo Market (0-100%)
            poisson_prob: Prawdopodobieństwo Poisson (0-100%)
        
        Returns:
            Combined probability (0-100%)
        """
        # Wagi dla prawdopodobieństw
        prob_weights = {
            "world": 0.4,
            "market": 0.35,
            "poisson": 0.25
        }
        
        combined = (world_prob * prob_weights["world"] +
                   market_prob * prob_weights["market"] +
                   poisson_prob * prob_weights["poisson"])
        
        return combined
    
    def _calculate_value_score(
        self,
        probability: float,
        confidence: float
    ) -> float:
        """
        Oblicz value_score (0-100%)
        
        Im wyższa pewność i niższe prawdopodobieństwo (wysoki kurs), tym wyższy value_score
        
        Args:
            probability: Prawdopodobieństwo (0-100%)
            confidence: Pewność (0-1)
        
        Returns:
            Value score (0-100%)
        """
        # Im niższe prawdopodobieństwo, tym wyższa wartość (jeśli pewność jest wysoka)
        # Normalizuj prawdopodobieństwo do 0-1
        prob_normalized = probability / 100.0
        
        # Value score = (1 - prob_normalized) * confidence * 100
        # Jeśli prawdopodobieństwo jest niskie, ale pewność wysoka -> wysoki value_score
        value_score = (1.0 - prob_normalized) * confidence * 100.0
        
        return max(0.0, min(100.0, value_score))
    
    def _calculate_risk_score(
        self,
        probability: float,
        confidence: float
    ) -> float:
        """
        Oblicz risk_score (0-100%)
        
        Im wyższe prawdopodobieństwo i niższa pewność, tym wyższe ryzyko
        
        Args:
            probability: Prawdopodobieństwo (0-100%)
            confidence: Pewność (0-1)
        
        Returns:
            Risk score (0-100%)
        """
        # Normalizuj prawdopodobieństwo do 0-1
        prob_normalized = probability / 100.0
        
        # Ryzyko = prawdopodobieństwo * (1 - pewność)
        # Im wyższe prawdopodobieństwo i niższa pewność, tym wyższe ryzyko
        risk_score = prob_normalized * (1.0 - confidence) * 100.0
        
        return max(0.0, min(100.0, risk_score))
    
    def _extract_score_data(
        self,
        candidate: ExactScoreCandidate,
        group_confidence_map: Dict[str, float],
        group_type_map: Dict[str, ScoreGroupType]
    ) -> ScoreRankingData:
        """
        Wyekstraktuj dane rankingowe z kandydata
        
        Args:
            candidate: ExactScoreCandidate
            group_confidence_map: Mapowanie wynik -> group_confidence
            group_type_map: Mapowanie wynik -> group_type
        
        Returns:
            ScoreRankingData
        """
        evidence = candidate.evidence
        
        # Prawdopodobieństwa
        world_prob = candidate.world_probability * 100  # Konwersja na %
        market_prob = candidate.market_probability * 100
        poisson_prob = candidate.poisson_probability * 100
        
        # Combined probability
        combined_prob = self._calculate_combined_probability(
            world_prob, market_prob, poisson_prob
        )
        
        # Pewność
        if isinstance(candidate.confidence, ConfidenceLevel):
            confidence_map = {
                ConfidenceLevel.CRITICAL: 0.2,
                ConfidenceLevel.LOW: 0.4,
                ConfidenceLevel.MEDIUM: 0.7,
                ConfidenceLevel.HIGH: 0.85,
                ConfidenceLevel.VERY_HIGH: 0.95
            }
            confidence_score = confidence_map.get(candidate.confidence, 0.5)
        else:
            confidence_score = float(candidate.confidence)
        
        # Group confidence i type
        group_confidence = group_confidence_map.get(candidate.score, 0.0)
        group_type = group_type_map.get(candidate.score, None)
        
        # Value score
        value_score = self._calculate_value_score(combined_prob, confidence_score)
        
        # Risk score
        risk_score = self._calculate_risk_score(combined_prob, confidence_score)
        
        # Sample strength
        world_max_samples = evidence.world_max_samples
        sample_strength = self._calculate_sample_strength(world_max_samples)
        
        # Market alignment i Poisson alignment
        if hasattr(candidate, 'market_alignment'):
            market_alignment = candidate.market_alignment
        else:
            market_alignment = 0.5  # Domyślna wartość neutralna
            
        if hasattr(candidate, 'poisson_alignment'):
            poisson_alignment = candidate.poisson_alignment
        else:
            poisson_alignment = 0.5  # Domyślna wartość neutralna
        
        # Oblicz fair odds (1 / combined_probability_normalized)
        # combined_probability jest w %, więc normalizujemy do 0-1
        combined_prob_normalized = combined_prob / 100.0
        fair_odds = 1.0 / combined_prob_normalized if combined_prob_normalized > 0 else 0.0
        
        # Oblicz market_value (prawdopodobieństwo * confidence)
        market_value = combined_prob_normalized * confidence_score
        
        # Oblicz risk_reward_ratio
        risk_reward_ratio = value_score / risk_score if risk_score > 0 else 0.0
        
        return ScoreRankingData(
            score=candidate.score,
            world_probability=world_prob,
            market_probability=market_prob,
            poisson_probability=poisson_prob,
            combined_probability=combined_prob,
            confidence_score=confidence_score,
            confidence_level=candidate.confidence if isinstance(candidate.confidence, ConfidenceLevel) else ConfidenceLevel.LOW,
            group_confidence=group_confidence,
            group_type=group_type,
            sample_strength=sample_strength,
            market_alignment=market_alignment,
            poisson_alignment=poisson_alignment,
            value_score=value_score,
            risk_score=risk_score,
            fair_odds=fair_odds,
            market_value=market_value,
            risk_reward_ratio=risk_reward_ratio,
            ranking_score=0.0  # Będzie obliczone później
        )
    
    def _calculate_sample_strength(self, sample_count: int) -> float:
        """
        Oblicz sample_strength na podstawie liczby przypadków
        
        Args:
            sample_count: Liczba przypadków
        
        Returns:
            Sample strength (0-1)
        """
        import math
        if sample_count <= 0:
            return 0.1
        
        # Skala logarytmiczna
        max_expected = 5000.0
        strength = math.log10(sample_count + 1) / math.log10(max_expected + 1)
        
        return max(strength, 0.1)
    
    def _calculate_individual_ranking_score(
        self,
        score_data: ScoreRankingData
    ) -> float:
        """
        Oblicz ranking_score dla pojedynczego wyniku
        
        Args:
            score_data: ScoreRankingData
        
        Returns:
            Ranking score (0-100%)
        """
        # Normalizuj combined_probability do 0-1
        prob_normalized = score_data.combined_probability / 100.0
        
        # Obliczcomponents
        components = {
            "combined_probability": prob_normalized,
            "confidence_score": score_data.confidence_score,
            "group_confidence": score_data.group_confidence,
            "value_score": score_data.value_score / 100.0
        }
        
        # Oblicz ranking score
        ranking_score = sum(
            components[component_key] * INDIVIDUAL_RANKING_WEIGHTS[component_key]
            for component_key in INDIVIDUAL_RANKING_WEIGHTS
        )
        
        # Skaluj do 0-100%
        return ranking_score * 100.0
    
    def _calculate_group_ranking_score(
        self,
        group: ScoreGroup
    ) -> Tuple[float, float, float, float]:
        """
        Oblicz ranking_score i dane rynkowe dla grupy
        
        Args:
            group: ScoreGroup
        
        Returns:
            Tuple: (ranking_score, total_probability, group_fair_odds, group_market_value)
        """
        # Średnia confidence w grupie
        avg_confidence = group.average_confidence if group.average_confidence > 0 else 0.0
        
        # Group confidence
        group_confidence = group.group_confidence if group.group_confidence > 0 else 0.0
        
        # Średnie prawdopodobieństwo w grupie
        if group.scores:
            avg_prob = sum(gs.world_probability for gs in group.scores) / len(group.scores)
            avg_prob_normalized = avg_prob / 100.0
            # Total probability (suma prawdopodobieństw)
            total_probability = sum(gs.world_probability for gs in group.scores)
        else:
            avg_prob_normalized = 0.0
            total_probability = 0.0
        
        # Sample strength
        if group.total_sample_count > 0:
            sample_strength = self._calculate_sample_strength(group.total_sample_count)
        else:
            sample_strength = 0.1
        
        # Oblicz ranking score
        ranking_score = (avg_confidence * GROUP_RANKING_WEIGHTS["average_confidence"] +
                        group_confidence * GROUP_RANKING_WEIGHTS["group_confidence"] +
                        avg_prob_normalized * GROUP_RANKING_WEIGHTS["average_probability"] +
                        sample_strength * GROUP_RANKING_WEIGHTS["sample_strength"])
        
        # Skaluj do 0-100%
        ranking_score_percent = ranking_score * 100.0
        
        # Oblicz dane rynkowe dla grupy
        # Group fair odds (1 / total_probability_normalized)
        total_prob_normalized = total_probability / 100.0
        group_fair_odds = 1.0 / total_prob_normalized if total_prob_normalized > 0 else 0.0
        
        # Group market value (total_probability_normalized * group_confidence)
        group_market_value = total_prob_normalized * group_confidence
        
        return ranking_score_percent, total_probability, group_fair_odds, group_market_value
    
    def _classify_scenario_type(
        self,
        score: str
    ) -> List[ScenarioType]:
        """
        Klasyfikuj wynik do typów scenariuszy
        
        Args:
            score: Wynik w formacie "X:Y"
        
        Returns:
            Lista typów scenariuszy
        """
        home, away = map(int, score.split(":"))
        total_goals = home + away
        scenarios = []
        
        # Wanna scenariusza
        if home > away:
            scenarios.append(ScenarioType.HOME_VICTORY)
        elif away > home:
            scenarios.append(ScenarioType.AWAY_VICTORY)
        else:
            scenarios.append(ScenarioType.DRAW)
        
        # Wysoki/niski wynik
        if total_goals >= 4:
            scenarios.append(ScenarioType.HIGH_SCORING)
        elif total_goals <= 1:
            scenarios.append(ScenarioType.LOW_SCORING)
        
        # Ofensywny/defensywny
        if total_goals >= 3:
            scenarios.append(ScenarioType.OFFENSIVE)
        elif total_goals == 0:
            scenarios.append(ScenarioType.DEFENSIVE)
        
        return scenarios
    
    def _build_scenario_from_group(
        self,
        group: ScoreGroup,
        score_scenario_map: Dict[str, List[ScenarioType]]
    ) -> List[Tuple[ScenarioType, float, float]]:
        """
        Utwórz dane scenariusza z grupy
        
        Args:
            group: ScoreGroup
            score_scenario_map: Mapowanie wynik -> lista scenariuszy
        
        Returns:
            Lista (scenario_type, probability, confidence)
        """
        scenario_data = {}
        
        for gs in group.scores:
            scenarios = score_scenario_map.get(gs.score, [])
            for scenario in scenarios:
                if scenario not in scenario_data:
                    scenario_data[scenario] = {"probability": 0.0, "count": 0, "confidence": 0.0}
                
                scenario_data[scenario]["probability"] += gs.world_probability
                scenario_data[scenario]["count"] += 1
                scenario_data[scenario]["confidence"] += gs.confidence
        
        # Normalizuj dane
        result = []
        for scenario, data in scenario_data.items():
            avg_prob = data["probability"] / data["count"] if data["count"] > 0 else 0.0
            avg_confidence = data["confidence"] / data["count"] if data["count"] > 0 else 0.0
            
            result.append((scenario, avg_prob, avg_confidence))
        
        return result
    
    def rank_individual_scores(
        self,
        candidates: List[ExactScoreCandidate],
        group_collection: Optional[ScoreGroupCollection] = None
    ) -> List[ScoreRankingData]:
        """
        Utwórz ranking pojedynczych wyników
        
        Args:
            candidates: Lista ExactScoreCandidate
            group_collection: Opcjonalna ScoreGroupCollection
        
        Returns:
            Lista ScoreRankingData (posortowana po ranking_score)
        """
        # Buduj mapowanie group_confidence i group_type
        group_confidence_map = {}
        group_type_map = {}
        
        if group_collection:
            for group_type, group in group_collection.groups.items():
                for gs in group.scores:
                    confidence_val = getattr(gs, 'confidence', 0.0)
                    group_confidence_map[gs.score] = max(
                        group_confidence_map.get(gs.score, 0.0), 
                        confidence_val
                    )
                    group_type_map[gs.score] = group_type
        
        # Wyekstraktuj dane rankingowe
        score_datas = []
        for candidate in candidates:
            score_data = self._extract_score_data(
                candidate, group_confidence_map, group_type_map
            )
            score_datas.append(score_data)
        
        # Oblicz ranking_score i value_score
        for score_data in score_datas:
            score_data.ranking_score = self._calculate_individual_ranking_score(score_data)
        
        # Sortuj po ranking_score (malejąco)
        score_datas.sort(key=lambda x: x.ranking_score, reverse=True)
        
        # Uaktualnij pozycje
        for i, score_data in enumerate(score_datas, 1):
            score_data.rank = i
        
        return score_datas
    
    def rank_scenario_groups(
        self,
        group_collection: ScoreGroupCollection
    ) -> List[GroupRankingData]:
        """
        Utwórz ranking grup strategicznych
        
        Args:
            group_collection: ScoreGroupCollection
        
        Returns:
            Lista GroupRankingData (posortowana po ranking_score)
        """
        group_datas = []
        
        for group_type, group in group_collection.groups.items():
            definition = GROUP_DEFINITIONS.get(group_type, {})
            
            # Oblicz ranking_score i dane rynkowe
            ranking_score, total_probability, group_fair_odds, group_market_value = \
                self._calculate_group_ranking_score(group)
            
            # Oblicz average_probability z GroupScore
            avg_prob = sum(gs.world_probability for gs in group.scores) / len(group.scores) if group.scores else 0.0
            
            # Utwórz GroupRankingData
            group_data = GroupRankingData(
                group_type=group_type,
                name=definition.get("name", group_type.value),
                description=definition.get("description", ""),
                average_confidence=group.average_confidence,
                group_confidence=group.group_confidence,
                total_sample_count=group.total_sample_count,
                average_probability=avg_prob,
                total_probability=total_probability,
                group_fair_odds=group_fair_odds,
                group_market_value=group_market_value,
                ranking_score=ranking_score,
                scores=[gs.score for gs in group.scores]
            )
            
            group_datas.append(group_data)
        
        # Sortuj po ranking_score (malejąco)
        group_datas.sort(key=lambda x: x.ranking_score, reverse=True)
        
        # Uaktualnij pozycje
        for i, group_data in enumerate(group_datas, 1):
            group_data.rank = i
        
        return group_datas
    
    def rank_match_scenarios(
        self,
        score_datas: List[ScoreRankingData],
        group_datas: List[GroupRankingData]
    ) -> List[ScenarioRankingData]:
        """
        Utwórz ranking scenariuszy meczowych
        
        Args:
            score_datas: Lista ScoreRankingData
            group_datas: Lista GroupRankingData
        
        Returns:
            Lista ScenarioRankingData (posortowana po ranking_score)
        """
        # Buduj mapowanie wynik -> scenariusze
        score_scenario_map = {}
        for score_data in score_datas:
            scenarios = self._classify_scenario_type(score_data.score)
            score_scenario_map[score_data.score] = scenarios
        
        # Budaż mapowanie scenariusz -> dane
        scenario_data_map = {}
        
        for score_data in score_datas:
            scenarios = score_scenario_map.get(score_data.score, [])
            for scenario in scenarios:
                if scenario not in scenario_data_map:
                    scenario_data_map[scenario] = {
                        "probability": 0.0,
                        "confidence": 0.0,
                        "count": 0,
                        "related_scores": set(),
                        "group_support": 0.0
                    }
                
                # Dodaj dane
                scenario_data_map[scenario]["probability"] += score_data.combined_probability
                scenario_data_map[scenario]["confidence"] += score_data.confidence_score
                scenario_data_map[scenario]["count"] += 1
                scenario_data_map[scenario]["related_scores"].add(score_data.score)
        
        # Dodaj wsparcie od grup
        for group_data in group_datas:
            group_type = group_data.group_type
            group_scenarios = self._get_scenarios_from_group_type(group_type)
            
            for scenario in group_scenarios:
                if scenario in scenario_data_map:
                    scenario_data_map[scenario]["group_support"] += group_data.ranking_score
        
        # Utwórz ScenarioRankingData
        scenario_datas = []
        for scenario, data in scenario_data_map.items():
            avg_probability = data["probability"] / data["count"] if data["count"] > 0 else 0.0
            avg_confidence = data["confidence"] / data["count"] if data["count"] > 0 else 0.0
            
            # Mapowanie ScenarioType na nazwy
            scenario_names = {
                ScenarioType.HOME_VICTORY: ("Zwycięstwo gospodarzy", "Gospodarze wygrywają mecz"),
                ScenarioType.AWAY_VICTORY: ("Zwycięstwo gości", "Goście wygrywają mecz"),
                ScenarioType.DRAW: ("Remis", "Mecz kończy się remisem"),
                ScenarioType.HIGH_SCORING: ("Wysoki wynik", "Mecz z wieloma golami (4+)"),
                ScenarioType.LOW_SCORING: ("Niski wynik", "Mecz z małą liczbą goli (0-1)"),
                ScenarioType.BALANCED: ("Zrównoważony", "Zrównoważony przebieg meczu"),
                ScenarioType.OFFENSIVE: ("Ofensywny", "Mecz z ofensywnym charakterem"),
                ScenarioType.DEFENSIVE: ("Defensywny", "Mecz z defensywnym charakterem")
            }
            
            name, description = scenario_names.get(scenario, (scenario.value, ""))
            
            # Oblicz confidence level
            if avg_confidence >= 0.8:
                confidence_level = ConfidenceLevel.HIGH
            elif avg_confidence >= 0.6:
                confidence_level = ConfidenceLevel.MEDIUM
            else:
                confidence_level = ConfidenceLevel.LOW
            
            # Oblicz ranking_score
            group_support_normalized = data["group_support"] / 100.0  # Normalizuj
            ranking_score = (avg_probability / 100.0 * SCENARIO_RANKING_WEIGHTS["probability"] +
                           avg_confidence * SCENARIO_RANKING_WEIGHTS["confidence"] +
                           group_support_normalized * SCENARIO_RANKING_WEIGHTS["group_support"])
            
            scenario_data = ScenarioRankingData(
                scenario_type=scenario,
                name=name,
                description=description,
                probability=avg_probability,
                confidence=avg_confidence,
                confidence_level=confidence_level,
                ranking_score=ranking_score * 100.0,  # Skaluj do 0-100%
                related_scores=list(data["related_scores"])
            )
            
            scenario_datas.append(scenario_data)
        
        # Sortuj po ranking_score (malejąco)
        scenario_datas.sort(key=lambda x: x.ranking_score, reverse=True)
        
        # Uaktualnij pozycje
        for i, scenario_data in enumerate(scenario_datas, 1):
            scenario_data.rank = i
        
        return scenario_datas
    
    def _get_scenarios_from_group_type(
        self,
        group_type
    ) -> List[ScenarioType]:
        """
        Mapowanie ScoreGroupType z score_group_builder na ScenarioType
        
        Args:
            group_type: ScoreGroupType z score_group_builder
        
        Returns:
            Lista ScenarioType
        """
        from .score_group_builder import ScoreGroupType as SGBScoreGroupType
        
        mapping = {
            SGBScoreGroupType.HOME_DOMINANCE: [ScenarioType.HOME_VICTORY, ScenarioType.OFFENSIVE],
            SGBScoreGroupType.AWAY_DOMINANCE: [ScenarioType.AWAY_VICTORY, ScenarioType.OFFENSIVE],
            SGBScoreGroupType.DRAW_LOW_SCORE: [ScenarioType.DRAW, ScenarioType.LOW_SCORING],
            SGBScoreGroupType.BALANCED_SCORE: [ScenarioType.BALANCED, ScenarioType.DRAW],
            SGBScoreGroupType.HIGH_SCORE: [ScenarioType.HIGH_SCORING, ScenarioType.OFFENSIVE],
            SGBScoreGroupType.SAFE_RESULTS: [ScenarioType.DEFENSIVE, ScenarioType.LOW_SCORING],
            SGBScoreGroupType.OFFENSIVE: [ScenarioType.OFFENSIVE, ScenarioType.HIGH_SCORING]
        }
        
        return mapping.get(group_type, [])
    
    def create_ranking(
        self,
        candidates: List[ExactScoreCandidate],
        group_collection: Optional[ScoreGroupCollection] = None,
        match_id: str = "unknown",
        match_name: str = "Unknown Match"
    ) -> ExactScoreRanking:
        """
        Utwórz pełny ExactScoreRanking
        
        Główna funkcja modułu.
        
        Args:
            candidates: Lista ExactScoreCandidate
            group_collection: Opcjonalna ScoreGroupCollection
            match_id: Identyfikator meczu
            match_name: Nazwa meczu
        
        Returns:
            ExactScoreRanking
        
        Example:
            candidates = [...]  # Lista ExactScoreCandidate
            group_collection = ScoreGroupBuilder().build_groups_from_candidates(candidates)
            ranking = ranker.create_ranking(candidates, group_collection, "match_1", "Team A - Team B")
        """
        logger.info(f"[ExactScoreRanker] Tworzenie rankingu dla {match_name}")
        
        # Jeśli nie ma group_collection, utwórz go
        if not group_collection and candidates:
            group_collection = self.group_builder.build_groups_from_candidates(candidates)
        
        # Ranking pojedynczych wyników
        individual_scores = self.rank_individual_scores(candidates, group_collection)
        
        # Ranking grup (jeśli dostępne)
        scenario_groups = []
        if group_collection:
            scenario_groups = self.rank_scenario_groups(group_collection)
        
        # Ranking scenariuszy
        match_scenarios = self.rank_match_scenarios(individual_scores, scenario_groups)
        
        # Utwórz ExactScoreRanking
        ranking = ExactScoreRanking(
            match_id=match_id,
            match_name=match_name,
            individual_scores=individual_scores,
            scenario_groups=scenario_groups,
            match_scenarios=match_scenarios,
            metadata={
                "source": "ExactScoreRanker",
                "version": "5.2.9.x",
                "candidates_count": len(candidates),
                "groups_count": len(scenario_groups)
            }
        )
        
        logger.info(f"[ExactScoreRanker] Ranking utworzony: {len(individual_scores)} wyników, {len(scenario_groups)} grup, {len(match_scenarios)} scenariuszy")
        
        return ranking
    
    def create_ranking_from_knowledge(
        self,
        knowledge: ExactScoreKnowledge
    ) -> ExactScoreRanking:
        """
        Utwórz ranking z ExactScoreKnowledge
        
        Args:
            knowledge: ExactScoreKnowledge
        
        Returns:
            ExactScoreRanking
        """
        # Buduj group_collection z knowledge
        group_collection = self.group_builder.build_groups_from_knowledge(knowledge)
        
        return self.create_ranking(
            candidates=knowledge.candidates,
            group_collection=group_collection,
            match_id=knowledge.match_id,
            match_name=knowledge.match_name
        )


# =============================================================================
# FUNKCJE API
# =============================================================================

def rank_individual_scores(
    candidates: List[ExactScoreCandidate],
    group_collection: Optional[ScoreGroupCollection] = None
) -> List[ScoreRankingData]:
    """
    Funkcja wygodna - utwórz ranking pojedynczych wyników
    
    Args:
        candidates: Lista ExactScoreCandidate
        group_collection: Opcjonalna ScoreGroupCollection
    
    Returns:
        Lista ScoreRankingData
    """
    ranker = ExactScoreRanker()
    return ranker.rank_individual_scores(candidates, group_collection)


def rank_scenario_groups(
    group_collection: ScoreGroupCollection
) -> List[GroupRankingData]:
    """
    Funkcja wygodna - utwórz ranking grup
    
    Args:
        group_collection: ScoreGroupCollection
    
    Returns:
        Lista GroupRankingData
    """
    ranker = ExactScoreRanker()
    return ranker.rank_scenario_groups(group_collection)


def create_ranking(
    candidates: List[ExactScoreCandidate],
    match_id: str = "unknown",
    match_name: str = "Unknown Match",
    group_collection: Optional[ScoreGroupCollection] = None
) -> ExactScoreRanking:
    """
    Funkcja wygodna - utwórz pełny ranking
    
    Args:
        candidates: Lista ExactScoreCandidate
        match_id: Identyfikator meczu
        match_name: Nazwa meczu
        group_collection: Opcjonalna ScoreGroupCollection
    
    Returns:
        ExactScoreRanking
    """
    ranker = ExactScoreRanker()
    return ranker.create_ranking(candidates, group_collection, match_id, match_name)


def create_ranking_from_knowledge(
    knowledge: ExactScoreKnowledge
) -> ExactScoreRanking:
    """
    Funkcja wygodna - utwórz ranking z knowledge
    
    Args:
        knowledge: ExactScoreKnowledge
    
    Returns:
        ExactScoreRanking
    """
    ranker = ExactScoreRanker()
    return ranker.create_ranking_from_knowledge(knowledge)


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    # Enums
    'RankingType',
    'ScenarioType',
    
    # Models
    'ScoreRankingData',
    'GroupRankingData',
    'ScenarioRankingData',
    'ExactScoreRanking',
    
    # Ranker
    'ExactScoreRanker',
    
    # Config
    'INDIVIDUAL_RANKING_WEIGHTS',
    'GROUP_RANKING_WEIGHTS',
    'SCENARIO_RANKING_WEIGHTS',
    
    # Functions
    'rank_individual_scores',
    'rank_scenario_groups',
    'create_ranking',
    'create_ranking_from_knowledge'
]

print(f"[EXACT_SCORE_RANKER] Moduł załadowany - ETAP 5.2.9.x")