"""
SSI V5 Exact Score Engine - Models
====================================

ETAP: 5.2.9.x - Exact Score Market Intelligence Foundation

Modele danych dla Market Intelligence Layer:
- ExactScoreCandidate: Kandydat wyniku z pełną ewidencją
- ScoreEvidence: Dowód dla wyniku (WORLD + MARKET + POISSON)
- ExactScoreKnowledge: Finalny obiekt wiedzy dla agentów
- ConfidenceLevel: Poziomy pewności
- ScoreGroup: Grupa strategiczna wyników
- ScoreGroupType: Typy grup strategicznych

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any
from enum import Enum
import json


# =============================================================================
# CONSTANTS
# =============================================================================

# Tylko te 15 wyników jest analizowanych - redukcja szumu
VALID_SCORES: List[str] = [
    "1:0", "2:0", "3:0",
    "2:1", "3:1", "3:2",
    "0:1", "0:2", "0:3",
    "1:2", "1:3", "2:3",
    "0:0", "1:1", "2:2"
]

# Poziomy pewności
class ConfidenceLevel(Enum):
    """Poziomy pewności dla prognoz"""
    CRITICAL = "CRITICAL"      # Wszystkie źródła rozbieżne, mała próbka
    LOW = "LOW"                # Niska zgodność, mała próbka
    MEDIUM = "MEDIUM"          # Średnia zgodność, średnia próbka
    HIGH = "HIGH"              # Dobra zgodność, duża próbka
    VERY_HIGH = "VERY_HIGH"    # Pełna zgodność, bardzo duża próbka


# Typy grup strategicznych
class ScoreGroupType(Enum):
    """Typy grup strategicznych"""
    SAFE = "SAFE"              # Bezpieczne wyniki (niskie ryzyko)
    OFFENSIVE = "OFFENSIVE"    # Ofensywne wyniki (wysokie strzelanie)
    GUESTS = "GUESTS"          # Wygrane gości
    HOSTS = "HOSTS"            # Wygrane gospodarzy
    DRAW = "DRAW"              # Remisy
    HIGH_VALUE = "HIGH_VALUE"  # Wysoka wartość kursowa
    LOW_RISK = "LOW_RISK"      # Niskie ryzyko
    BALANCED = "BALANCED"      # Zrównoważone


# =============================================================================
# DATA MODELS
# =============================================================================

@dataclass
class WorldLevelEvidence:
    """Ewidencja dla jednego poziomu WORLD (level_1, level_2, full_group)"""
    
    level: str  # "level_1", "level_2", "full_group"
    percentage: float  # Procentowy udział wyniku
    sample_count: int  # Liczba przypadków (ilosc_przypadkow)
    
    def __post_init__(self):
        """Walidacja danych"""
        if not isinstance(self.percentage, (int, float)) or self.percentage < 0:
            raise ValueError(f"Percentage must be >= 0, got {self.percentage}")
        if not isinstance(self.sample_count, int) or self.sample_count <= 0:
            raise ValueError(f"Sample count must be > 0, got {self.sample_count}")
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "level": self.level,
            "percentage": self.percentage,
            "samples": self.sample_count
        }


@dataclass
class ScoreEvidence:
    """
    Dowód dla wyniku - numpy sprawdzenia wszyskich źródeł
    
    Przechowuje pełną ewidencję dla jednego wyniku:
    - WORLD (level_1, level_2, full_group) z uwzględnieniem wielkości próbek
    - MARKET (prawdopodobieństwo z kursów bukmacherskich)
    - POISSON (prawdopodobieństwo z modelu Poisson Dixon Coles)
    """
    
    score: str  # Wynik w formacie "X:Y"
    
    # WORLD Evidence
    world_level_1: Optional[WorldLevelEvidence] = None
    world_level_2: Optional[WorldLevelEvidence] = None
    world_full_group: Optional[WorldLevelEvidence] = None
    
    # MARKET Evidence
    market_probability: Optional[float] = None
    
    # POISSON Evidence
    poisson_probability: Optional[float] = None
    
    def __post_init__(self):
        """Walidacja danych"""
        if self.score not in VALID_SCORES:
            raise ValueError(f"Score {self.score} not in VALID_SCORES")
        
        # Walidacja prawdopodobieństw
        for prob in [self.market_probability, self.poisson_probability]:
            if prob is not None and (prob < 0 or prob > 100):
                raise ValueError(f"Probability must be between 0-100, got {prob}")
    
    @property
    def world_weighted_average(self) -> Optional[float]:
        """
        Średnia ważona po wszystkich poziomach WORLD
        Waga = liczba przypadków (sample_count)
        """
        levels = [
            self.world_level_1,
            self.world_level_2,
            self.world_full_group
        ]
        
        valid_levels = [l for l in levels if l is not None]
        if not valid_levels:
            return None
        
        total_weight = sum(l.sample_count for l in valid_levels)
        if total_weight == 0:
            return None
            
        weighted_sum = sum(l.percentage * l.sample_count for l in valid_levels)
        return weighted_sum / total_weight
    
    @property
    def world_max_samples(self) -> int:
        """Maksymalna liczba przypadków spośród poziomów WORLD"""
        samples = []
        if self.world_level_1:
            samples.append(self.world_level_1.sample_count)
        if self.world_level_2:
            samples.append(self.world_level_2.sample_count)
        if self.world_full_group:
            samples.append(self.world_full_group.sample_count)
        
        return max(samples) if samples else 0
    
    @property
    def world_min_samples(self) -> int:
        """Minimalna liczba przypadków spośród poziomów WORLD"""
        samples = []
        if self.world_level_1:
            samples.append(self.world_level_1.sample_count)
        if self.world_level_2:
            samples.append(self.world_level_2.sample_count)
        if self.world_full_group:
            samples.append(self.world_full_group.sample_count)
        
        return min(samples) if samples else 0
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "score": self.score,
            "world": {
                "level_1": self.world_level_1.to_dict() if self.world_level_1 else None,
                "level_2": self.world_level_2.to_dict() if self.world_level_2 else None,
                "full_group": self.world_full_group.to_dict() if self.world_full_group else None,
            },
            "market": {
                "probability": self.market_probability
            },
            "poisson": {
                "probability": self.poisson_probability
            },
            "world_weighted_average": self.world_weighted_average,
            "world_samples": {
                "max": self.world_max_samples,
                "min": self.world_min_samples
            }
        }


@dataclass
class ExactScoreCandidate:
    """
    Kandydat wyniku z pełną analizą i rankingiem
    
    Przechowuje:
    - Wynik
    - Ewidencję (ScoreEvidence)
    - Prawdopodobieństwa z różnych źródeł
    - Poziom pewności
    - Ranking
    - Dodatkowe metryki
    """
    
    score: str
    evidence: ScoreEvidence
    
    # Prawdopodobieństwa z normalizacji
    world_probability: float = 0.0
    market_probability: float = 0.0
    poisson_probability: float = 0.0
    
    # Combined probability (średnia ważona)
    combined_probability: float = 0.0
    
    # Poziom pewności
    confidence: ConfidenceLevel = ConfidenceLevel.LOW
    
    # Ranking (1 = najlepszy)
    rank: int = 0
    
    # Ryzyko (0-100)
    risk_score: float = 0.0
    
    # Wartość kursowa
    value_score: float = 0.0
    
    # Notatki dla agentów
    notes: List[str] = field(default_factory=list)
    
    def __post_init__(self):
        """Walidacja danych"""
        if self.score not in VALID_SCORES:
            raise ValueError(f"Score {self.score} not in VALID_SCORES")
        
        if not isinstance(self.world_probability, (int, float)) or self.world_probability < 0:
            raise ValueError(f"World probability must be >= 0")
        if not isinstance(self.market_probability, (int, float)) or self.market_probability < 0:
            raise ValueError(f"Market probability must be >= 0")
        if not isinstance(self.poisson_probability, (int, float)) or self.poisson_probability < 0:
            raise ValueError(f"Poisson probability must be >= 0")
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "score": self.score,
            "world_probability": self.world_probability,
            "market_probability": self.market_probability,
            "poisson_probability": self.poisson_probability,
            "combined_probability": self.combined_probability,
            "confidence": self.confidence.value,
            "rank": self.rank,
            "risk_score": self.risk_score,
            "value_score": self.value_score,
            "evidence": self.evidence.to_dict(),
            "notes": self.notes
        }


@dataclass 
class ScoreGroup:
    """
    Grupa strategiczna wyników
    
    Grupa wyników o podobnych charakterystykach, np.:
    - Bezpieczne wyniki (SAFE)
    - Ofensywne wyniki (OFFENSIVE)
    - Wygrane gości (GUESTS)
    """
    
    group_type: ScoreGroupType
    name: str
    description: str
    scores: List[str]  # Lista wyników należących do grupy
    
    # Statystyki grupy
    average_probability: float = 0.0
    total_risk: float = 0.0
    group_confidence: ConfidenceLevel = ConfidenceLevel.MEDIUM
    
    def __post_init__(self):
        """Walidacja danych"""
        if not all(score in VALID_SCORES for score in self.scores):
            invalid_scores = [s for s in self.scores if s not in VALID_SCORES]
            raise ValueError(f"Invalid scores in group: {invalid_scores}")
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "group_type": self.group_type.value,
            "name": self.name,
            "description": self.description,
            "scores": self.scores,
            "average_probability": self.average_probability,
            "total_risk": self.total_risk,
            "confidence": self.group_confidence.value
        }


@dataclass
class ExactScoreKnowledge:
    """
    Finalny obiekt wiedzy dla agentów i Strategy Laboratory
    
    Zawiera:
    - Informacje o meczu
    - Listę kandydatów (ExactScoreCandidate)
    - Grupy strategiczne (ScoreGroup)
    - Charakterystyka rynku
    - Metadane
    """
    
    # Informacje o meczu
    match_id: str
    match_name: str
    
    # Lista kandydatów (posegregowanych po rankingu)
    candidates: List[ExactScoreCandidate] = field(default_factory=list)
    
    # Grupy strategiczne
    score_groups: List[ScoreGroup] = field(default_factory=list)
    
    # Najlepsze 3 wyniki
    top_3_scores: List[str] = field(default_factory=list)
    
    # Charakterystyka rynku
    market_characteristics: Dict[str, Any] = field(default_factory=dict)
    
    # Metryki jakości
    quality_metrics: Dict[str, float] = field(default_factory=dict)
    
    # Czas generowania
    generated_at: str = ""
    
    def __post_init__(self):
        """Sortowanie kandydatów po rankingu"""
        self.candidates.sort(key=lambda c: c.rank)
        self.top_3_scores = [c.score for c in self.candidates[:3]]
        
        if not self.generated_at:
            from datetime import datetime
            self.generated_at = datetime.now().isoformat()
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "match_id": self.match_id,
            "match_name": self.match_name,
            "candidates": [c.to_dict() for c in self.candidates],
            "score_groups": [g.to_dict() for g in self.score_groups],
            "top_3_scores": self.top_3_scores,
            "market_characteristics": self.market_characteristics,
            "quality_metrics": self.quality_metrics,
            "generated_at": self.generated_at
        }
    
    def to_json(self, indent: int = 2) -> str:
        """Konwersja do JSON"""
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)
    
    def get_score_candidate(self, score: str) -> Optional[ExactScoreCandidate]:
        """Pobierz kandydata dla danego wyniku"""
        for candidate in self.candidates:
            if candidate.score == score:
                return candidate
        return None
    
    def get_group_by_type(self, group_type: ScoreGroupType) -> Optional[ScoreGroup]:
        """Pobierz grupę po typie"""
        for group in self.score_groups:
            if group.group_type == group_type:
                return group
        return None


# =============================================================================
# FACTORY FUNCTIONS
# =============================================================================

def create_score_evidence(
    score: str,
    world_level_1: Optional[WorldLevelEvidence] = None,
    world_level_2: Optional[WorldLevelEvidence] = None,
    world_full_group: Optional[WorldLevelEvidence] = None,
    market_probability: Optional[float] = None,
    poisson_probability: Optional[float] = None
) -> ScoreEvidence:
    """Tworzy ScoreEvidence z walidacją"""
    return ScoreEvidence(
        score=score,
        world_level_1=world_level_1,
        world_level_2=world_level_2,
        world_full_group=world_full_group,
        market_probability=market_probability,
        poisson_probability=poisson_probability
    )


def create_world_level_evidence(
    level: str,
    percentage: float,
    sample_count: int
) -> WorldLevelEvidence:
    """Tworzy WorldLevelEvidence z walidacją"""
    return WorldLevelEvidence(
        level=level,
        percentage=percentage,
        sample_count=sample_count
    )


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    # Constants
    'VALID_SCORES',
    
    # Enums
    'ConfidenceLevel',
    'ScoreGroupType',
    
    # Models
    'WorldLevelEvidence',
    'ScoreEvidence', 
    'ExactScoreCandidate',
    'ScoreGroup',
    'ExactScoreKnowledge',
    
    # Factory functions
    'create_score_evidence',
    'create_world_level_evidence',
]


print(f"[MODELS] Moduł models.py załadowany - ETAP 5.2.9.x")