"""
SSI V5 Exact Score Engine - Score Group Builder
=================================================

ETAP: 5.2.9.x - Score Group Builder

Odpowiedzialność:
- Tworzenie grup wyników dokładnych (Exact Scores)
- Klasyfikacja wyników do kategorii strategicznych
- Obliczanie group_confidence (średnia ważona)
- Sortowanie i ranking grup
- Przygotowanie danych dla Strategy Laboratory

Założenia:
- System NIE wybiera pojedynczego wyniku
- Tworzy grupy wyników, które mogą być użyte przez:
  * Strategy Laboratory
  * Coupon Laboratory  
  * Agentów predykcyjnych
  * Strategy Evolution

Idea grupowania:
Zamiast traktować 1:1, 1:0, 2:0 jako trzech niezależnych typów,
tworzymy grupę "Stabilne zwycięstwo gospodarzy" zawierającą:
- 1:0, 2:0, 3:0, 2:1, 3:1 (HOME_DOMINANCE)
- 0:1, 0:2, 0:3, 1:2, 1:3, 2:3 (AWAY_DOMINANCE)
- 0:0, 1:1, 2:2 (DRAW_LOW_SCORE)
- Wyniki z najwyższą zgodnością WORLD + MARKET + POISSON (BALANCED_SCORE)

роўne wag:
- confidence: 0.5
- market_probability: 0.3
- sample_strength: 0.2

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from enum import Enum
import logging
import math

from .models import (
    VALID_SCORES,
    ConfidenceLevel,
    ExactScoreCandidate,
    ExactScoreKnowledge,
    ScoreEvidence
)
from .confidence_engine import ConfidenceScore, ConfidenceEngine

# Konfiguracja logowania
logger = logging.getLogger(__name__)


# =============================================================================
# ENUMS - Typy Grup
# =============================================================================

class ScoreGroupType(Enum):
    """Typy grup strategicznych wyników"""
    HOME_DOMINANCE = "HOME_DOMINANCE"        # Wygrane gospodarzy
    AWAY_DOMINANCE = "AWAY_DOMINANCE"        # Wygrane gości
    DRAW_LOW_SCORE = "DRAW_LOW_SCORE"        # Remisy (niski wynik)
    BALANCED_SCORE = "BALANCED_SCORE"        # Zrównoważone wyniki (najwyższa zgodność)
    HIGH_SCORE = "HIGH_SCORE"                # Wysokie wyniki (3+ gol)
    SAFE_RESULTS = "SAFE_RESULTS"            # Bezpieczne wyniki (nisko ryzyko)
    OFFENSIVE = "OFFENSIVE"                  # Ofensywne scenariusze


class GroupQuality(Enum):
    """Jakość grupy"""
    EXCELLENT = "EXCELLENT"      # ≥ 0.90
    VERY_GOOD = "VERY_GOOD"      # 0.80 - 0.89
    GOOD = "GOOD"                # 0.70 - 0.79
    AVERAGE = "AVERAGE"          # 0.60 - 0.69
    BELOW_AVERAGE = "BELOW_AVERAGE"  # 0.50 - 0.59
    WEAK = "WEAK"                # < 0.50


# =============================================================================
# KONFIGURACJA GRUP
# =============================================================================

# DomAvatar dla typów grup
GROUP_DEFINITIONS = {
    ScoreGroupType.HOME_DOMINANCE: {
        "name": "Wygrane gospodarzy",
        "description": "Wyniki z wygraną gospodarzy (1:0, 2:0, 3:0, 2:1, 3:1)",
        "score_patterns": ["1:0", "2:0", "3:0", "2:1", "3:1"],
        "category": "home"
    },
    ScoreGroupType.AWAY_DOMINANCE: {
        "name": "Wygrane gości",
        "description": "Wyniki z wygraną gości (0:1, 0:2, 0:3, 1:2, 1:3, 2:3)",
        "score_patterns": ["0:1", "0:2", "0:3", "1:2", "1:3", "2:3"],
        "category": "away"
    },
    ScoreGroupType.DRAW_LOW_SCORE: {
        "name": "Remisy",
        "description": "Wyniki remisowe (0:0, 1:1, 2:2)",
        "score_patterns": ["0:0", "1:1", "2:2"],
        "category": "draw"
    },
    ScoreGroupType.BALANCED_SCORE: {
        "name": "Zrównoważone",
        "description": "Wyniki z najwyższą zgodnością WORLD + MARKET + POISSON",
        "score_patterns": [],  # Dynamicznie generowane
        "category": "balanced"
    },
    ScoreGroupType.HIGH_SCORE: {
        "name": "Wysokie wyniki",
        "description": "Wyniki z 3+ golami (3:0, 0:3, 3:1, 1:3, 3:2, 2:3)",
        "score_patterns": ["3:0", "0:3", "3:1", "1:3", "3:2", "2:3"],
        "category": "high_score"
    },
    ScoreGroupType.SAFE_RESULTS: {
        "name": "Bezpieczne",
        "description": "Wyniki o niskim ryzyku (0:0, 1:0, 0:1, 1:1, 2:0, 0:2)",
        "score_patterns": ["0:0", "1:0", "0:1", "1:1", "2:0", "0:2"],
        "category": "safe"
    },
    ScoreGroupType.OFFENSIVE: {
        "name": "Ofensywne",
        "description": "Wyniki z dużą liczbą goli (2:1, 3:0, 1:2, 0:3, 3:1, 2:3, 3:2, 1:3)",
        "score_patterns": ["2:1", "3:0", "1:2", "0:3", "3:1", "2:3", "3:2", "1:3"],
        "category": "offensive"
    }
}

# Wagi dla group_confidence
GROUP_CONFIDENCE_WEIGHTS = {
    "confidence": 0.5,      # Największa waga - pewność indywidualna
    "market_probability": 0.3,   # Prawdopodobieństwo rynkowe
    "sample_strength": 0.2      # Siła próbek
}


# =============================================================================
# MODELE DANYCH
# =============================================================================

@dataclass
class GroupScore:
    """
    Wynik z przypisanym confidence w grupie
    
    Zawiera dodatkowe metryki używane do obliczenia group_confidence
    """
    score: str                           # Wynik (np. "1:0")
    confidence: float = 0.0              # Pewność z Confidence Engine
    market_probability: float = 0.0    # Prawdopodobieństwo rynkowe (%)
    world_probability: float = 0.0     # Prawdopodobieństwo WORLD (%)
    sample_count: int = 0               # Liczba przypadków
    poisson_probability: float = 0.0   # Prawdopodobieństwo Poisson (%)
    
    def __post_init__(self):
        """Walidacja"""
        if self.score not in VALID_SCORES:
            raise ValueError(f"Score {self.score} not in VALID_SCORES")
        
        for attr in ['confidence', 'market_probability', 'world_probability', 'poisson_probability']:
            value = getattr(self, attr)
            if not isinstance(value, (int, float)) or value < 0:
                raise ValueError(f"{attr} must be >= 0, got {value}")
    
    def weighted_value(self) -> float:
        """Oblicz wartość ważoną dla grupowania"""
        return (self.confidence * GROUP_CONFIDENCE_WEIGHTS["confidence"] +
                self.market_probability * GROUP_CONFIDENCE_WEIGHTS["market_probability"] +
                (math.log10(self.sample_count + 1) / math.log10(5001)) * GROUP_CONFIDENCE_WEIGHTS["sample_strength"])
    
    def to_dict(self) -> Dict[str, Any]:
        """Serializacja do dict"""
        return {
            "score": self.score,
            "confidence": self.confidence,
            "market_probability": self.market_probability,
            "world_probability": self.world_probability,
            "sample_count": self.sample_count,
            "poisson_probability": self.poisson_probability
        }


@dataclass
class ScoreGroup:
    """
    Grupa strategiczna wyników
    
    Zawiera:
    - Identyfikator grupy
    - Listę wyników z metrykami
    - Metryki grupy
    """
    group_type: ScoreGroupType        # Typ grupy
    name: str                         # Nazwa grupy
    description: str                  # Opis
    scores: List[GroupScore] = field(default_factory=list)  # Wyniki w grupie
    
    # Metryki grupy
    group_confidence: float = 0.0    # Średnia ważona confidence
    total_sample_count: int = 0      # Całkowita liczba przypadków
    average_confidence: float = 0.0 # Średnia confidence
    quality: GroupQuality = GroupQuality.AVERAGE
    
    # Ranking
    rank: int = 0
    
    def __post_init__(self):
        """Obliczenia po inicjalizacji"""
        if self.scores:
            self._calculate_metrics()
    
    def _calculate_metrics(self):
        """Oblicz metryki grupy"""
        # Całkowita liczba przypadków
        self.total_sample_count = sum(s.sample_count for s in self.scores)
        
        # Średnia confidence
        if self.scores:
            self.average_confidence = sum(s.confidence for s in self.scores) / len(self.scores)
        
        # Group confidence (średnia ważona)
        if self.scores:
            weighted_sum = sum(s.weighted_value() for s in self.scores)
            self.group_confidence = weighted_sum / len(self.scores)
        
        # Klassfikacja jakości
        self.quality = self._classify_quality()
    
    def _classify_quality(self) -> GroupQuality:
        """Klasyfikuj jakość grupy"""
        if self.group_confidence >= 0.90:
            return GroupQuality.EXCELLENT
        elif self.group_confidence >= 0.80:
            return GroupQuality.VERY_GOOD
        elif self.group_confidence >= 0.70:
            return GroupQuality.GOOD
        elif self.group_confidence >= 0.60:
            return GroupQuality.AVERAGE
        elif self.group_confidence >= 0.50:
            return GroupQuality.BELOW_AVERAGE
        else:
            return GroupQuality.WEAK
    
    def add_score(self, group_score: GroupScore):
        """Dodaj wynik do grupy"""
        self.scores.append(group_score)
        self._calculate_metrics()
    
    def get_score(self, score: str) -> Optional[GroupScore]:
        """Pobierz GroupScore dla danego wyniku"""
        for gs in self.scores:
            if gs.score == score:
                return gs
        return None
    
    def to_dict(self) -> Dict[str, Any]:
        """Serializacja do dict"""
        return {
            "group_type": self.group_type.value,
            "name": self.name,
            "description": self.description,
            "scores": [s.to_dict() for s in self.scores],
            "metrics": {
                "group_confidence": self.group_confidence,
                "average_confidence": self.average_confidence,
                "total_sample_count": self.total_sample_count,
                "quality": self.quality.value
            },
            "rank": self.rank
        }


@dataclass
class ScoreGroupCollection:
    """
    Kolekcja wszystkich grup dla meczu
    
    Zawiera wszystkie ScoreGroup dla danego meczu
    """
    match_id: str
    groups: Dict[ScoreGroupType, ScoreGroup] = field(default_factory=dict)
    
    # Statystyki
    total_groups: int = 0
    best_group: Optional[ScoreGroup] = None
    groups_by_quality: Dict[GroupQuality, List[ScoreGroupType]] = field(default_factory=dict)
    
    def __post_init__(self):
        """Obliczenia"""
        self.total_groups = len(self.groups)
        self._index_by_quality()
        self._rank_groups()
    
    def _index_by_quality(self):
        """Indeksowanie grup po jakości"""
        for group_type, group in self.groups.items():
            quality = group.quality
            if quality not in self.groups_by_quality:
                self.groups_by_quality[quality] = []
            self.groups_by_quality[quality].append(group_type)
    
    def _rank_groups(self):
        """Ranking grup po group_confidence"""
        sorted_groups = sorted(
            self.groups.values(),
            key=lambda g: (g.group_confidence, g.total_sample_count),
            reverse=True
        )
        for rank, group in enumerate(sorted_groups, 1):
            group.rank = rank
        
        if sorted_groups:
            self.best_group = sorted_groups[0]
    
    def get_group(self, group_type: ScoreGroupType) -> Optional[ScoreGroup]:
        """Pobierz grupę po typie"""
        return self.groups.get(group_type)
    
    def get_best_groups(self, n: int = 3) -> List[ScoreGroup]:
        """Pobierz N najlepszych grup"""
        sorted_groups = sorted(
            self.groups.values(),
            key=lambda g: (g.group_confidence, g.total_sample_count),
            reverse=True
        )
        return sorted_groups[:n]
    
    def get_groups_by_category(self, category: str) -> List[ScoreGroup]:
        """Pobierz grupy po kategorii"""
        result = []
        for group_type, group in self.groups.items():
            if GROUP_DEFINITIONS[group_type]["category"] == category:
                result.append(group)
        return result
    
    def to_dict(self) -> Dict[str, Any]:
        """Serializacja do dict"""
        return {
            "match_id": self.match_id,
            "total_groups": self.total_groups,
            "groups": {gtype.value: group.to_dict() for gtype, group in self.groups.items()},
            "best_group": self.best_group.to_dict() if self.best_group else None,
            "statistics": {
                "by_quality": {
                    q.value: [gt.value for gt in gtypes]
                    for q, gtypes in self.groups_by_quality.items()
                }
            }
        }
    
    def to_json(self, indent: int = 2) -> str:
        """Serializacja do JSON"""
        import json
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)


# =============================================================================
# GROUP BUILDER
# =============================================================================

class ScoreGroupBuilder:
    """
    Budowniczy grup wyników
    
    Odpowiedzialność:
    - Klasyfikacja wyników do grup
    - Obliczanie metryki grupowych
    - Tworzenie ScoreGroup i ScoreGroupCollection
    """
    
    def __init__(self, confidence_engine: Optional[ConfidenceEngine] = None):
        """
        Inicjalizacja
        
        Args:
            confidence_engine: Opcjonalny Confidence Engine
        """
        self.confidence_engine = confidence_engine or ConfidenceEngine()
        logger.info("[ScoreGroupBuilder] Inicjalizacja")
    
    def extract_group_score(self, candidate: ExactScoreCandidate) -> GroupScore:
        """
        Wyekstraktuj GroupScore z ExactScoreCandidate
        
        Args:
            candidate: Kandydat wyniku
            
        Returns:
            GroupScore
        """
        evidence = candidate.evidence
        
        # Wyekstraktuj confidence jako float
        # candidate.confidence może być ConfidenceLevel lub float
        if isinstance(candidate.confidence, ConfidenceLevel):
            # Mapowanie ConfidenceLevel na float
            confidence_map = {
                ConfidenceLevel.CRITICAL: 0.2,
                ConfidenceLevel.LOW: 0.4,
                ConfidenceLevel.MEDIUM: 0.7,
                ConfidenceLevel.HIGH: 0.85,
                ConfidenceLevel.VERY_HIGH: 0.95
            }
            confidence_value = confidence_map.get(candidate.confidence, 0.5)
        else:
            confidence_value = float(candidate.confidence)
        
        # Pobierz world_probability z evidence
        world_pct = evidence.world_weighted_average or 0.0
        
        return GroupScore(
            score=candidate.score,
            confidence=confidence_value,
            market_probability=candidate.market_probability * 100,  # Konwersja na %
            world_probability=world_pct,
            sample_count=evidence.world_max_samples,
            poisson_probability=(candidate.poisson_probability * 100) if hasattr(candidate, 'poisson_probability') else 0.0
        )
    
    def classify_score(self, score: str) -> List[ScoreGroupType]:
        """
        Klasyfikuj wynik do typów grup
        
        Args:
            score: Wynik w formacie "X:Y"
            
        Returns:
            Lista typów grup, do których należy wynik
        """
        home, away = self._parse_score(score)
        groups = []
        
        # HOME_DOMINANCE
        if score in GROUP_DEFINITIONS[ScoreGroupType.HOME_DOMINANCE]["score_patterns"]:
            groups.append(ScoreGroupType.HOME_DOMINANCE)
        
        # AWAY_DOMINANCE  
        if score in GROUP_DEFINITIONS[ScoreGroupType.AWAY_DOMINANCE]["score_patterns"]:
            groups.append(ScoreGroupType.AWAY_DOMINANCE)
        
        # DRAW_LOW_SCORE
        if score in GROUP_DEFINITIONS[ScoreGroupType.DRAW_LOW_SCORE]["score_patterns"]:
            groups.append(ScoreGroupType.DRAW_LOW_SCORE)
        
        # HIGH_SCORE
        if score in GROUP_DEFINITIONS[ScoreGroupType.HIGH_SCORE]["score_patterns"]:
            groups.append(ScoreGroupType.HIGH_SCORE)
        
        # SAFE_RESULTS
        if score in GROUP_DEFINITIONS[ScoreGroupType.SAFE_RESULTS]["score_patterns"]:
            groups.append(ScoreGroupType.SAFE_RESULTS)
        
        # OFFENSIVE
        if score in GROUP_DEFINITIONS[ScoreGroupType.OFFENSIVE]["score_patterns"]:
            groups.append(ScoreGroupType.OFFENSIVE)
        
        return groups
    
    def _parse_score(self, score: str) -> Tuple[int, int]:
        """Parsuj wynik na home:away"""
        parts = score.split(":")
        return int(parts[0]), int(parts[1])
    
    def _get_score_category(self, score: str) -> str:
        """Okrel_category wyniku"""
        home, away = self._parse_score(score)
        
        if home > away:
            return "home"
        elif away > home:
            return "away"
        else:
            return "draw"
    
    def build_group(self, group_type: ScoreGroupType, candidates: List[ExactScoreCandidate]) -> ScoreGroup:
        """
        Utwórz pojedynczą grupę
        
        Args:
            group_type: Typ grupy
            candidates: Lista kandydatów należących do grupy
            
        Returns:
            ScoreGroup
        """
        definition = GROUP_DEFINITIONS[group_type]
        
        group_scores = []
        for candidate in candidates:
            group_scores.append(self.extract_group_score(candidate))
        
        return ScoreGroup(
            group_type=group_type,
            name=definition["name"],
            description=definition["description"],
            scores=group_scores
        )
    
    def build_groups_from_candidates(
        self,
        candidates: List[ExactScoreCandidate]
    ) -> ScoreGroupCollection:
        """
        Utwórz grupy z listy kandydatów
        
        Args:
            candidates: Lista ExactScoreCandidate
            
        Returns:
            ScoreGroupCollection
        """
        #ိわけLesz kandydaci po typach grup
        groups_dict = {gtype: [] for gtype in ScoreGroupType}
        
        for candidate in candidates:
            #lasyfikuj kandidata do grup
            group_types = self.classify_score(candidate.score)
            for gtype in group_types:
                groups_dict[gtype].append(candidate)
        
        # Twórz grupy
        groups = {}
        for gtype, gtype_candidates in groups_dict.items():
            if gtype_candidates:  # Tylko niepuste grupy
                group = self.build_group(gtype, gtype_candidates)
                groups[gtype] = group
        
        # Utwórz kolekcję
        collection = ScoreGroupCollection(
            match_id=candidates[0].evidence.score if candidates else "unknown",
            groups=groups
        )
        
        return collection
    
    def build_groups_from_knowledge(
        self,
        knowledge: ExactScoreKnowledge
    ) -> ScoreGroupCollection:
        """
        Utwórz grupy z ExactScoreKnowledge
        
        Args:
            knowledge: Obiekt ExactScoreKnowledge
            
        Returns:
            ScoreGroupCollection
        """
        return self.build_groups_from_candidates(knowledge.candidates)
    
    def build_groups(
        self,
        match_id: str,
        candidates: Optional[List[ExactScoreCandidate]] = None,
        knowledge: Optional[ExactScoreKnowledge] = None
    ) -> ScoreGroupCollection:
        """
        Główna funkcja - utwórz grupy dla meczu
        
        Args:
            match_id: Identyfikator meczu
            candidates: Opcjonalna lista kandydatów
            knowledge: Opcjonalny ExactScoreKnowledge
            
        Returns:
            ScoreGroupCollection
        """
        if knowledge:
            return self.build_groups_from_knowledge(knowledge)
        
        if candidates:
            return self.build_groups_from_candidates(candidates)
        
        # Jeśli nic nie podano, spróbuj pobrać dane
        # To jest fallback - w rzeczywistości należy dostarczyć dane
        raise ValueError("Musisz podać candidates lub knowledge")
    
    def build_balanced_group(
        self,
        candidates: List[ExactScoreCandidate],
        threshold: float = 0.7
    ) -> Optional[ScoreGroup]:
        """
        Utwórz grupę BALANCED_SCORE z wyników o najwyższej zgodności
        
        Args:
            candidates: Lista kandydatów
            threshold: Minimalny confidence do włączenia
            
        Returns:
            ScoreGroup lub None
        """
        # Mapowanie ConfidenceLevel na float
        confidence_map = {
            ConfidenceLevel.CRITICAL: 0.2,
            ConfidenceLevel.LOW: 0.4,
            ConfidenceLevel.MEDIUM: 0.7,
            ConfidenceLevel.HIGH: 0.85,
            ConfidenceLevel.VERY_HIGH: 0.95
        }
        
        # Filtrowanie wyników z wysokim confidence
        high_confidence_candidates = [
            c for c in candidates 
            if confidence_map.get(c.confidence, 0.0) >= threshold
        ]
        
        if not high_confidence_candidates:
            return None
        
        # Mapowanie ConfidenceLevel na float
        confidence_map = {
            ConfidenceLevel.CRITICAL: 0.2,
            ConfidenceLevel.LOW: 0.4,
            ConfidenceLevel.MEDIUM: 0.7,
            ConfidenceLevel.HIGH: 0.85,
            ConfidenceLevel.VERY_HIGH: 0.95
        }
        
        # Sortuj po confidence (malejąco)
        sorted_candidates = sorted(
            high_confidence_candidates,
            key=lambda c: confidence_map.get(c.confidence, 0.0),
            reverse=True
        )
        
        # Pobierz top 3 wyniki
        top_candidates = sorted_candidates[:3]
        
        definition = GROUP_DEFINITIONS[ScoreGroupType.BALANCED_SCORE]
        group_scores = [self.extract_group_score(c) for c in top_candidates]
        
        return ScoreGroup(
            group_type=ScoreGroupType.BALANCED_SCORE,
            name=definition["name"],
            description=definition["description"],
            scores=group_scores
        )
    
    def rank_groups(
        self,
        collection: ScoreGroupCollection
    ) -> ScoreGroupCollection:
        """
        Posortuj grupy po group_confidence
        
        Args:
            collection: ScoreGroupCollection do posortowania
            
        Returns:
            ScoreGroupCollection (z zaktualizowanym rankingiem)
        """
        # Ranking jest już obliczany w __post_init__, ale możemy wymusić ponowne sortowanie
        sorted_groups = sorted(
            collection.groups.values(),
            key=lambda g: (g.group_confidence, g.total_sample_count),
            reverse=True
        )
        
        for rank, group in enumerate(sorted_groups, 1):
            group.rank = rank
        
        collection._rank_groups()
        return collection
    
    def get_best_groups(
        self,
        match_id: str,
        n: int = 3
    ) -> List[ScoreGroup]:
        """
        Pobierz N najlepszych grup dla meczu
        
        Args:
            match_id: Identyfikator meczu
            n: Liczba grup do zwrócenia
            
        Returns:
            Lista ScoreGroup
        """
        # Tutaj powinniśmy użyć ExactScoreKnowledge, ale uprościmy
        # W rzeczywistości należy zintegrować z pełnym systemem
        
        # Na razie zwracamy zestaw domyślny (do implementacji z danymi rzeczywistymi)
        all_candidates = []  # Powinno być pobrane z ExactScoreKnowledge
        collection = self.build_groups(match_id, candidates=all_candidates)
        return collection.get_best_groups(n)


# =============================================================================
# FUNKCJE API
# =============================================================================

def build_groups(
    candidates: List[ExactScoreCandidate]
) -> ScoreGroupCollection:
    """
    Funkcja wygodna - utwórz grupy z kandydatów
    
    Args:
        candidates: Lista ExactScoreCandidate
        
    Returns:
        ScoreGroupCollection
    """
    builder = ScoreGroupBuilder()
    return builder.build_groups_from_candidates(candidates)


def rank_groups(
    collection: ScoreGroupCollection
) -> ScoreGroupCollection:
    """
    Funkcja wygodna - posortuj grupy
    
    Args:
        collection: ScoreGroupCollection
        
    Returns:
        ScoreGroupCollection (posortowana)
    """
    builder = ScoreGroupBuilder()
    return builder.rank_groups(collection)


def get_best_groups(
    candidates: List[ExactScoreCandidate],
    n: int = 3
) -> List[ScoreGroup]:
    """
    Funkcja wygodna - pobierz N najlepszych grup
    
    Args:
        candidates: Lista ExactScoreCandidate
        n: Liczba grup
        
    Returns:
        Lista ScoreGroup
    """
    builder = ScoreGroupBuilder()
    collection = builder.build_groups_from_candidates(candidates)
    return collection.get_best_groups(n)


def build_balanced_group(
    candidates: List[ExactScoreCandidate],
    threshold: float = 0.7
) -> Optional[ScoreGroup]:
    """
    Funkcja wygodna - utwórz grupę BALANCED_SCORE
    
    Args:
        candidates: Lista ExactScoreCandidate
        threshold: Minimalny confidence
        
    Returns:
        ScoreGroup lub None
    """
    builder = ScoreGroupBuilder()
    return builder.build_balanced_group(candidates, threshold)


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    # Enums
    'ScoreGroupType',
    'GroupQuality',
    
    # Models  
    'GroupScore',
    'ScoreGroup',
    'ScoreGroupCollection',
    
    # Builder
    'ScoreGroupBuilder',
    
    # Functions
    'build_groups',
    'rank_groups',
    'get_best_groups',
    'build_balanced_group',
    
    # Config
    'GROUP_DEFINITIONS',
    'GROUP_CONFIDENCE_WEIGHTS'
]

print(f"[SCORE_GROUP_BUILDER] Moduł załadowany - ETAP 5.2.9.x")
