"""
SSI V5 Exact Score Engine - World Score Comparator
==================================================

ETAP: 5.2.9.x - Porównywanie wyników na różnych poziomach WORLD

Odpowiedzialność:
- Porównanie statystyk wyników między level_1, level_2 i full_group
- Obliczanie trendów i stabilności wyników
- Określanie mocy dowodu dla poszczególnych wyników
- Tworzenie rankingów zgodności między poziomami

Cel:
Porównanie trzech perspektyw:
- LEVEL 1: Szeroka historia (największa próbka)
- LEVEL 2: Bardziej podobne mecze (średnia próbka)
- FULL GROUP: Najbardziej dokładna grupa (najmniejsza próbka)

Nie wybierać automatycznie najlepszego, ale:
- Tworzyć ranking zgodności
- Określać stabilność (trend_strength)
- Wskazywać rozbieżności między poziomami

Nie wolno traktować full_group jako zawsze najlepszego!
Przykład: full_group z 5 meczów nie jest wiarygodny.

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

from typing import Dict, List, Optional, Any, Tuple
from dataclasses import dataclass, field
from enum import Enum
import logging
import math

from .models import VALID_SCORES, ScoreEvidence, WorldLevelEvidence, create_world_level_evidence
from .score_space_generator import ScoreSpaceGenerator, ExactScoreSpace, ScoreLevelData

# Konfiguracja logowania
logger = logging.getLogger(__name__)


# Poziomy stabilności
class TrendStrength(Enum):
    """Poziomy stabilności trendu"""
    VERY_WEAK = "VERY_WEAK"      # Duże rozbieżności, mała próbka
    WEAK = "WEAK"                # Rozbieżności, średnia próbka
    MODERATE = "MODERATE"        # Niskie rozbieżności lub mała próbka
    STRONG = "STRONG"            # Małe rozbieżności, duża próbka
    VERY_STRONG = "VERY_STRONG"  # Zgodność, duża próbka


# Typy zgodności
class ConsistencyType(Enum):
    """Typy zgodności między poziomami"""
    PERFECT = "PERFECT"          # Wszystkie poziomy wskazują ten sam trend
    INCREASING = "INCREASING"    # Wynik rośnie z poziomem (full > level_2 > level_1)
    DECREASING = "DECREASING"    # Wynik maleje z poziomem (full < level_2 < level_1)
    MIXED = "MIXED"              # Brak jasnego trendu
    VOLATILE = "VOLATILE"        # Duże wahania między poziomami


@dataclass
class ScoreConsistency:
    """
    Zgodność wyniku między poziomami WORLD
    
    Analizuje jak wynik zachowuje się na różnych poziomach:
    - level_1, level_2, full_group
    - Uwzględnia wielkość próbek
    - Określa trend i stabilność
    """
    
    score: str  # Analizowany wynik (np. "1:1")
    
    # Procentowe wartości na każdym poziomie
    level_1_percentage: Optional[float] = None
    level_2_percentage: Optional[float] = None
    full_group_percentage: Optional[float] = None
    
    # Liczba przypadków na każdym poziomie
    level_1_samples: int = 0
    level_2_samples: int = 0
    full_group_samples: int = 0
    
    # Średnia ważona (z uwzględnieniem sample_weight)
    weighted_average: float = 0.0
    
    # Typ zgodności
    consistency_type: ConsistencyType = ConsistencyType.MIXED
    
    # Poziom stabilności
    trend_strength: TrendStrength = TrendStrength.VERY_WEAK
    
    # Różnice między poziomami (w punktach procentowych)
    diff_level1_level2: float = 0.0
    diff_level2_full: float = 0.0
    diff_level1_full: float = 0.0
    
    # Maksymalna różnica
    max_difference: float = 0.0
    
    # Odchylenie standardowe (miara zmienności)
    std_deviation: float = 0.0
    
    def __post_init__(self):
        """Obliczenia parametryczne"""
        self._calculate_differences()
        self._calculate_weighted_average()
        self._determine_consistency_type()
        self._determine_trend_strength()
        self._calculate_std_deviation()
    
    def _calculate_differences(self):
        """Oblicz różnice między poziomami"""
        levels = [
            ("level_1", self.level_1_percentage, self.level_1_samples),
            ("level_2", self.level_2_percentage, self.level_2_samples),
            ("full_group", self.full_group_percentage, self.full_group_samples)
        ]
        
        valid_levels = [(name, pct) for name, pct, _ in levels if pct is not None]
        
        if len(valid_levels) >= 2:
            # Znajdź pary
            for i in range(len(valid_levels)):
                for j in range(i + 1, len(valid_levels)):
                    name1, pct1 = valid_levels[i]
                    name2, pct2 = valid_levels[j]
                    
                    diff = abs(pct1 - pct2)
                    
                    if name1 == "level_1" and name2 == "level_2":
                        self.diff_level1_level2 = diff
                    elif name1 == "level_2" and name2 == "full_group":
                        self.diff_level2_full = diff
                    elif name1 == "level_1" and name2 == "full_group":
                        self.diff_level1_full = diff
                    
                    self.max_difference = max(self.max_difference, diff)
    
    def _calculate_weighted_average(self):
        """Oblicz średnią ważoną z uwzględnieniem wielkości próbek"""
        total_weight = self.level_1_samples + self.level_2_samples + self.full_group_samples
        
        if total_weight == 0:
            self.weighted_average = 0.0
            return
        
        weighted_sum = 0.0
        
        if self.level_1_percentage is not None:
            weighted_sum += self.level_1_percentage * self.level_1_samples
        if self.level_2_percentage is not None:
            weighted_sum += self.level_2_percentage * self.level_2_samples
        if self.full_group_percentage is not None:
            weighted_sum += self.full_group_percentage * self.full_group_samples
        
        self.weighted_average = weighted_sum / total_weight
    
    def _determine_consistency_type(self):
        """Określ typ zgodności"""
        if not self._has_enough_data():
            self.consistency_type = ConsistencyType.MIXED
            return
        
        # Sprawdź czy wszystkie poziomy są zbliżone
        if self.max_difference < 0.5:  # Różnica < 0.5%
            self.consistency_type = ConsistencyType.PERFECT
            return
        
        # Sprawdź volatility (duże wahania) - wysoki priorytet
        if self.max_difference > 5.0:  # Różnica > 5%
            self.consistency_type = ConsistencyType.VOLATILE
            return
        
        # Sprawdź trend rosnący
        if (self.level_1_percentage is not None and 
            self.level_2_percentage is not None and 
            self.full_group_percentage is not None):
            
            if (self.level_1_percentage < self.level_2_percentage < self.full_group_percentage):
                self.consistency_type = ConsistencyType.INCREASING
                return
            elif (self.level_1_percentage > self.level_2_percentage > self.full_group_percentage):
                self.consistency_type = ConsistencyType.DECREASING
                return
        
        self.consistency_type = ConsistencyType.MIXED
    
    def _determine_trend_strength(self):
        """Określ siłę trendu"""
        if not self._has_enough_data():
            self.trend_strength = TrendStrength.VERY_WEAK
            return
        
        #efiniujemy minimalną próbkę
        min_samples = 100
        
        # Mała próbka = niska pewność
        if self.full_group_samples < min_samples:
            if self.level_2_samples < min_samples:
                self.trend_strength = TrendStrength.VERY_WEAK
                return
            else:
                self.trend_strength = TrendStrength.WEAK
                return
        
        # Duża próbka + mała rozbieżność = duża pewność
        if self.max_difference < 1.0 and self.level_1_samples > 1000:
            self.trend_strength = TrendStrength.VERY_STRONG
        elif self.max_difference < 2.0 and self.level_1_samples > 500:
            self.trend_strength = TrendStrength.STRONG
        elif self.max_difference < 3.0:
            self.trend_strength = TrendStrength.MODERATE
        else:
            self.trend_strength = TrendStrength.WEAK
    
    def _calculate_std_deviation(self):
        """Oblicz odchylenie standardowe"""
        values = []
        if self.level_1_percentage is not None:
            values.append(self.level_1_percentage)
        if self.level_2_percentage is not None:
            values.append(self.level_2_percentage)
        if self.full_group_percentage is not None:
            values.append(self.full_group_percentage)
        
        if len(values) < 2:
            self.std_deviation = 0.0
            return
        
        mean = sum(values) / len(values)
        variance = sum((x - mean) ** 2 for x in values) / len(values)
        self.std_deviation = math.sqrt(variance)
    
    def _has_enough_data(self) -> bool:
        """Sprawdź czy jest wystarczająco danych"""
        return (self.level_1_percentage is not None or 
                self.level_2_percentage is not None or 
                self.full_group_percentage is not None)
    
    def is_stable(self) -> bool:
        """Sprawdź czy wynik jest stabilny"""
        return self.trend_strength in [TrendStrength.STRONG, TrendStrength.VERY_STRONG]
    
    def is_consistent(self) -> bool:
        """Sprawdź czy wynik jest spójny między poziomami"""
        return (self.consistency_type in [ConsistencyType.PERFECT, ConsistencyType.INCREASING, ConsistencyType.DECREASING] and
                self.trend_strength not in [TrendStrength.VERY_WEAK, TrendStrength.WEAK])
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "score": self.score,
            "percentages": {
                "level_1": self.level_1_percentage,
                "level_2": self.level_2_percentage,
                "full_group": self.full_group_percentage
            },
            "samples": {
                "level_1": self.level_1_samples,
                "level_2": self.level_2_samples,
                "full_group": self.full_group_samples
            },
            "weighted_average": self.weighted_average,
            "consistency_type": self.consistency_type.value,
            "trend_strength": self.trend_strength.value,
            "differences": {
                "level1_level2": self.diff_level1_level2,
                "level2_full": self.diff_level2_full,
                "level1_full": self.diff_level1_full,
                "max": self.max_difference
            },
            "std_deviation": self.std_deviation,
            "is_stable": self.is_stable(),
            "is_consistent": self.is_consistent()
        }


@dataclass
class WorldScoreComparison:
    """
    Pełna analiza porównawcza wyników dla meczu
    
    Zawiera:
    - Porównanie dla wszystkich VALID_SCORES
    - Rankingi stabilności i zgodności
    - Statystyki ogólne
    """
    
    match_id: str
    
    # Porównania dla poszczególnych wyników
    score_consistencies: Dict[str, ScoreConsistency] = field(default_factory=dict)
    
    # Rankingi
    most_stable_scores: List[str] = field(default_factory=list)
    most_consistent_scores: List[str] = field(default_factory=list)
    highest_variability_scores: List[str] = field(default_factory=list)
    
    # Statystyki ogólne
    average_stability: float = 0.0
    average_consistency: float = 0.0
    
    def __post_init__(self):
        """Obliczenia i sortowanie"""
        self._calculate_rankings()
        self._calculate_statistics()
    
    def _calculate_rankings(self):
        """Oblicz rankingi"""
        # Sortuj po stabilności
        self.most_stable_scores = sorted(
            self.score_consistencies.keys(),
            key=lambda s: self._get_strength_value(self.score_consistencies[s].trend_strength),
            reverse=True
        )
        
        # Sortuj po zgodności
        self.most_consistent_scores = sorted(
            self.score_consistencies.keys(),
            key=lambda s: self._get_consistency_value(self.score_consistencies[s].consistency_type),
            reverse=True
        )
        
        # Sortuj po zmienności
        self.highest_variability_scores = sorted(
            self.score_consistencies.keys(),
            key=lambda s: self.score_consistencies[s].std_deviation,
            reverse=True
        )
    
    def _get_strength_value(self, strength: TrendStrength) -> int:
        """Konwersja TrendStrength na wartość numeryczną"""
        values = {
            TrendStrength.VERY_WEAK: 1,
            TrendStrength.WEAK: 2,
            TrendStrength.MODERATE: 3,
            TrendStrength.STRONG: 4,
            TrendStrength.VERY_STRONG: 5
        }
        return values.get(strength, 0)
    
    def _get_consistency_value(self, consistency: ConsistencyType) -> int:
        """Konwersja ConsistencyType na wartość numeryczną"""
        values = {
            ConsistencyType.VOLATILE: 1,
            ConsistencyType.MIXED: 2,
            ConsistencyType.DECREASING: 3,
            ConsistencyType.INCREASING: 4,
            ConsistencyType.PERFECT: 5
        }
        return values.get(consistency, 0)
    
    def _calculate_statistics(self):
        """Oblicz statystyki ogólne"""
        if not self.score_consistencies:
            return
        
        total_stability = sum(
            self._get_strength_value(c.trend_strength) 
            for c in self.score_consistencies.values()
        )
        self.average_stability = total_stability / len(self.score_consistencies)
        
        total_consistency = sum(
            self._get_consistency_value(c.consistency_type) 
            for c in self.score_consistencies.values()
        )
        self.average_consistency = total_consistency / len(self.score_consistencies)
    
    def get_top_stable_scores(self, n: int = 5) -> List[str]:
        """Pobierz N najbardziej stabilnych wyników"""
        return self.most_stable_scores[:n]
    
    def get_top_consistent_scores(self, n: int = 5) -> List[str]:
        """Pobierz N najbardziej spójnych wyników"""
        return self.most_consistent_scores[:n]
    
    def get_top_variable_scores(self, n: int = 5) -> List[str]:
        """Pobierz N najbardziej zmiennych wyników"""
        return self.highest_variability_scores[:n]
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do dict"""
        return {
            "match_id": self.match_id,
            "score_consistencies": {s: c.to_dict() for s, c in self.score_consistencies.items()},
            "rankings": {
                "most_stable": self.most_stable_scores,
                "most_consistent": self.most_consistent_scores,
                "highest_variability": self.highest_variability_scores
            },
            "statistics": {
                "average_stability": self.average_stability,
                "average_consistency": self.average_consistency
            }
        }


class WorldScoreComparator:
    """
    Komparator wyników WORLD
    
    Odpowiedzialność:
    - Porównanie statystyk na różnych poziomach
    - Analiza zgodności i stabilności
    - Tworzenie analiz porównawczych
    """
    
    def __init__(self, score_space_generator: Optional[ScoreSpaceGenerator] = None):
        """
        Inicjalizacja komparatora
        
        Args:
            score_space_generator: Opjonalny generator przestrzeni wyników
        """
        self.score_space_generator = score_space_generator or ScoreSpaceGenerator()
        self._comparisons: Dict[str, WorldScoreComparison] = {}
        logger.info(f"[WorldScoreComparator] Inicjalizacja")
    
    def compare_score_across_levels(
        self,
        score: str,
        level_1_data: Optional[ScoreLevelData] = None,
        level_2_data: Optional[ScoreLevelData] = None,
        full_group_data: Optional[ScoreLevelData] = None
    ) -> ScoreConsistency:
        """
        Porównaj wynik na różnych poziomach
        
        Args:
            score: Wynik do porównania
            level_1_data: Dane level_1 (opcjonalne)
            level_2_data: Dane level_2 (opcjonalne)
            full_group_data: Dane full_group (opcjonalne)
            
        Returns:
            ScoreConsistency
        """
        if score not in VALID_SCORES:
            raise ValueError(f"Score {score} not in VALID_SCORES")
        
        level_1_pct = level_1_data.get_score_percentage(score) if level_1_data else None
        level_2_pct = level_2_data.get_score_percentage(score) if level_2_data else None
        full_pct = full_group_data.get_score_percentage(score) if full_group_data else None
        
        level_1_samples = level_1_data.sample_count if level_1_data else 0
        level_2_samples = level_2_data.sample_count if level_2_data else 0
        full_samples = full_group_data.sample_count if full_group_data else 0
        
        return ScoreConsistency(
            score=score,
            level_1_percentage=level_1_pct,
            level_2_percentage=level_2_pct,
            full_group_percentage=full_pct,
            level_1_samples=level_1_samples,
            level_2_samples=level_2_samples,
            full_group_samples=full_samples
        )
    
    def compare_all_scores_for_match(
        self,
        score_space: ExactScoreSpace
    ) -> WorldScoreComparison:
        """
        Porównaj wszystkie wyniki dla jednego meczu
        
        Args:
            score_space: Prestrzeń wyników
            
        Returns:
            WorldScoreComparison
        """
        if score_space.match_id in self._comparisons:
            return self._comparisons[score_space.match_id]
        
        score_consistencies = {}
        
        for score in VALID_SCORES:
            consistency = self.compare_score_across_levels(
                score,
                score_space.level_1,
                score_space.level_2,
                score_space.full_group
            )
            score_consistencies[score] = consistency
        
        comparison = WorldScoreComparison(
            match_id=score_space.match_id,
            score_consistencies=score_consistencies
        )
        
        # Cache
        self._comparisons[score_space.match_id] = comparison
        
        return comparison
    
    def get_level_trends(self, consistency: ScoreConsistency) -> Dict[str, Any]:
        """
        Określ trendy między poziomami
        
        Args:
            consistency: ScoreConsistency do analizy
            
        Returns:
            Dict z analizą trendów
        """
        trends = {
            "increasing": False,
            "decreasing": False,
            "stable": consistency.is_stable(),
            "consistent": consistency.is_consistent(),
            "volatility": consistency.std_deviation
        }
        
        if (consistency.level_1_percentage is not None and 
            consistency.level_2_percentage is not None and 
            consistency.full_group_percentage is not None):
            
            if (consistency.level_1_percentage < consistency.level_2_percentage < consistency.full_group_percentage):
                trends["increasing"] = True
            elif (consistency.level_1_percentage > consistency.level_2_percentage > consistency.full_group_percentage):
                trends["decreasing"] = True
        
        return trends
    
    def get_sample_weight_impact(self, consistency: ScoreConsistency) -> float:
        """
        Oblicz wpływ sample_weight na wiarygodność
        
        Args:
            consistency: ScoreConsistency
            
        Returns:
            Waga wiarygodności (0-1)
        """
        max_sample = max(
            consistency.level_1_samples,
            consistency.level_2_samples,
            consistency.full_group_samples
        )
        
        if max_sample == 0:
            return 0.0
        
        # Im większa próbka, tym wyższa waga
        # Normalizacja do 0-1 (przyjmując, że 5000 to max)
        return min(max_sample / 5000.0, 1.0)
    
    def get_consistency_score(self, consistency: ScoreConsistency) -> float:
        """
        Oblicz ogólny wynik zgodności (0-100)
        
        Args:
            consistency: ScoreConsistency
            
        Returns:
            Wynik zgodności (0-100)
        """
        score = 0.0
        
        # Dodaj punkty za stabilność
        strength_values = {
            TrendStrength.VERY_WEAK: 0,
            TrendStrength.WEAK: 25,
            TrendStrength.MODERATE: 50,
            TrendStrength.STRONG: 75,
            TrendStrength.VERY_STRONG: 100
        }
        score += strength_values.get(consistency.trend_strength, 0) * 0.4
        
        # Dodaj punkty za zgodność
        consistency_values = {
            ConsistencyType.VOLATILE: 0,
            ConsistencyType.MIXED: 25,
            ConsistencyType.DECREASING: 75,
            ConsistencyType.INCREASING: 75,
            ConsistencyType.PERFECT: 100
        }
        score += consistency_values.get(consistency.consistency_type, 0) * 0.3
        
        # Dodaj punkty za sample_weight
        sample_weight = self.get_sample_weight_impact(consistency)
        score += sample_weight * 100 * 0.3
        
        return score
    
    def find_most_reliable_scores(
        self,
        comparison: WorldScoreComparison,
        min_consistency_score: float = 70.0
    ) -> List[str]:
        """
        Znajdź najbardziej wiarygodne wyniki
        
        Args:
            comparison: WorldScoreComparison
            min_consistency_score: Minimalny wynik zgodności
            
        Returns:
            Lista najbardziej wiarygodnych wyników
        """
        reliable_scores = []
        
        for score, consistency in comparison.score_consistencies.items():
            score_value = self.get_consistency_score(consistency)
            if score_value >= min_consistency_score:
                reliable_scores.append(score)
        
        # Sortuj po wyniku zgodności
        reliable_scores.sort(
            key=lambda s: self.get_consistency_score(comparison.score_consistencies[s]),
            reverse=True
        )
        
        return reliable_scores


# =============================================================================
# EXPORTS
# =============================================================================

__all__ = [
    'WorldScoreComparator',
    'WorldScoreComparison',
    'ScoreConsistency',
    'TrendStrength',
    'ConsistencyType',
]

print(f"[WORLD_SCORE_COMPARATOR] Moduł załadowany - ETAP 5.2.9.x")