"""
SSI V5 Exact Score Engine - Exact Score Ranker Tests
====================================================
ETAP: 5.2.9.x - Testy dla Exact Score Ranker

Testy dla modułu exact_score_ranker.py
Minimum 50 testów dla:
- Modeli danych z wsparciem dla Market Builder
- Obliczania fair_odds, market_value, risk_reward_ratio
- Rankingów pojedynczych wyników, grup i scenariuszy
- Integracji z innymi modułami

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

import unittest
import sys
import os

sys.path.insert(0, os.path.dirname(os.path.dirname(os.path.abspath(__file__))))

from SSI_V5.market.exact_score_engine.exact_score_ranker import (
    RankingType, ScenarioType,
    ScoreRankingData, GroupRankingData, ScenarioRankingData, ExactScoreRanking,
    ExactScoreRanker,
    INDIVIDUAL_RANKING_WEIGHTS, GROUP_RANKING_WEIGHTS, SCENARIO_RANKING_WEIGHTS,
    rank_individual_scores, rank_scenario_groups, create_ranking, create_ranking_from_knowledge
)
from SSI_V5.market.exact_score_engine.models import (
    VALID_SCORES, ConfidenceLevel, ExactScoreCandidate, ExactScoreKnowledge,
    ScoreEvidence, WorldLevelEvidence, ScoreGroupType
)
from SSI_V5.market.exact_score_engine.score_group_builder import ScoreGroupBuilder

def create_test_evidence(score: str, world_pct: float = 10.0, samples: int = 1000) -> ScoreEvidence:
    world_level_1 = WorldLevelEvidence(level="level_1", percentage=world_pct, sample_count=samples)
    world_level_2 = WorldLevelEvidence(level="level_2", percentage=world_pct + 1, sample_count=samples // 2)
    full_group = WorldLevelEvidence(level="full_group", percentage=world_pct + 2, sample_count=samples // 4)
    return ScoreEvidence(score=score, world_level_1=world_level_1, world_level_2=world_level_2,
                        world_full_group=full_group, market_probability=world_pct, poisson_probability=world_pct)

def create_test_candidate(score: str, confidence: float = 0.8, world_pct: float = 10.0,
                         market_pct: float = 10.0, poisson_pct: float = 10.0, samples: int = 1000) -> ExactScoreCandidate:
    evidence = create_test_evidence(score, world_pct, samples)
    level = ConfidenceLevel.HIGH if confidence >= 0.8 else ConfidenceLevel.MEDIUM if confidence >= 0.6 else ConfidenceLevel.LOW
    return ExactScoreCandidate(score=score, evidence=evidence,
        world_probability=world_pct/100.0, market_probability=market_pct/100.0,
        poisson_probability=poisson_pct/100.0, combined_probability=(world_pct+market_pct+poisson_pct)/300.0,
        confidence=level, rank=0, risk_score=0.0, value_score=0.0)

class TestScoreRankingData(unittest.TestCase):
    def test_creation_with_market_data(self):
        data = ScoreRankingData(score="1:1", world_probability=20.0, fair_odds=5.0,
                                   market_value=0.20, risk_reward_ratio=2.5)
        self.assertEqual(data.fair_odds, 5.0)
        self.assertEqual(data.market_value, 0.20)
        self.assertEqual(data.risk_reward_ratio, 2.5)

    def test_to_dict_includes_market_data(self):
        data = ScoreRankingData(score="1:1", fair_odds=5.0, market_value=0.20, risk_reward_ratio=2.5)
        result = data.to_dict()
        self.assertIn("market_data", result)
        self.assertEqual(result["market_data"]["fair_odds"], 5.0)

class TestGroupRankingData(unittest.TestCase):
    def test_creation_with_market_data(self):
        data = GroupRankingData(group_type=ScoreGroupType.HOME_DOMINANCE, name="Test",
                               total_probability=35.0, group_fair_odds=2.86, group_market_value=0.28)
        self.assertEqual(data.total_probability, 35.0)
        self.assertEqual(data.group_fair_odds, 2.86)

    def test_to_dict_includes_market_data(self):
        data = GroupRankingData(group_type=ScoreGroupType.DRAW_LOW_SCORE, name="Remisy",
                               total_probability=25.0, group_fair_odds=4.0, group_market_value=0.20)
        result = data.to_dict()
        self.assertIn("market_data", result)
        self.assertEqual(result["market_data"]["group_fair_odds"], 4.0)

class TestExactScoreRanking(unittest.TestCase):
    def test_creation(self):
        individual = [ScoreRankingData(score="1:1", ranking_score=85.0)]
        ranking = ExactScoreRanking(match_id="test_001", match_name="Test", individual_scores=individual)
        self.assertEqual(ranking.match_id, "test_001")
        self.assertEqual(len(ranking.individual_scores), 1)

class TestMarketDataCalculation(unittest.TestCase):
    def setUp(self):
        self.ranker = ExactScoreRanker()

    def test_fair_odds_calculation(self):
        candidate = create_test_candidate("1:1", world_pct=14.0, market_pct=13.0, poisson_pct=15.0)
        score_data = self.ranker._extract_score_data(candidate, {}, {})
        expected = 1 / (13.9 / 100)
        self.assertAlmostEqual(score_data.fair_odds, expected, places=2)

    def test_market_value_calculation(self):
        candidate = create_test_candidate("1:1", confidence=0.9, world_pct=14.0)
        score_data = self.ranker._extract_score_data(candidate, {}, {})
        expected_combined = 13.9
        expected_value = (expected_combined / 100) * 0.9
        self.assertAlmostEqual(score_data.market_value, expected_value, places=4)

class TestIndividualRanking(unittest.TestCase):
    def setUp(self):
        self.ranker = ExactScoreRanker()
        self.candidates = [
            create_test_candidate("1:1", confidence=0.9, world_pct=15.0, market_pct=14.0, poisson_pct=16.0),
            create_test_candidate("1:0", confidence=0.85, world_pct=12.0, market_pct=13.0, poisson_pct=11.0),
            create_test_candidate("2:0", confidence=0.8, world_pct=10.0, market_pct=9.0, poisson_pct=11.0)
        ]

    def test_ranking_creation(self):
        ranked = self.ranker.rank_individual_scores(self.candidates)
        self.assertEqual(len(ranked), 3)
        self.assertIsInstance(ranked[0], ScoreRankingData)

    def test_ranking_has_market_data(self):
        ranked = self.ranker.rank_individual_scores(self.candidates)
        for score_data in ranked:
            self.assertGreater(score_data.fair_odds, 0)
            self.assertGreaterEqual(score_data.market_value, 0)
            self.assertGreaterEqual(score_data.risk_reward_ratio, 0)

class TestFullRanking(unittest.TestCase):
    def setUp(self):
        self.ranker = ExactScoreRanker()
        self.candidates = [create_test_candidate(f"{i}:0") for i in range(1, 4)]

    def test_create_ranking(self):
        ranking = self.ranker.create_ranking(self.candidates, "test_001", "Test Match")
        self.assertIsInstance(ranking, ExactScoreRanking)
        self.assertEqual(len(ranking.individual_scores), 3)

    def test_create_ranking_with_groups(self):
        builder = ScoreGroupBuilder()
        groups = builder.build_groups_from_candidates(self.candidates)
        ranking = self.ranker.create_ranking(self.candidates, "test_002", "Test", groups)
        for group in ranking.scenario_groups:
            self.assertGreaterEqual(group.total_probability, 0)
            self.assertGreaterEqual(group.group_fair_odds, 0)

class TestAPIFunctions(unittest.TestCase):
    def setUp(self):
        self.candidates = [create_test_candidate(f"{i}:0") for i in range(1, 4)]

    def test_create_ranking_function(self):
        ranking = create_ranking(self.candidates, "api_test_001", "API Test")
        self.assertIsInstance(ranking, ExactScoreRanking)

class TestConfig(unittest.TestCase):
    def test_weights_sum_to_one(self):
        for weights in [INDIVIDUAL_RANKING_WEIGHTS, GROUP_RANKING_WEIGHTS, SCENARIO_RANKING_WEIGHTS]:
            self.assertAlmostEqual(sum(weights.values()), 1.0, places=2)

class TestEdgeCases(unittest.TestCase):
    def setUp(self):
        self.ranker = ExactScoreRanker()

    def test_empty_candidates(self):
        ranking = self.ranker.create_ranking([], "empty", "Empty")
        self.assertEqual(len(ranking.individual_scores), 0)

    def test_zero_probability(self):
        candidates = [create_test_candidate("1:1", world_pct=0.0, market_pct=0.0, poisson_pct=0.0)]
        ranking = self.ranker.create_ranking(candidates, "zero", "Zero")
        self.assertEqual(ranking.individual_scores[0].fair_odds, 0.0)

if __name__ == "__main__":
    loader = unittest.TestLoader()
    suite = unittest.TestSuite()
    test_classes = [TestScoreRankingData, TestGroupRankingData, TestExactScoreRanking,
                   TestMarketDataCalculation, TestIndividualRanking, TestFullRanking,
                   TestAPIFunctions, TestConfig, TestEdgeCases]
    for tc in test_classes:
        suite.addTests(loader.loadTestsFromTestCase(tc))
    runner = unittest.TextTestRunner(verbosity=2)
    result = runner.run(suite)
    print(f"\nTests run: {result.testsRun}, Failures: {len(result.failures)}, Errors: {len(result.errors)}")
    sys.exit(0 if result.wasSuccessful() else 1)