"""
SSI V5 Exact Score Engine - Score Space Generator Tests
=======================================================

ETAP: 5.2.9.x - Testy dla Score Space Generator

Testy dla:
- ScoreLevelData
- ExactScoreSpace
- ScoreSpaceGenerator

Minimum 30 testów.

Generated by Mistral Vibe.
Co-Authored-By: Mistral Vibe <vibe@mistral.ai>
"""

import pytest
import os
import json
import tempfile
from pathlib import Path

# Import from parent package
import sys
from pathlib import Path

# Add project root to path
project_root = Path(__file__).parent.parent.parent.parent.parent
sys.path.insert(0, str(project_root))

from SSI_V5.market.exact_score_engine.score_space_generator import (
    ScoreSpaceGenerator,
    ExactScoreSpace,
    ScoreLevelData,
)
from SSI_V5.market.exact_score_engine.models import VALID_SCORES


# =============================================================================
# TEST: ScoreLevelData
# =============================================================================

class TestScoreLevelData:
    """Testy dla modelu ScoreLevelData"""
    
    def test_creation(self):
        """Test: Tworzenie poprawnego obiektu"""
        level_data = ScoreLevelData(
            level="level_1",
            group_name="poziom7",
            sample_count=3448,
            scores={"1:0": 12.18, "1:1": 12.73, "2:0": 6.99}
        )
        
        assert level_data.level == "level_1"
        assert level_data.group_name == "poziom7"
        assert level_data.sample_count == 3448
        assert level_data.scores["1:0"] == 12.18
    
    def test_get_score_percentage(self):
        """Test: Pobieranie procentu dla wyniku"""
        level_data = ScoreLevelData(
            level="level_1",
            group_name="poziom7",
            sample_count=3448,
            scores={"1:0": 12.18, "1:1": 12.73}
        )
        
        assert level_data.get_score_percentage("1:0") == 12.18
        assert level_data.get_score_percentage("2:0") is None
    
    def test_get_score_percentage_missing(self):
        """Test: Pobieranie nieistniejącego wyniku"""
        level_data = ScoreLevelData(
            level="level_1",
            group_name="poziom7",
            sample_count=3448,
            scores={"1:0": 12.18}
        )
        
        assert level_data.get_score_percentage("9:9") is None
    
    def test_validation_negative_sample_count(self):
        """Test: Walidacja - ujemna liczba przypadków"""
        with pytest.raises(ValueError):
            ScoreLevelData(
                level="level_1",
                group_name="poziom7",
                sample_count=-100,
                scores={"1:0": 12.18}
            )
    
    def test_to_dict(self):
        """Test: Konwersja do dict"""
        level_data = ScoreLevelData(
            level="level_1",
            group_name="poziom7",
            sample_count=3448,
            scores={"1:0": 12.18, "1:1": 12.73}
        )
        
        result = level_data.to_dict()
        assert result["level"] == "level_1"
        assert result["group_name"] == "poziom7"
        assert result["samples"] == 3448
        assert result["scores"]["1:0"] == 12.18


# =============================================================================
# TEST: ExactScoreSpace
# =============================================================================

class TestExactScoreSpace:
    """Testy dla modelu ExactScoreSpace"""
    
    @pytest.fixture
    def sample_level_1(self):
        """Przykładowe dane level_1"""
        return ScoreLevelData(
            level="level_1",
            group_name="poziom7",
            sample_count=3448,
            scores={"1:0": 12.18, "1:1": 12.73, "2:0": 6.99}
        )
    
    @pytest.fixture
    def sample_level_2(self):
        """Przykładowe dane level_2"""
        return ScoreLevelData(
            level="level_2",
            group_name="poziom7poziom11",
            sample_count=853,
            scores={"1:0": 13.13, "1:1": 14.39, "2:0": 7.45}
        )
    
    @pytest.fixture
    def sample_full_group(self):
        """Przykładowe dane full_group"""
        return ScoreLevelData(
            level="full_group",
            group_name="poziom7poziom11poziom10",
            sample_count=264,
            scores={"1:0": 11.45, "1:1": 14.39, "2:0": 8.23}
        )
    
    def test_creation_full(self, sample_level_1, sample_level_2, sample_full_group):
        """Test: Tworzenie pełnego obiektu"""
        score_space = ExactScoreSpace(
            match_id="Inhulets Petrove - Polissya II",
            match_group="poziom7poziom11poziom10",
            level_1=sample_level_1,
            level_2=sample_level_2,
            full_group=sample_full_group
        )
        
        assert score_space.match_id == "Inhulets Petrove - Polissya II"
        assert score_space.match_group == "poziom7poziom11poziom10"
        assert score_space.level_1 == sample_level_1
        assert score_space.level_2 == sample_level_2
        assert score_space.full_group == sample_full_group
    
    def test_ensure_valid_scores(self, sample_level_1, sample_level_2, sample_full_group):
        """Test: Uzupełnianie brakujących wyników"""
        # Utworzenie poziomów z niekompletnymi danymi
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1,
            level_2=sample_level_2,
            full_group=sample_full_group
        )
        
        # Sprawdź czy wszystkie VALID_SCORES są obecne
        for level_data in [score_space.level_1, score_space.level_2, score_space.full_group]:
            for score in VALID_SCORES:
                assert score in level_data.scores, f"Brakujący wynik {score} w {level_data.level}"
    
    def test_ensure_valid_scores_adds_missing(self, sample_level_1, sample_level_2, sample_full_group):
        """Test: Dodawanie brakujących wyników z wartością 0.0"""
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1,
            level_2=sample_level_2,
            full_group=sample_full_group
        )
        
        # Sprawdź, że brakujące wyniki mają wartość 0.0
        for score in VALID_SCORES:
            if score not in ["1:0", "1:1", "2:0"]:  # Te są w sample_level_1
                assert score_space.level_1.scores[score] == 0.0
    
    def test_get_levels(self, sample_level_1, sample_level_2, sample_full_group):
        """Test: Pobieranie wszystkich poziomów"""
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1,
            level_2=sample_level_2,
            full_group=sample_full_group
        )
        
        levels = score_space.get_levels()
        assert "level_1" in levels
        assert "level_2" in levels
        assert "full_group" in levels
    
    def test_get_score_across_levels(self, sample_level_1, sample_level_2, sample_full_group):
        """Test: Pobieranie wyniku na wszystkich poziomach"""
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1,
            level_2=sample_level_2,
            full_group=sample_full_group
        )
        
        result = score_space.get_score_across_levels("1:0")
        assert result["level_1"] == 12.18
        assert result["level_2"] == 13.13
        assert result["full_group"] == 11.45
    
    def test_get_score_across_levels_missing_level(self, sample_level_1):
        """Test: Pobieranie wyniku z brakującymi poziomami"""
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1,
            level_2=None,
            full_group=None
        )
        
        result = score_space.get_score_across_levels("1:0")
        assert result["level_1"] == 12.18
        assert result["level_2"] is None
        assert result["full_group"] is None
    
    def test_get_score_across_levels_invalid_score(self, sample_level_1):
        """Test: Pobieranie nieprawidłowego wyniku"""
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1
        )
        
        with pytest.raises(ValueError):
            score_space.get_score_across_levels("5:5")
    
    def test_get_sample_counts(self, sample_level_1, sample_level_2, sample_full_group):
        """Test: Pobieranie liczby przypadków"""
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1,
            level_2=sample_level_2,
            full_group=sample_full_group
        )
        
        counts = score_space.get_sample_counts()
        assert counts["level_1"] == 3448
        assert counts["level_2"] == 853
        assert counts["full_group"] == 264
    
    def test_get_sample_counts_missing_levels(self, sample_level_1):
        """Test: Pobieranie liczby przypadków z brakującymi poziomami"""
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1
        )
        
        counts = score_space.get_sample_counts()
        assert counts["level_1"] == 3448
        assert counts["level_2"] == 0
        assert counts["full_group"] == 0
    
    def test_to_dict(self, sample_level_1, sample_level_2, sample_full_group):
        """Test: Konwersja do dict"""
        score_space = ExactScoreSpace(
            match_id="Test Match",
            match_group="test_group",
            level_1=sample_level_1,
            level_2=sample_level_2,
            full_group=sample_full_group
        )
        
        result = score_space.to_dict()
        assert result["match"] == "Test Match"
        assert result["match_group"] == "test_group"
        assert "levels" in result
        assert "sample_counts" in result


# =============================================================================
# TEST: ScoreSpaceGenerator
# =============================================================================

class TestScoreSpaceGenerator:
    """Testy dla ScoreSpaceGenerator"""
    
    @pytest.fixture
    def sample_world_database(self):
        """Tworzy tymczasową bazę WORLD"""
        world_data = {
            "Inhulets Petrove - Polissya II": {
                "metadata": {
                    "mecz": "Inhulets Petrove - Polissya II",
                    "grupa_kursowa": "poziom7poziom11poziom10"
                },
                "identyfikacja": {
                    "level_1": "poziom7",
                    "level_2": "poziom7poziom11",
                    "full": "poziom7poziom11poziom10"
                },
                "world_analysis": {
                    "level_1": {
                        "poziom": "poziom7",
                        "analiza": {
                            "ilosc_przypadkow": 3448,
                            "wyniki_docelowe": {
                                "1:0": {"ilosc": 420, "procent": 12.18},
                                "2:0": {"ilosc": 241, "procent": 6.99},
                                "3:0": {"ilosc": 119, "procent": 3.45},
                                "2:1": {"ilosc": 315, "procent": 9.14},
                                "3:1": {"ilosc": 132, "procent": 3.83},
                                "3:2": {"ilosc": 85, "procent": 2.47},
                                "0:1": {"ilosc": 285, "procent": 8.27},
                                "0:2": {"ilosc": 149, "procent": 4.32},
                                "0:3": {"ilosc": 96, "procent": 2.78},
                                "1:2": {"ilosc": 238, "procent": 6.90},
                                "1:3": {"ilosc": 73, "procent": 2.12},
                                "2:3": {"ilosc": 80, "procent": 2.32},
                                "0:0": {"ilosc": 281, "procent": 8.15},
                                "1:1": {"ilosc": 439, "procent": 12.73},
                                "2:2": {"ilosc": 180, "procent": 5.22}
                            }
                        }
                    },
                    "level_2": {
                        "poziom": "poziom7poziom11",
                        "analiza": {
                            "ilosc_przypadkow": 853,
                            "wyniki_docelowe": {
                                "1:0": {"ilosc": 112, "procent": 13.13},
                                "2:0": {"ilosc": 68, "procent": 7.97},
                                "1:1": {"ilosc": 123, "procent": 14.39}
                            }
                        }
                    },
                    "full_group": {
                        "poziom": "poziom7poziom11poziom10",
                        "analiza": {
                            "ilosc_przypadkow": 264,
                            "wyniki_docelowe": {
                                "1:0": {"ilosc": 30, "procent": 11.36},
                                "1:1": {"ilosc": 38, "procent": 14.39}
                            }
                        }
                    }
                }
            },
            "Kambodża - Timor Wschodni": {
                "metadata": {"mecz": "Kambodża - Timor Wschodni"},
                "world_analysis": {
                    "level_1": {
                        "poziom": "poziom12",
                        "analiza": {
                            "ilosc_przypadkow": 944,
                            "wyniki_docelowe": {
                                "1:0": {"ilosc": 79, "procent": 8.37},
                                "2:0": {"ilosc": 44, "procent": 4.66}
                            }
                        }
                    }
                }
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False, encoding='utf-8') as f:
            json.dump(world_data, f, ensure_ascii=False)
            f.flush()
            yield f.name
        
        # Cleanup
        try:
            os.unlink(f.name)
        except:
            pass
    
    def test_initialization(self, sample_world_database):
        """Test: Inicjalizacja generatora"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        assert generator.database_path == sample_world_database
        assert not generator.is_loaded()
    
    def test_load_database(self, sample_world_database):
        """Test: Ładowanie bazy WORLD"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        count = generator.load_database()
        
        assert generator.is_loaded()
        assert count == 2  # Dwa mecze w danych testowych
    
    def test_generate_score_space(self, sample_world_database):
        """Test: Generowanie przestrzeni wyników"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        score_space = generator.generate_score_space("Inhulets Petrove - Polissya II")
        
        assert score_space is not None
        assert score_space.match_id == "Inhulets Petrove - Polissya II"
        assert score_space.match_group == "poziom7poziom11poziom10"
        assert score_space.level_1 is not None
        assert score_space.level_2 is not None
        assert score_space.full_group is not None
    
    def test_generate_score_space_not_found(self, sample_world_database):
        """Test: Generowanie dla nieistniejącego meczu"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        score_space = generator.generate_score_space("Non Existent Match")
        assert score_space is None
    
    def test_generate_score_space_caching(self, sample_world_database):
        """Test: Cache'owanie wyników"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        # Pierwsze wywołanie
        score_space1 = generator.generate_score_space("Inhulets Petrove - Polissya II")
        # Drugie wywołanie (powinno być z cache)
        score_space2 = generator.generate_score_space("Inhulets Petrove - Polissya II")
        
        assert score_space1 is score_space2
    
    def test_generate_all_score_spaces(self, sample_world_database):
        """Test: Generowanie wszystkich przestrzeni"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        all_spaces = generator.generate_all_score_spaces()
        
        assert len(all_spaces) == 2
        assert "Inhulets Petrove - Polissya II" in all_spaces
        assert "Kambodża - Timor Wschodni" in all_spaces
    
    def test_get_match_ids(self, sample_world_database):
        """Test: Pobieranie listy meczów"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        match_ids = generator.get_match_ids()
        assert len(match_ids) == 2
        assert "Inhulets Petrove - Polissya II" in match_ids
    
    def test_count(self, sample_world_database):
        """Test: Pobieranie liczby meczów"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        assert generator.count() == 2
    
    def test_auto_load(self, sample_world_database):
        """Test: Automatyczne ładowanie przy pierwszym dostępie"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        
        # Powinno zautomatycznie załadować
        score_space = generator.generate_score_space("Inhulets Petrove - Polissya II")
        assert score_space is not None
        assert generator.is_loaded()
    
    def test_extract_level_data_level_1(self, sample_world_database):
        """Test: Ekstrakcja danych level_1"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        # Pobierz dane analityczne
        match_data = generator._world_data["Inhulets Petrove - Polissya II"]
        world_analysis = match_data["world_analysis"]
        
        level_data = generator._extract_level_data("level_1", world_analysis)
        
        assert level_data is not None
        assert level_data.level == "level_1"
        assert level_data.group_name == "poziom7"
        assert level_data.sample_count == 3448
        assert "1:0" in level_data.scores
        assert level_data.scores["1:0"] == 12.18
    
    def test_extract_level_data_missing_level(self, sample_world_database):
        """Test: Ekstrakcja dla brakującego poziomu"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        # Pobierz dane analityczne
        match_data = generator._world_data["Kambodża - Timor Wschodni"]
        world_analysis = match_data["world_analysis"]
        
        level_data = generator._extract_level_data("full_group", world_analysis)
        
        assert level_data is None  # Brak full_group w danych testowych
    
    def test_filter_valid_scores(self, sample_world_database):
        """Test: Filtrowanie tylko VALID_SCORES"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        score_space = generator.generate_score_space("Inhulets Petrove - Polissya II")
        
        # Sprawdź, że wszystkie wyniki w poziomach są z VALID_SCORES
        for level_data in [score_space.level_1, score_space.level_2, score_space.full_group]:
            if level_data:
                for score in level_data.scores.keys():
                    assert score in VALID_SCORES, f"Nieprawidłowy wynik {score}"
    
    def test_score_space_structure(self, sample_world_database):
        """Test: Struktura ExactScoreSpace"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        score_space = generator.generate_score_space("Inhulets Petrove - Polissya II")
        
        # Sprawdź strukturę
        assert hasattr(score_space, 'match_id')
        assert hasattr(score_space, 'match_group')
        assert hasattr(score_space, 'level_1')
        assert hasattr(score_space, 'level_2')
        assert hasattr(score_space, 'full_group')
    
    def test_get_score_statistics(self, sample_world_database):
        """Test: Pobieranie statystyk dla wyniku"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        statistics = generator.get_score_statistics("1:0")
        
        assert "level_1" in statistics
        assert "level_2" in statistics
        assert "full_group" in statistics
        
        # Level 1 powinien mieć statystyki
        assert len(statistics["level_1"]) > 0
    
    def test_get_score_statistics_invalid_score(self, sample_world_database):
        """Test: Pobieranie statystyk dla nieprawidłowego wyniku"""
        generator = ScoreSpaceGenerator(database_path=sample_world_database)
        generator.load_database()
        
        with pytest.raises(ValueError):
            generator.get_score_statistics("5:5")


# =============================================================================
# TEST: Integration Tests
# =============================================================================

class TestIntegration:
    """Testy integracyjne"""
    
    def test_full_workflow(self):
        """Test: Pełny workflow - od bazy WORLD do ExactScoreSpace"""
        # Użyj prawdziwej bazy WORLD jeśli dostępna
        possible_paths = [
            "WORLD/aktualny/WORLD_MATCH_DATABASE.json",
            os.path.join(os.getcwd(), "WORLD", "aktualny", "WORLD_MATCH_DATABASE.json"),
        ]
        
        database_path = None
        for path in possible_paths:
            if os.path.exists(path):
                database_path = path
                break
        
        if not database_path:
            pytest.skip("WORLD_MATCH_DATABASE.json not found for integration test")
        
        generator = ScoreSpaceGenerator(database_path=database_path)
        count = generator.load_database()
        
        assert count > 0
        
        # Wybierz pierwszy mecz
        match_ids = generator.get_match_ids()
        if match_ids:
            first_match = match_ids[0]
            score_space = generator.generate_score_space(first_match)
            
            assert score_space is not None
            assert score_space.match_id == first_match
            
            # Sprawdź, że ma co najmniej jeden poziom
            levels = score_space.get_levels()
            assert len(levels) > 0
            
            # Sprawdź, że wszystkie VALID_SCORES są obecne
            for score in VALID_SCORES:
                percentages = score_space.get_score_across_levels(score)
                assert any(p is not None for p in percentages.values())


# =============================================================================
# TEST: Edge Cases
# =============================================================================

class TestEdgeCases:
    """Testy dla przypadków brzegowych"""
    
    def test_empty_database(self):
        """Test: Pusta baza danych"""
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False, encoding='utf-8') as f:
            json.dump({}, f)
            f.flush()
            db_path = f.name
            
            try:
                generator = ScoreSpaceGenerator(database_path=db_path)
                count = generator.load_database()
                assert count == 0
                
                match_ids = generator.get_match_ids()
                assert len(match_ids) == 0
            finally:
                try:
                    os.unlink(db_path)
                except:
                    pass
    
    def test_database_without_world_analysis(self):
        """Test: Baza bez world_analysis"""
        world_data = {
            "Test Match": {
                "metadata": {"mecz": "Test Match"}
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False, encoding='utf-8') as f:
            json.dump(world_data, f)
            f.flush()
            db_path = f.name
            
            try:
                generator = ScoreSpaceGenerator(database_path=db_path)
                generator.load_database()
                
                score_space = generator.generate_score_space("Test Match")
                assert score_space is None
            finally:
                try:
                    os.unlink(db_path)
                except:
                    pass
    
    def test_database_without_wyniki_docelowe(self):
        """Test: Baza bez wyników docelowych"""
        world_data = {
            "Test Match": {
                "world_analysis": {
                    "level_1": {
                        "poziom": "poziom1",
                        "analiza": {
                            "ilosc_przypadkow": 100
                        }
                    }
                }
            }
        }
        
        with tempfile.NamedTemporaryFile(mode='w', suffix='.json', delete=False, encoding='utf-8') as f:
            json.dump(world_data, f)
            f.flush()
            db_path = f.name
            
            try:
                generator = ScoreSpaceGenerator(database_path=db_path)
                generator.load_database()
                
                score_space = generator.generate_score_space("Test Match")
                assert score_space is not None
                assert score_space.level_1 is not None
                # ExactScoreSpace automatycznie uzupełnia VALID_SCORES z 0.0
                assert len(score_space.level_1.scores) == len(VALID_SCORES)
                # Wszystkie powinny być 0.0
                for score, percentage in score_space.level_1.scores.items():
                    assert percentage == 0.0
            finally:
                try:
                    os.unlink(db_path)
                except:
                    pass


# =============================================================================
# MAIN
# =============================================================================

if __name__ == "__main__":
    pytest.main([__file__, "-v", "--tb=short"])

print(f"[TEST_SCORE_SPACE_GENERATOR] Testy dla score space generator załadowane - ETAP 5.2.9.x")