# SSI V5 Market Intelligence Layer
# ==================================
#
# ETAP: 5.2.9.x - Exact Score Market Intelligence Foundation
# ETAP: 5.2.6.5 - OddsAggregator and MarketTrendsAnalyzer
# Data: 2026-08-04
#
# Odpowiedzialnosc:
# - OBSERVATION / KNOWLEDGE GENERATION LAYER
# - Analiza rynku bukmacherskiego
# - Budowanie przestrzeni strategii dla zakładów dokładnego wyniku
# - Generowanie wiedzy dla agentów i Strategy Laboratory
# - Agregacja kursów i analiza trendów
#
# ZASADY:
# 1. NIE MODYFIKUJE istniejących modułów (Feedback, Evolution, Trace, Ingestion)
# 2. TYLKO OBSERWACJA - nie decyduje o strategiach
# 3. Dostarcza wiedzę dla kolejnych warstw
#
# Architektura:
# WORLD DATABASE + MARKET ODDS + POISSON -> ExactScoreEngine -> ExactScoreKnowledge
#                                                OddsAggregator -> MarketTrendsAnalyzer
#
# Przepływ:
#   WORLD DATABASE (level_1, level_2, full_group)
#       + MARKET ODDS (kurs_1_koniec, kurs_X_koniec, kurs_2_koniec)
#       + POISSON DIXON COLES
#           ↓
#   exact_score_engine/ (analiza, porównanie, ranking)
#           ↓
#   ExactScoreKnowledge (dla Strategy Laboratory)
#
#   OddsAggregator (agregacja kursów z wielu źródeł)
#       ↓
#   MarketTrendsAnalyzer (analiza trendów, sygnały, predykcje)
#
# Generated by Mistral Vibe.
# Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

from .exact_score_engine import (
    # Models
    ExactScoreCandidate,
    ScoreEvidence,
    ExactScoreKnowledge,
    ConfidenceLevel,
    ScoreGroup,
    ScoreGroupType,
    
    # Constants
    VALID_SCORES,
)

# Import modułu aggregator
try:
    from .aggregator import (
        # OddsAggregator
        OddsSource,
        OddsType,
        MarketType,
        AggregationMethod,
        RawOddsData,
        AggregatedOdds,
        OddsMovement,
        OddsAggregator,
        
        # MarketTrendsAnalyzer
        TrendType,
        MarketCondition,
        SignalType,
        TimeFrame,
        TREND_THRESHOLDS,
        TrendData,
        MarketTrendAnalysis,
        MarketSignal,
        MarketTrendsAnalyzer,
        
        # Module metadata
        __version__ as AGGREGATOR_VERSION,
        __etap__ as AGGREGATOR_ETAP,
        __name__ as AGGREGATOR_NAME
    )
    _aggregator_available = True
except ImportError:
    _aggregator_available = False
    print("[MARKET] Warning: Aggregator submodule not available")

# Wersja modułu
__version__ = "1.1.0"
__etap__ = "5.2.9.x + 5.2.6.5"
__name__ = "SSI_V5_MARKET"

# Eksport publiczny
__all__ = [
    # Exact Score Engine
    'ExactScoreCandidate',
    'ScoreEvidence',
    'ExactScoreKnowledge',
    'ConfidenceLevel',
    'ScoreGroup',
    'ScoreGroupType',
    'VALID_SCORES',
    
    # Aggregator (jeśli dostępny)
    'OddsSource',
    'OddsType',
    'MarketType',
    'AggregationMethod',
    'RawOddsData',
    'AggregatedOdds',
    'OddsMovement',
    'OddsAggregator',
    'TrendType',
    'MarketCondition',
    'SignalType',
    'TimeFrame',
    'TREND_THRESHOLDS',
    'TrendData',
    'MarketTrendAnalysis',
    'MarketSignal',
    'MarketTrendsAnalyzer',
    
    # Metadata
    '__version__',
    '__etap__',
    '__name__'
]

# Inicjalizacja - rejestracja modułu w systemie
print(f"[MARKET] Moduł {__name__} v{__version__} (ETAP {__etap__}) załadowany")
if _aggregator_available:
    print(f"[MARKET] Submoduł Aggregator v{AGGREGATOR_VERSION} (ETAP {AGGREGATOR_ETAP}) załadowany")