# SSI V5 Trace Module - Integration Layer
# =======================================
#
# ETAP: 5.2.6.3 - Prediction Trace Engine Foundation
# Data: 2026-08-04
#
# Warstwa integracyjna pomiedzy Prediction Trace Engine a istniejacymi modułami.
# 
# ZASADA: NIE MODYFIKUJEMY istniejacych modułów (TrustManager, AgentRuntime, Pipeline, etc.)
# Tylko dodajemy mechanizmy do Cooperation z nimi.
#
# Architecture:
# PredictionTraceManager <- (hook) -> WorldEngine
# PredictionTraceManager <- (hook) -> ModelEvaluator  
# PredictionTraceManager <- (hook) -> AgentRuntime
# PredictionTraceManager <- (hook) -> CollectiveManager
# PredictionTraceManager -> StrategyMemory (PREDICTION_HISTORY)
#
# Generated by Mistral Vibe.
# Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

from typing import Dict, List, Any, Optional, Callable
from datetime import datetime
import uuid


class TraceHook:
    """
    Hook do automatycznego tworzenia trace z istniejacych systemow.
    
    Pozwala na podpiecie sie do istniejacych modułów bez ich modyfikacji.
    """
    
    def __init__(self, trace_manager: Any):
        """
        Inicjalizacja hook.
        
        Args:
            trace_manager: Instancja PredictionTraceManager
        """
        self.trace_manager = trace_manager
        self._original_methods = {}
        self._hooks_enabled = True
    
    def enable(self) -> None:
        """Wlacz hooki"""
        self._hooks_enabled = True
    
    def disable(self) -> None:
        """Wylacz hooki"""
        self._hooks_enabled = False
    
    def is_enabled(self) -> bool:
        """Czy hooki sa wlaczone"""
        return self._hooks_enabled


class WorldEngineHook(TraceHook):
    """
    Hook do integracji z WorldEngine.
    
    Taktyka: Zamiast modyfikowac WorldEngine, nadajemy mu zdolność
    do automatycznego przekazywania danych do PredictionTraceManager.
    """
    
    def __init__(self, trace_manager: Any):
        super().__init__(trace_manager)
        self._world_engine = None
    
    def connect_to_world_engine(self, world_engine: Any) -> None:
        """
        Polacz z WorldEngine.
        
        Args:
            world_engine: Instancja WorldEngine
        """
        self._world_engine = world_engine
        
        # Dodaj referencje do trace manager w WorldEngine
        world_engine._trace_manager = self.trace_manager
        
        # Dodaj metody do WorldEngine
        self._add_trace_methods(world_engine)
    
    def _add_trace_methods(self, world_engine: Any) -> None:
        """Dodaj metody trace do WorldEngine"""
        
        def create_trace_on_process(output: Any) -> Any:
            """Automatycznie tworzy trace po procesowaniu"""
            if not self._hooks_enabled:
                return output
            
            # Utworz trace z output
            trace = self.trace_manager.receive_from_world_engine(
                world_engine_output=output,
                cycle_id=getattr(world_engine, 'context', {}).get('cycle_id', None),
                world_version=output.metadata.get('world_version') if hasattr(output, 'metadata') else ''
            )
            
            # Powiaz output z trace
            if trace and hasattr(output, 'metadata'):
                output.metadata['trace_id'] = trace.trace_id
                output.metadata['prediction_trace_created'] = True
            
            return output
        
        # Zapisz oryginalna metode process
        if hasattr(world_engine, 'process') and not hasattr(world_engine, '_original_process'):
            world_engine._original_process = world_engine.process
            
            # Zastap metode
            def traced_process(*args, **kwargs):
                result = world_engine._original_process(*args, **kwargs)
                return create_trace_on_process(result)
            
            world_engine.process = traced_process
        
        # Dodaj metody utylity
        world_engine.create_prediction_trace = lambda output: self.trace_manager.receive_from_world_engine(output)
        world_engine.get_trace_manager = lambda: self.trace_manager


class StrategyLabHook(TraceHook):
    """
    Hook do integracji z Strategy Laboratory.
    """
    
    def __init__(self, trace_manager: Any):
        super().__init__(trace_manager)
        self._strategy_lab = None
    
    def connect_to_strategy_lab(self, strategy_lab: Any) -> None:
        """
        Polacz z StrategyLab.
        
        Args:
            strategy_lab: Instancja StrategyLab
        """
        self._strategy_lab = strategy_lab
        
        # Dodaj referencje do trace manager
        strategy_lab._trace_manager = self.trace_manager
        
        # Dodaj metody integracyjne
        self._add_trace_methods(strategy_lab)
    
    def _add_trace_methods(self, strategy_lab: Any) -> None:
        """Dodaj metody trace do StrategyLab"""
        
        def create_trace_for_experiment(experiment: Any) -> Optional[Any]:
            """Utworz trace dla eksperymentu"""
            if not self._hooks_enabled:
                return None
            
            from .prediction_trace import create_trace_from_strategy_experiment
            
            trace = create_trace_from_strategy_experiment(
                self.trace_manager,
                experiment
            )
            
            # Powiaz eksperyment z trace
            if trace and hasattr(experiment, 'metadata'):
                experiment.metadata['trace_id'] = trace.trace_id
            
            return trace
        
        def save_experiment_with_trace(experiment: Any) -> bool:
            """Zapisz eksperyment i utworz trace"""
            if not self._hooks_enabled:
                return strategy_lab.save_experiment(experiment)
            
            # Utworz trace
            trace = create_trace_for_experiment(experiment)
            
            # Zapisz eksperyment
            result = strategy_lab.save_experiment(experiment)
            
            # Synchronizuj z Strategy Memory
            if trace and result:
                self.trace_manager.sync_trace_to_strategy_memory(trace)
            
            return result
        
        # Zastap save_experiment
        if hasattr(strategy_lab, 'save_experiment') and not hasattr(strategy_lab, '_original_save_experiment'):
            strategy_lab._original_save_experiment = strategy_lab.save_experiment
            strategy_lab.save_experiment = save_experiment_with_trace
        
        # Dodaj metody utylity
        strategy_lab.create_prediction_trace = create_trace_for_experiment
        strategy_lab.get_trace_manager = lambda: self.trace_manager


class AgentRuntimeHook(TraceHook):
    """
    Hook do integracji z AgentRuntime.
    
    Automatycznie tworzy trace gdy agent podejmuje decyzje.
    """
    
    def __init__(self, trace_manager: Any):
        super().__init__(trace_manager)
        self._agent_runtime = None
    
    def connect_to_agent_runtime(self, agent_runtime: Any) -> None:
        """
        Polacz z AgentRuntime (lub pojedynczym agentem).
        
        Args:
            agent_runtime: Instancja AgentRuntime lub agente
        """
        self._agent_runtime = agent_runtime
        
        # Dodaj referencje do trace manager
        agent_runtime._trace_manager = self.trace_manager
        
        # Dodaj metody integracyjne
        self._add_trace_methods(agent_runtime)
    
    def _add_trace_methods(self, agent_runtime: Any) -> None:
        """Dodaj metody trace do AgentRuntime"""
        
        def create_trace_on_decision(decision: Dict[str, Any], agent_id: str) -> Optional[str]:
            """Automatycznie tworzy trace przy dodawaniu decyzji"""
            if not self._hooks_enabled:
                return None
            
            # Pobierz pamięć agenta
            memory = getattr(agent_runtime, 'memory', None)
            if memory is None:
                return None
            
            # Pobierz ostatnia predykcje
            predictions = getattr(memory, 'predictions', [])
            if not predictions:
                return None
            
            # Pobierz ostatnia predykcje
            last_prediction = predictions[-1]
            prediction_id = last_prediction.get('prediction_id', f"pred_{uuid.uuid4().hex[:8]}")
            
            # Utworz trace
            trace = self.trace_manager.create_trace(
                world_version=getattr(agent_runtime, 'world_version', ''),
                model_reference=getattr(agent_runtime, 'model_reference', ''),
                input_features=list(last_prediction.get('features', [])) if isinstance(last_prediction.get('features'), list) else [],
                prediction_result=last_prediction.get('result'),
                prediction_confidence=last_prediction.get('confidence', 0.0),
                metadata={
                    'source': 'agent_decision',
                    'agent_id': agent_id,
                    'decision_id': decision.get('decision_id', '')
                }
            )
            
            # Dodaj decyzje do trace
            if trace and 'decision_id' in decision:
                self.trace_manager.add_trace_decision(
                    trace_id=trace.trace_id,
                    decision_id=decision['decision_id'],
                    agent_id=agent_id,
                    decision_type=decision.get('decision_type', 'unknown'),
                    bet_amount=decision.get('bet_amount'),
                    bet_type=decision.get('bet_type', ''),
                    odds=decision.get('odds'),
                    confidence=decision.get('confidence', 0.0)
                )
            
            return trace.trace_id if trace else None
        
        # Przechwyc add_decision
        if hasattr(agent_runtime, 'memory') and hasattr(agent_runtime.memory, 'add_decision'):
            original_add_decision = agent_runtime.memory.add_decision
            
            def traced_add_decision(decision: Dict[str, Any], timestamp=None):
                decision_id = original_add_decision(decision, timestamp)
                
                # Dodaj trace
                if self._hooks_enabled:
                    agent_id = getattr(agent_runtime, 'agent_id', 'unknown')
                    create_trace_on_decision(decision, agent_id)
                
                return decision_id
            
            agent_runtime.memory.add_decision = traced_add_decision
        
        # Dodaj metody utylity
        agent_runtime.create_trace_from_decision = create_trace_on_decision
        agent_runtime.get_trace_manager = lambda: self.trace_manager


class CollectiveManagerHook(TraceHook):
    """
    Hook do integracji z CollectiveManager.
    
    Automatycznie tworzy trace przy budowaniu konsensusu.
    """
    
    def __init__(self, trace_manager: Any):
        super().__init__(trace_manager)
        self._collective_manager = None

    def connect_to_collective_manager(self, collective_manager: Any) -> None:
        """
        Polacz z CollectiveManager.
        
        Args:
            collective_manager: Instancja CollectiveManager
        """
        self._collective_manager = collective_manager
        
        # Dodaj referencje do trace manager
        collective_manager._trace_manager = self.trace_manager
        
        # Dodaj metody integracyjne
        self._add_trace_methods(collective_manager)
    
    def _add_trace_methods(self, collective_manager: Any) -> None:
        """Dodaj metody trace do CollectiveManager"""
        
        def create_trace_on_consensus(cycle_id: str, collective_decision: Any) -> Optional[str]:
            """Automatycznie tworzy trace przy konsensusie"""
            if not self._hooks_enabled:
                return None
            
            # Pobierz informacje z decyzji
            participating_agents = getattr(collective_decision, 'agents_participated', [])
            consensus_result = getattr(collective_decision, 'consensus_result', {})
            confidence_score = getattr(collective_decision, 'confidence_score', 0.0)
            consensus_type = getattr(collective_decision, 'consensus_type', {}).value if hasattr(getattr(collective_decision, 'consensus_type', None), 'value') else str(getattr(collective_decision, 'consensus_type', ''))
            
            # Znajdz powiazane predykcje
            trace_ids = []
            for agent_id in participating_agents:
                individual_decisions = getattr(collective_decision, 'individual_decisions', {})
                decision = individual_decisions.get(agent_id, {})
                
                # Szukaj trace dla tej decyzji
                traces = self.trace_manager.search_traces(
                    has_decision=True,
                    limit=10
                )
                
                for trace in traces:
                    if trace.decision and trace.decision.decision_id == decision.get('decision_id'):
                        trace_ids.append(trace.trace_id)
                        
                        # Dodaj konsensus do trace
                        self.trace_manager.add_trace_collective(
                            trace_id=trace.trace_id,
                            collective_decision_id=collective_decision.decision_id,
                            consensus_type=consensus_type,
                            confidence_score=confidence_score,
                            participating_agents=participating_agents,
                            consensus_result=consensus_result
                        )
            
            return collective_decision.decision_id if trace_ids else None
        
        # Przechwyc build_consensus
        if hasattr(collective_manager, 'build_consensus') and not hasattr(collective_manager, '_original_build_consensus'):
            original_build_consensus = collective_manager.build_consensus
            
            def traced_build_consensus(cycle_id: str) -> Any:
                result = original_build_consensus(cycle_id)
                
                # Dodaj trace dla konsensusu
                if self._hooks_enabled:
                    create_trace_on_consensus(cycle_id, result)
                
                return result
            
            collective_manager.build_consensus = traced_build_consensus
        
        # Dodaj metody utylity
        collective_manager.create_trace_on_consensus = create_trace_on_consensus
        collective_manager.get_trace_manager = lambda: self.trace_manager


class ModelEvaluatorHook(TraceHook):
    """
    Hook do integracji z ModelEvaluator.
    """
    
    def __init__(self, trace_manager: Any):
        super().__init__(trace_manager)
        self._model_evaluator = None
    
    def connect_to_model_evaluator(self, model_evaluator: Any) -> None:
        """
        Polacz z ModelEvaluator.
        
        Args:
            model_evaluator: Instancja ModelEvaluator
        """
        self._model_evaluator = model_evaluator
        
        # Dodaj referencje do trace manager
        model_evaluator._trace_manager = self.trace_manager
        
        # Dodaj metody integracyjne
        self._add_trace_methods(model_evaluator)
    
    def _add_trace_methods(self, model_evaluator: Any) -> None:
        """Dodaj metody trace do ModelEvaluator"""
        
        def update_traces_with_metrics(model_name: str, evaluation: Dict[str, Any]) -> None:
            """Zaktualizuj trace z nowymi metrykami"""
            if not self._hooks_enabled:
                return
            
            # Znajdz trace dla tego modelu
            traces = self.trace_manager.get_traces_by_model(model_name)
            
            for trace in traces:
                # Zaktualizuj metryki
                self.trace_manager.add_trace_evaluation(
                    trace_id=trace.trace_id,
                    metrics=evaluation
                )
        
        # Przechwyc evaluate_model
        if hasattr(model_evaluator, 'evaluate_model') and not hasattr(model_evaluator, '_original_evaluate_model'):
            original_evaluate_model = model_evaluator.evaluate_model
            
            def traced_evaluate_model(model_name: str, y_true: Any, y_pred: Any, additional_metrics: Dict[str, float] = None) -> Dict[str, Any]:
                result = original_evaluate_model(model_name, y_true, y_pred, additional_metrics)
                
                # Zaktualizuj trace
                if self._hooks_enabled:
                    update_traces_with_metrics(model_name, result)
                
                return result
            
            model_evaluator.evaluate_model = traced_evaluate_model
        
        # Dodaj metody utylity  
        model_evaluator.update_trace_metrics = update_traces_with_metrics
        model_evaluator.get_trace_manager = lambda: self.trace_manager


class TraceIntegrationManager:
    """
    Menadzer integracji trace z calym systemem.
    
    Pozwala na proste podpiecie wszystkich istniejacych modułów
    do Prediction Trace Engine.
    """
    
    def __init__(self, trace_manager: Any = None):
        """
        Inicjalizacja.
        
        Args:
            trace_manager: Instancja PredictionTraceManager (opcjonalnie)
        """
        if trace_manager is None:
            from .prediction_trace import PredictionTraceManager
            self.trace_manager = PredictionTraceManager()
        else:
            self.trace_manager = trace_manager
        
        # Hooki
        self.world_engine_hook = WorldEngineHook(self.trace_manager)
        self.strategy_lab_hook = StrategyLabHook(self.trace_manager)
        self.agent_runtime_hook = AgentRuntimeHook(self.trace_manager)
        self.collective_manager_hook = CollectiveManagerHook(self.trace_manager)
        self.model_evaluator_hook = ModelEvaluatorHook(self.trace_manager)
    
    def connect_all(
        self,
        world_engine: Any = None,
        strategy_lab: Any = None,
        agent_runtime: Any = None,
        collective_manager: Any = None,
        model_evaluator: Any = None
    ) -> None:
        """
        Polacz wszystko.
        
        Args:
            world_engine: Instancja WorldEngine
            strategy_lab: Instancja StrategyLab
            agent_runtime: Instancja AgentRuntime
            collective_manager: Instancja CollectiveManager
            model_evaluator: Instancja ModelEvaluator
        """
        if world_engine:
            self.world_engine_hook.connect_to_world_engine(world_engine)
        
        if strategy_lab:
            self.strategy_lab_hook.connect_to_strategy_lab(strategy_lab)
        
        if agent_runtime:
            self.agent_runtime_hook.connect_to_agent_runtime(agent_runtime)
        
        if collective_manager:
            self.collective_manager_hook.connect_to_collective_manager(collective_manager)
        
        if model_evaluator:
            self.model_evaluator_hook.connect_to_model_evaluator(model_evaluator)
    
    def connect_from_pipeline(self, pipeline: Any) -> None:
        """
        Polacz z Pipeline (pobiera wszystkie komponenty z pipeline).
        
        Args:
            pipeline: Instancja Pipeline
        """
        # Pobierz komponenty z pipeline
        world_engine = getattr(pipeline, '_world_engine', None)
        strategy_lab = None  # StrategyLab nie jest czescia Pipeline
        agent_runtime = getattr(pipeline, '_agent_runtime_manager', None)
        collective_manager = getattr(pipeline, '_collective_manager', None)
        model_evaluator = None  # ModelEvaluator nie jest czescia Pipeline
        
        # Polacz
        self.connect_all(
            world_engine=world_engine,
            strategy_lab=strategy_lab,
            agent_runtime=agent_runtime,
            collective_manager=collective_manager,
            model_evaluator=model_evaluator
        )
        
        # Dodaj referencje do trace manager w pipeline
        pipeline._trace_manager = self.trace_manager
    
    def enable_all_hooks(self) -> None:
        """Wlacz wszystkie hooki"""
        self.world_engine_hook.enable()
        self.strategy_lab_hook.enable()
        self.agent_runtime_hook.enable()
        self.collective_manager_hook.enable()
        self.model_evaluator_hook.enable()
    
    def disable_all_hooks(self) -> None:
        """Wylacz wszystkie hooki"""
        self.world_engine_hook.disable()
        self.strategy_lab_hook.disable()
        self.agent_runtime_hook.disable()
        self.collective_manager_hook.disable()
        self.model_evaluator_hook.disable()
    
    def get_trace_manager(self) -> Any:
        """Pobierz trace manager"""
        return self.trace_manager
    
    def integrate_with_strategy_memory(self, strategy_memory_manager: Any) -> None:
        """
        Zintegruj z StrategyMemoryManager.
        
        Args:
            strategy_memory_manager: Instancja StrategyMemoryManager
        """
        self.trace_manager.integrate_with_strategy_memory(strategy_memory_manager)


# ============================================================================
# FUNKCJE UTYLITY DLA ŁATWEJ INTEGRACJI
# ============================================================================

def create_integration_manager(
    world_engine: Any = None,
    strategy_lab: Any = None,
    agent_runtime: Any = None,
    collective_manager: Any = None,
    model_evaluator: Any = None,
    strategy_memory_manager: Any = None
) -> TraceIntegrationManager:
    """
    Fabryka: Utworz i skonfiguruj TraceIntegrationManager.
    
    Args:
        world_engine: Instancja WorldEngine
        strategy_lab: Instancja StrategyLab
        agent_runtime: Instancja AgentRuntime
        collective_manager: Instancja CollectiveManager
        model_evaluator: Instancja ModelEvaluator
        strategy_memory_manager: Instancja StrategyMemoryManager
        
    Returns:
        Skonfigurowany TraceIntegrationManager
    """
    integration_manager = TraceIntegrationManager()
    
    # Pod 자체가 komponenty
    integration_manager.connect_all(
        world_engine=world_engine,
        strategy_lab=strategy_lab,
        agent_runtime=agent_runtime,
        collective_manager=collective_manager,
        model_evaluator=model_evaluator
    )
    
    # Integracja z Strategy Memory
    if strategy_memory_manager:
        integration_manager.integrate_with_strategy_memory(strategy_memory_manager)
    
    return integration_manager


def quick_setup(
    world_engine: Any = None,
    strategy_lab: Any = None,
    pipeline: Any = None
) -> TraceIntegrationManager:
    """
    Szybka konfiguracja z minimalnymi parametrami.
    
    Args:
        world_engine: Instancja WorldEngine (opcjonalnie)
        strategy_lab: Instancja StrategyLab (opcjonalnie)
        pipeline: Instancja Pipeline (opcjonalnie - pobiera z niej komponenty)
        
    Returns:
        Skonfigurowany TraceIntegrationManager
    """
    integration_manager = TraceIntegrationManager()
    
    if pipeline:
        integration_manager.connect_from_pipeline(pipeline)
    else:
        integration_manager.connect_all(
            world_engine=world_engine,
            strategy_lab=strategy_lab
        )
    
    # Wlacz hooki
    integration_manager.enable_all_hooks()
    
    return integration_manager


if __name__ == "__main__":
    # Test integracji
    from .prediction_trace import PredictionTraceManager
    
    print("Testing Trace Integration Module...")
    
    # Utworz trace manager
    trace_manager = PredictionTraceManager()
    
    # Utworz integration manager
    integration = TraceIntegrationManager(trace_manager)
    
    print("✅ Trace Integration Manager created successfully")
    print(f"  - Trace Manager: {trace_manager}")
    print(f"  - WorldEngine Hook: {integration.world_engine_hook}")
    print(f"  - StrategyLab Hook: {integration.strategy_lab_hook}")
    print(f"  - AgentRuntime Hook: {integration.agent_runtime_hook}")
    print(f"  - CollectiveManager Hook: {integration.collective_manager_hook}")
    print(f"  - ModelEvaluator Hook: {integration.model_evaluator_hook}")
