# SSI V5 Evolution Module - Strategy Genome
# ========================================
#
# ETAP: 5.2.7 - Strategy Evolution Engine Foundation
# Data: 2026-08-04
#
# Odpowiedzialnosc:
# - Reprezentacja strategii jako obiektu ewolucyjnego
# - Podstawa dla mutacji i selekcji
# - Zachowanie genomu strategii
#
# ZASADY:
# 1. NIE modyfikuje aktywnych strategii produkcyjnych
# 2. TYLKO DO UZYTKU W EVOLUTION ENGINE
# 3. Powiazany z StrategyMemory (tylko odczyt)
# 4. NIE wplywa na: TrustManager, AgentRuntime, Pipeline, WorldEngine, CollectiveManager
# 5. Izolowane srodowisko laboratoryjne
#
# Architektura:
# StrategyMemory -> StrategyGenome -> MutationEngine -> EvolutionRecord
#
# Generated by Mistral Vibe.
# Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional, Union, Tuple
from datetime import datetime
import json
import uuid
import hashlib
import copy
from enum import Enum
import random


class GeneType(Enum):
    """Typy genow w genomie strategii"""
    PARAMETER = "parameter"      # Parametr liczbowy (float/int)
    RULE = "rule"               # Reguła logiczna (bool/string)
    FEATURE = "feature"         # Funkcja cechy (feature name)
    CONSTRAINT = "constraint"   # Ograniczenie (min/max value)
    WEIGHT = "weight"           # Waga cechy lub parametru
    THRESHOLD = "threshold"     # Próg decyzji
    OPERATOR = "operator"       # Operator logiczny (>, <, ==, etc.)


class MutationType(Enum):
    """Typy mutacji"""
    NONE = "none"               # Brak mutacji
    RANDOM = "random"           # Losowa mutacja
    SMALL = "small"             # Mala mutacja (小 modification)
    LARGE = "large"             # Duza mutacja (significant change)
    CROSSOVER = "crossover"      # Krzyzowanie z inna strategia
    COPY = "copy"               # Kopia z innej strategii


@dataclass
class Gene:
    """
    Pojedynczy gen w genomie strategii.
    
    Reprezentuje jeden parametr, regułę lub cechę,
    która może ulec mutacji.
    """
    name: str                          # Nazwa genu
    gene_type: GeneType = GeneType.PARAMETER  # Typ genu
    value: Any = None                  # Wartosc genu
    min_value: Optional[float] = None # Minimalna wartosc (dla typow liczbowych)
    max_value: Optional[float] = None # Maksymalna wartosc (dla typow liczbowych)
    possible_values: Optional[List[Any]] = None  # Mozliwe wartosci (dla typow enum/string)
    mutation_rate: float = 0.1        # Prawdopodobienstwo mutacji (0.0 - 1.0)
    mutation_step: float = 0.1       # Krok mutacji (dla typow liczbowych)
    is_active: bool = True            # Czy gen jest aktywny
    description: str = ""              # Opis genu
    
    def __post_init__(self):
        """Inicjalizacja po utworzeniu"""
        if self.possible_values is None:
            self.possible_values = []
    
    def mutate(self, mutation_type: MutationType = MutationType.RANDOM) -> 'Gene':
        """
        Mutuje gen według zadanej strategii.
        
        Args:
            mutation_type: Typ mutacji
            
        Returns:
            Gene: Nowy zmutowany gen
        """
        if mutation_type == MutationType.NONE:
            return copy.deepcopy(self)
        
        # Utworz kopie
        new_gene = copy.deepcopy(self)
        
        # Losowa mutacja
        if mutation_type == MutationType.RANDOM:
            new_gene._random_mutate()
        elif mutation_type == MutationType.SMALL:
            new_gene._small_mutate()
        elif mutation_type == MutationType.LARGE:
            new_gene._large_mutate()
        
        return new_gene
    
    def _random_mutate(self) -> None:
        """Losowa mutacja"""
        if not self.is_active:
            return
        
        if self.gene_type == GeneType.PARAMETER:
            if isinstance(self.value, (int, float)):
                if self.possible_values:
                    self.value = random.choice(self.possible_values)
                elif self.min_value is not None and self.max_value is not None:
                    self.value = random.uniform(self.min_value, self.max_value)
                else:
                    # Domyslna mutacja
                    if isinstance(self.value, float):
                        self.value += random.uniform(-0.5, 0.5) * self.mutation_step
                    else:
                        self.value += random.randint(-1, 1) * int(self.mutation_step)
        
        elif self.gene_type == GeneType.RULE:
            if self.possible_values:
                self.value = random.choice(self.possible_values)
            else:
                self.value = not self.value if isinstance(self.value, bool) else self.value
        
        elif self.gene_type == GeneType.FEATURE:
            # Losowo wlacz/wylacz ceche
            self.is_active = random.choice([True, False])
        
        elif self.gene_type == GeneType.CONSTRAINT:
            if isinstance(self.value, (int, float)):
                if self.min_value is not None and self.max_value is not None:
                    self.value = random.uniform(self.min_value, self.max_value)
        
        elif self.gene_type == GeneType.WEIGHT:
            if isinstance(self.value, (int, float)):
                new_weight = self.value * (1 + random.uniform(-0.2, 0.2))
                if self.min_value is not None:
                    new_weight = max(self.min_value, new_weight)
                if self.max_value is not None:
                    new_weight = min(self.max_value, new_weight)
                self.value = new_weight
        
        elif self.gene_type == GeneType.THRESHOLD:
            if isinstance(self.value, (int, float)):
                new_threshold = self.value + random.uniform(-0.1, 0.1)
                if self.min_value is not None:
                    new_threshold = max(self.min_value, new_threshold)
                if self.max_value is not None:
                    new_threshold = min(self.max_value, new_threshold)
                self.value = new_threshold
        
        elif self.gene_type == GeneType.OPERATOR:
            if self.possible_values:
                self.value = random.choice(self.possible_values)
    
    def _small_mutate(self) -> None:
        """Mala mutacja (subtelna zmiana)"""
        if not self.is_active:
            return
        
        if isinstance(self.value, (int, float)):
            step = self.mutation_step * 0.5  # Mniejszy krok
            if isinstance(self.value, float):
                new_value = self.value + random.uniform(-step, step)
            else:
                new_value = self.value + random.randint(-1, 1) * int(step)
            
            if self.min_value is not None:
                new_value = max(self.min_value, new_value)
            if self.max_value is not None:
                new_value = min(self.max_value, new_value)
            
            self.value = new_value
    
    def _large_mutate(self) -> None:
        """Duza mutacja (istotna zmiana)"""
        if not self.is_active:
            return
        
        if isinstance(self.value, (int, float)):
            step = self.mutation_step * 2.0  # Wiekszy krok
            if isinstance(self.value, float):
                new_value = self.value + random.uniform(-step, step)
            else:
                new_value = self.value + random.randint(-2, 2) * int(step)
            
            if self.min_value is not None:
                new_value = max(self.min_value, new_value)
            if self.max_value is not None:
                new_value = min(self.max_value, new_value)
            
            self.value = new_value
        elif self.gene_type == GeneType.RULE and isinstance(self.value, bool):
            self.value = not self.value  # Zmien swoja wartosc
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do slownika"""
        return {
            'name': self.name,
            'gene_type': self.gene_type.value,
            'value': self.value,
            'min_value': self.min_value,
            'max_value': self.max_value,
            'possible_values': list(self.possible_values) if self.possible_values else [],
            'mutation_rate': self.mutation_rate,
            'mutation_step': self.mutation_step,
            'is_active': self.is_active,
            'description': self.description
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Gene':
        """Utworzenie z slownika"""
        return cls(
            name=data.get('name', ''),
            gene_type=GeneType(data.get('gene_type', 'parameter')),
            value=data.get('value'),
            min_value=data.get('min_value'),
            max_value=data.get('max_value'),
            possible_values=data.get('possible_values', []),
            mutation_rate=data.get('mutation_rate', 0.1),
            mutation_step=data.get('mutation_step', 0.1),
            is_active=data.get('is_active', True),
            description=data.get('description', '')
        )


@dataclass
class StrategyGenome:
    """
    Genom strategii - kompletna reprezentacja ewolucyjna.
    
    Zawiera wszystkie parametry, reguły i cechy potrzebne do:
    - Tworzenia nowych wariantów strategii
    - Obliczania fitness score
    - Zachowania historii mutacji
    
    Powiazany z:
    - StrategyMemory (source strategy)
    - EvolutionRecord (historia mutacji)
    - StrategyPopulation (czesc populacji)
    """
    
    # ===== IDENTYFIKACJA =====
    genome_id: str = field(default_factory=lambda: f"genome_{uuid.uuid4().hex[:12]}")
    
    # ===== POWIAZANIA =====
    strategy_id: str = ""              # ID oryginalnej strategii
    strategy_version: str = "1.0.0"   # Wersja strategii
    parent_genome_id: Optional[str] = None  # ID genomu rodzica (dla ewolucji)
    
    # ===== GENY =====
    genes: Dict[str, Gene] = field(default_factory=dict)  # Slownik genow (name -> Gene)
    
    # ===== PARAMETRY =====
    parameters: Dict[str, Any] = field(default_factory=dict)  # Zserializowane parametry
    rules: Dict[str, Any] = field(default_factory=dict)      # Reguły strategii
    features: List[str] = field(default_factory=list)        # Lista uzywanych cech
    constraints: Dict[str, Any] = field(default_factory=dict)  # Ograniczenia
    
    # ===== METADANE =====
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # ===== FITNESS =====
    fitness_score: float = 0.0            # Ocena sprawności (0.0 - 1.0 lub wyzsza)
    fitness_metrics: Dict[str, float] = field(default_factory=dict)  # Szczególowe metryki
    
    # ===== STATUS =====
    created_time: datetime = field(default_factory=datetime.now)
    last_mutated: Optional[datetime] = None  # Ostatnia mutacja
    mutation_count: int = 0               # Liczba mutacji
    
    # ===== METODY =====
    
    def add_gene(self, gene: Gene) -> None:
        """Dodaje gen do genomu"""
        self.genes[gene.name] = gene
        # Zaktualizuj parametry
        self._sync_parameters()
    
    def add_parameter(self, name: str, value: Any, gene_type: GeneType = GeneType.PARAMETER,
                     min_value: Optional[float] = None, max_value: Optional[float] = None,
                     possible_values: Optional[List[Any]] = None) -> None:
        """
        Dodaje nowy parametr jako gen.
        
        Args:
            name: Nazwa parametru
            value: Wartosc poczatkowa
            gene_type: Typ genu
            min_value: Minimalna wartosc
            max_value: Maksymalna wartosc
            possible_values: Mozliwe wartosci
        """
        gene = Gene(
            name=name,
            gene_type=gene_type,
            value=value,
            min_value=min_value,
            max_value=max_value,
            possible_values=possible_values or []
        )
        self.genes[name] = gene
        self.parameters[name] = value
        self._sync_parameters()
    
    def get_gene(self, name: str) -> Optional[Gene]:
        """Pobiera gen po nazwie"""
        return self.genes.get(name)
    
    def remove_gene(self, name: str) -> bool:
        """Usuwa gen z genomu"""
        if name in self.genes:
            del self.genes[name]
            if name in self.parameters:
                del self.parameters[name]
            return True
        return False
    
    def _sync_parameters(self) -> None:
        """Synchronizuje parametry z genami"""
        for gene_name, gene in self.genes.items():
            if gene.is_active:
                self.parameters[gene_name] = gene.value
            elif gene_name in self.parameters:
                del self.parameters[gene_name]
    
    def calculate_genome_id(self) -> str:
        """
        Generuje deterministyczne genome_id z parametrow.
        
        Returns:
            str: Unikalne genome_id
        """
        # Sortuj geny dla determinizmu
        gene_data = []
        for name, gene in sorted(self.genes.items()):
            gene_data.append(f"{name}:{gene.value}:{gene.gene_type.value}")
        
        genes_str = "|".join(gene_data)
        combined = f"{self.strategy_id}:{self.strategy_version}:{genes_str}"
        return f"genome_{hashlib.sha256(combined.encode('utf-8')).hexdigest()[:12]}"
    
    def mutate(self, mutation_type: MutationType = MutationType.RANDOM, 
               mutation_rate: Optional[float] = None) -> 'StrategyGenome':
        """
        Tworzy zmutowana kopie genomu.
        
        Args:
            mutation_type: Typ mutacji
            mutation_rate: Opcjonalne prawdopodobienstwo mutacji
            
        Returns:
            StrategyGenome: Nowy zmutowany genom
        """
        # Utworz kopie
        new_genome = copy.deepcopy(self)
        
        # Ustaw nowy parent
        new_genome.genome_id = f"genome_{uuid.uuid4().hex[:12]}"
        new_genome.parent_genome_id = self.genome_id
        new_genome.mutation_count = self.mutation_count + 1
        new_genome.last_mutated = datetime.now()
        
        # Mutuj geny
        rate = mutation_rate if mutation_rate is not None else 0.3
        
        for gene_name, gene in new_genome.genes.items():
            # Decyduj czy mutowac
            if random.random() < rate and gene.is_active:
                gene.mutate(mutation_type)
        
        # Zaktualizuj parametry
        new_genome._sync_parameters()
        
        return new_genome
    
    def crossover(self, other: 'StrategyGenome', crossover_rate: float = 0.5) -> Tuple['StrategyGenome', 'StrategyGenome']:
        """
        Krzyzowanie z innym genomem.
        
        Args:
            other: Inny genom do krzyzowania
            crossover_rate: Prawdopodobienstwo wymiany genu
            
        Returns:
            Tuple[StrategyGenome, StrategyGenome]: Dwie nowy genom (potomkowie)
        """
        # Utworz dvě kopie
        child1 = copy.deepcopy(self)
        child2 = copy.deepcopy(other)
        
        # Ustaw nowy parent
        child1.genome_id = f"genome_{uuid.uuid4().hex[:12]}"
        child1.parent_genome_id = self.genome_id
        child1.mutation_count = self.mutation_count + 1
        child1.last_mutated = datetime.now()
        
        child2.genome_id = f"genome_{uuid.uuid4().hex[:12]}"
        child2.parent_genome_id = other.genome_id
        child2.mutation_count = other.mutation_count + 1
        child2.last_mutated = datetime.now()
        
        # Wymien geny
        all_gene_names = set(self.genes.keys()) | set(other.genes.keys())
        
        for gene_name in all_gene_names:
            if random.random() < crossover_rate:
                # Wymien geny miedzy dziecmi
                if gene_name in self.genes and gene_name in other.genes:
                    child1.genes[gene_name] = copy.deepcopy(other.genes[gene_name])
                    child2.genes[gene_name] = copy.deepcopy(self.genes[gene_name])
        
        # Zaktualizuj parametry
        child1._sync_parameters()
        child2._sync_parameters()
        
        return child1, child2
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do slownika"""
        return {
            'genome_id': self.genome_id,
            'strategy_id': self.strategy_id,
            'strategy_version': self.strategy_version,
            'parent_genome_id': self.parent_genome_id,
            'genes': {name: gene.to_dict() for name, gene in self.genes.items()},
            'parameters': copy.deepcopy(self.parameters),
            'rules': copy.deepcopy(self.rules),
            'features': copy.deepcopy(self.features),
            'constraints': copy.deepcopy(self.constraints),
            'metadata': copy.deepcopy(self.metadata),
            'fitness_score': self.fitness_score,
            'fitness_metrics': copy.deepcopy(self.fitness_metrics),
            'created_time': self.created_time.isoformat() if self.created_time else None,
            'last_mutated': self.last_mutated.isoformat() if self.last_mutated else None,
            'mutation_count': self.mutation_count
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'StrategyGenome':
        """Utworzenie z slownika"""
        genome = cls(
            genome_id=data.get('genome_id', f"genome_{uuid.uuid4().hex[:12]}"),
            strategy_id=data.get('strategy_id', ''),
            strategy_version=data.get('strategy_version', '1.0.0'),
            parent_genome_id=data.get('parent_genome_id'),
            parameters=copy.deepcopy(data.get('parameters', {})),
            rules=copy.deepcopy(data.get('rules', {})),
            features=copy.deepcopy(data.get('features', [])),
            constraints=copy.deepcopy(data.get('constraints', {})),
            metadata=copy.deepcopy(data.get('metadata', {})),
            fitness_score=data.get('fitness_score', 0.0),
            fitness_metrics=copy.deepcopy(data.get('fitness_metrics', {})),
            mutation_count=data.get('mutation_count', 0)
        )
        
        # Zaladuj geny
        for gene_name, gene_data in data.get('genes', {}).items():
            gene = Gene.from_dict(gene_data)
            genome.genes[gene_name] = gene
        
        # Zaladuj czasy
        if data.get('created_time'):
            genome.created_time = datetime.fromisoformat(data['created_time'])
        if data.get('last_mutated'):
            genome.last_mutated = datetime.fromisoformat(data['last_mutated'])
        
        return genome
    
    def to_json(self) -> str:
        """Konwersja do JSON"""
        return json.dumps(self.to_dict(), indent=2, default=str, ensure_ascii=False)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'StrategyGenome':
        """Utworzenie z JSON"""
        data = json.loads(json_str)
        return cls.from_dict(data)
    
    def from_strategy_experiment(self, strategy_experiment: Any) -> None:
        """
        Inicjalizuje genom z StrategyExperiment.
        
        Args:
            strategy_experiment: Obiekt StrategyExperiment z StrategyLab
        """
        self.strategy_id = strategy_experiment.strategy_id
        self.strategy_version = strategy_experiment.strategy_version
        
        # Dodaj parametry jako geny
        for param_name, param_value in strategy_experiment.strategy_parameters.items():
            self.add_parameter(
                name=param_name,
                value=param_value,
                gene_type=GeneType.PARAMETER
            )
        
        # Dodaj_features
        if strategy_experiment.features:
            self.features = list(strategy_experiment.features)
        
        # Dodaj execution_context jako metadata
        if strategy_experiment.execution_context:
            self.metadata.update(strategy_experiment.execution_context)
