# SSI V5 Evolution Module - Strategy Population
# ===============================================
#
# ETAP: 5.2.7 - Strategy Evolution Engine Foundation
# Data: 2026-08-04
#
# Odpowiedzialnosc:
# - Zarzadzanie populacja genomow strategii
# - Selekcja najlepszych strategii
# - Ranking i ewolucja populacji
# - Zachowanie historii generacji
#
# ZASADY:
# 1. TYLKO DO UZYTKU W EVOLUTION ENGINE
# 2. NIE modyfikuje aktywnych strategii produkcyjnych
# 3. TYLKO odczyt z: StrategyMemory, CouponLaboratory, PredictionTrace
# 4. NIE wplywa na: TrustManager, AgentRuntime, Pipeline, WorldEngine, CollectiveManager
# 5. Izolowane srodowisko laboratoryjne
#
# Architektura:
# StrategyPopulation -> [StrategyGenome] -> StrategyMutationEngine
#
# Generated by Mistral Vibe.
# Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional, Callable, Tuple
from datetime import datetime
import json
import uuid
import copy
import random
from threading import RLock
import logging

from .strategy_genome import StrategyGenome, GeneType, MutationType
from .evolution_record import EvolutionRecord, EvolutionType, EvolutionStatus, EvolutionHistory


@dataclass
class PopulationStats:
    """Statystyki populacji"""
    size: int = 0                       # Rozmiar populacji
    best_fitness: float = 0.0           # Najlepszy fitness
    worst_fitness: float = float('inf')  # Najgorszy fitness
    avg_fitness: float = 0.0            # Sredni fitness
    total_fitness: float = 0.0          # Suma fitness
    fitness_std: float = 0.0            # Odchylenie standardowe fitness
    diversity: float = 0.0              # Roznorodnosc populacji
    generation: int = 0                 # Numer generacji
    
    def to_dict(self) -> Dict[str, float]:
        """Konwersja do slownika"""
        return {
            'size': self.size,
            'best_fitness': self.best_fitness,
            'worst_fitness': self.worst_fitness,
            'avg_fitness': self.avg_fitness,
            'total_fitness': self.total_fitness,
            'fitness_std': self.fitness_std,
            'diversity': self.diversity,
            'generation': self.generation
        }


@dataclass
class SelectionResult:
    """Wynik selekcji"""
    selected: List[str] = field(default_factory=list)      # ID wybranych genomow
    rejected: List[str] = field(default_factory=list)     # ID odrzuconych genomow
    elite: List[str] = field(default_factory=list)       # ID elit (najlepsze)
    metrics: Dict[str, Any] = field(default_factory=dict)  # Metryki selekcji
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do slownika"""
        return {
            'selected': copy.deepcopy(self.selected),
            'rejected': copy.deepcopy(self.rejected),
            'elite': copy.deepcopy(self.elite),
            'metrics': copy.deepcopy(self.metrics)
        }


class StrategyPopulation:
    """
    Populacja strategii - zarzadza kolekcja genomow.
    
    Odpowiedzialnosc:
    - Przechowywanie genomow
    - Selekcja najlepszych
    - Ranking populacji
    - Zachowanie historii generacji
    
    ZASADA: TYLKO LABORATORIUM - nie wplywa na produkcje.
    """
    
    def __init__(self, population_id: Optional[str] = None):
        """
        Inicjalizacja populacji.
        
        Args:
            population_id: Unikalne ID populacji
        """
        self.population_id = population_id or f"pop_{uuid.uuid4().hex[:8]}"
        
        # Genomy w populacji
        self.genomes: Dict[str, StrategyGenome] = {}  # genome_id -> StrategyGenome
        
        # Historia generacji
        self.generation: int = 0
        self.generations: List[List[str]] = []  # Lista generacji ([genome_id, ...])
        
        # Historia selekcji
        self.selection_history: List[SelectionResult] = []
        
        # Statystyki
        self.stats: PopulationStats = PopulationStats()
        
        # Lock dla thread-safety
        self._lock = RLock()
        
        # Konfiguracja logowania
        self._setup_logging()
    
    def _setup_logging(self) -> None:
        """Konfiguracja logowania"""
        self.logger = logging.getLogger('StrategyPopulation')
        if not self.logger.handlers:
            handler = logging.StreamHandler()
            handler.setFormatter(logging.Formatter(
                '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
            ))
            self.logger.addHandler(handler)
            self.logger.setLevel(logging.INFO)
    
    # ===== METODY PUBLICZNE =====
    
    def add_genome(self, genome: StrategyGenome) -> bool:
        """
        Dodaje genom do populacji.
        
        Args:
            genome: Genom do dodania
            
        Returns:
            bool: True jesli dodano pomyslnie
        """
        with self._lock:
            if genome.genome_id in self.genomes:
                self.logger.warning(f"Genom {genome.genome_id} juz istnieje w populacji")
                return False
            
            self.genomes[genome.genome_id] = genome
            self.logger.info(f"Dodano genom {genome.genome_id} do populacji {self.population_id}")
            return True
    
    def add_genomes(self, genomes: List[StrategyGenome]) -> int:
        """
        Dodaje wiele genomow do populacji.
        
        Args:
            genomes: Lista genomow
            
        Returns:
            int: Liczba dodanych genomow
        """
        with self._lock:
            count = 0
            for genome in genomes:
                if self.add_genome(genome):
                    count += 1
            
            self.logger.info(f"Dodano {count}/{len(genomes)} genomow do populacji")
            return count
    
    def remove_genome(self, genome_id: str) -> bool:
        """
        Usuwa genom z populacji.
        
        Args:
            genome_id: ID genomu do usuniecia
            
        Returns:
            bool: True jesli usunieto pomyslnie
        """
        with self._lock:
            if genome_id not in self.genomes:
                return False
            
            del self.genomes[genome_id]
            self.logger.info(f"Usunieto genom {genome_id} z populacji")
            return True
    
    def get_genome(self, genome_id: str) -> Optional[StrategyGenome]:
        """Pobiera genom po ID"""
        with self._lock:
            return copy.deepcopy(self.genomes.get(genome_id))
    
    def get_all_genomes(self) -> List[StrategyGenome]:
        """Pobiera wszystkie genom'y"""
        with self._lock:
            return [copy.deepcopy(g) for g in self.genomes.values()]
    
    def get_size(self) -> int:
        """Pobiera rozmiar populacji"""
        with self._lock:
            return len(self.genomes)
    
    def get_best_genomes(self, limit: int = 5) -> List[StrategyGenome]:
        """
        Pobiera najlepsze genom'y po fitness.
        
        Args:
            limit: Maksymalna liczba genomow
            
        Returns:
            List[StrategyGenome]: Posortowana lista genomow (od najlepszego)
        """
        with self._lock:
            sorted_genomes = sorted(
                self.genomes.values(),
                key=lambda g: g.fitness_score,
                reverse=True
            )
            return [copy.deepcopy(g) for g in sorted_genomes[:limit]]
    
    def get_worst_genomes(self, limit: int = 5) -> List[StrategyGenome]:
        """
        Pobiera najgorsze genom'y po fitness.
        
        Args:
            limit: Maksymalna liczba genomow
            
        Returns:
            List[StrategyGenome]: Posortowana lista genomow (od najgorszego)
        """
        with self._lock:
            sorted_genomes = sorted(
                self.genomes.values(),
                key=lambda g: g.fitness_score
            )
            return [copy.deepcopy(g) for g in sorted_genomes[:limit]]
    
    def rank_genomes(self) -> List[Tuple[str, float]]:
        """
        Rankuje genom'y po fitness.
        
        Returns:
            List[Tuple[genome_id, fitness_score]]: Posortowana lista rankingu
        """
        with self._lock:
            ranked = [
                (genome_id, genome.fitness_score)
                for genome_id, genome in self.genomes.items()
            ]
            ranked.sort(key=lambda x: x[1], reverse=True)
            return ranked
    
    def select_best(self, limit: int = 5, fitness_threshold: Optional[float] = None) -> SelectionResult:
        """
        Wybiera najlepsze genom'y.
        
        Args:
            limit: Maksymalna liczba genomow do wyboru
            fitness_threshold: Minimalny poziom fitness
            
        Returns:
            SelectionResult: Wynik selekcji
        """
        with self._lock:
            result = SelectionResult()
            
            if not self.genomes:
                return result
            
            # Sortuj po fitness
            sorted_genomes = sorted(
                self.genomes.items(),
                key=lambda x: x[1].fitness_score,
                reverse=True
            )
            
            # Wybierz najlepsze
            for genome_id, genome in sorted_genomes:
                if fitness_threshold is not None and genome.fitness_score < fitness_threshold:
                    result.rejected.append(genome_id)
                elif len(result.selected) < limit:
                    result.selected.append(genome_id)
                    result.elite.append(genome_id)  # Present acteur le plus
                else:
                    result.rejected.append(genome_id)
            
            # Ustaw metryki
            result.metrics = {
                'total': len(self.genomes),
                'selected': len(result.selected),
                'rejected': len(result.rejected),
                'avg_fitness': self.stats.avg_fitness,
                'best_fitness': self.stats.best_fitness,
                'threshold': fitness_threshold or 0.0
            }
            
            # Zapisz w historii
            self.selection_history.append(result)
            
            self.logger.info(f"Wybrano {len(result.selected)} najlepszych genomow z {len(self.genomes)}")
            return result
    
    def select_random(self, limit: int = 5) -> SelectionResult:
        """
        Wybiera losowe genom'y.
        
        Args:
            limit: Liczba genomow do wyboru
            
        Returns:
            SelectionResult: Wynik selekcji
        """
        with self._lock:
            result = SelectionResult()
            
            if not self.genomes:
                return result
            
            genome_ids = list(self.genomes.keys())
            
            # Losuj genomy
            if limit >= len(genome_ids):
                result.selected = copy.deepcopy(genome_ids)
            else:
                result.selected = random.sample(genome_ids, limit)
            
            # Reszta to rejected
            result.rejected = [gid for gid in genome_ids if gid not in result.selected]
            
            # Ustaw metryki
            result.metrics = {
                'total': len(self.genomes),
                'selected': len(result.selected),
                'rejected': len(result.rejected),
                'method': 'random'
            }
            
            # Zapisz w historii
            self.selection_history.append(result)
            
            self.logger.info(f"Wybrano losowo {len(result.selected)} genomow")
            return result
    
    def select_tournament(self, tournament_size: int = 3, num_winners: int = 2) -> SelectionResult:
        """
        Wybiera genom'y metoda turnieju.
        
        Args:
            tournament_size: Rozmiar turnieju
            num_winners: Liczba zwyciezcow w kazdym turnieju
            
        Returns:
            SelectionResult: Wynik selekcji
        """
        with self._lock:
            result = SelectionResult()
            
            if not self.genomes:
                return result
            
            genome_ids = list(self.genomes.keys())
            selected_set = set()
            
            # Wybierzվում przez turnieje
            while len(selected_set) < min(num_winners * len(genome_ids), len(genome_ids)):
                # Losuj uczestnikow turnieju
                tournament = random.sample(genome_ids, min(tournament_size, len(genome_ids)))
                
                # Znajdz najlepszych w turnieju
                tournament_genomes = [self.genomes[gid] for gid in tournament]
                tournament_genomes.sort(key=lambda g: g.fitness_score, reverse=True)
                
                # Wybierz zwyciezcow
                for winner in tournament_genomes[:num_winners]:
                    selected_set.add(winner.genome_id)
            
            result.selected = list(selected_set)
            result.rejected = [gid for gid in genome_ids if gid not in selected_set]
            
            # Ustaw metryki
            result.metrics = {
                'total': len(self.genomes),
                'selected': len(result.selected),
                'rejected': len(result.rejected),
                'tournament_size': tournament_size,
                'method': 'tournament'
            }
            
            # Zapisz w historii
            self.selection_history.append(result)
            
            self.logger.info(f"Wybrano {len(result.selected)} genomow metoda turnieju")
            return result
    
    def next_generation(self, 
                       selection_method: str = "best",
                       elite_count: int = 2,
                       mutation_rate: Optional[float] = None) -> List[StrategyGenome]:
        """
        Tworzy nowa generacje z obecnej populacji.
        
        Args:
            selection_method: Metoda selekcji ('best', 'random', 'tournament')
            elite_count: Liczba elit (najlepszych zachowywanych)
            mutation_rate: Prawdopodobienstwo mutacji
            
        Returns:
            List[StrategyGenome]: Nowa generacja genomow
        """
        with self._lock:
            # Zapisz biezaca generacje
            current_genome_ids = list(self.genomes.keys())
            self.generations.append(current_genome_ids)
            self.generation += 1
            
            # Wybierz najlepsze (elite)
            if selection_method == "best":
                selection = self.select_best(limit=elite_count)
            elif selection_method == "random":
                selection = self.select_random(limit=elite_count)
            elif selection_method == "tournament":
                selection = self.select_tournament(num_winners=elite_count)
            else:
                selection = self.select_best(limit=elite_count)
            
            # Nowa generacja zaczyna sie od elit
            new_generation = []
            for elite_id in selection.elite:
                elite_genome = self.genomes[elite_id]
                new_generation.append(copy.deepcopy(elite_genome))
            
            # Reszte populacji uzupelnij mutowanymi elitami
            while len(new_generation) < len(self.genomes):
                # Wybierz losowego rodzica z elit
                parent_id = random.choice(selection.elite)
                parent = self.genomes[parent_id]
                
                # Zmutuj
                child = parent.mutate(
                    mutation_type=MutationType.RANDOM,
                    mutation_rate=mutation_rate or 0.3
                )
                new_generation.append(child)
            
            # Zaktualizuj populacje
            new_genome_ids = [g.genome_id for g in new_generation]
            self.genomes = {g.genome_id: g for g in new_generation}
            
            self.logger.info(f"Utworzono nowa generacje {self.generation} z {len(new_generation)} genomow")
            
            # Zaktualizuj statystyki
            self._calculate_stats()
            
            return new_generation
    
    def calculate_diversity(self) -> float:
        """
        Oblicza roznorodnosc populacji.
        
        Metryka: Srednia róznica między genomami
        
        Returns:
            float: Poziom roznorodnosci (0.0 - 1.0)
        """
        if len(self.genomes) <= 1:
            return 0.0
        
        # Porównaj parametry genomow
        all_genomes = list(self.genomes.values())
        total_differences = 0
        comparisons = 0
        
        for i in range(len(all_genomes)):
            for j in range(i + 1, len(all_genomes)):
                diff = self._calculate_genome_difference(all_genomes[i], all_genomes[j])
                total_differences += diff
                comparisons += 1
        
        return (total_differences / comparisons) if comparisons > 0 else 0.0
    
    def _calculate_genome_difference(self, genome1: StrategyGenome, genome2: StrategyGenome) -> float:
        """Oblicza roznice entre dwooma genomami"""
        differences = 0
        max_diff = 0
        
        # Porównaj parametry
        all_keys = set(genome1.parameters.keys()) | set(genome2.parameters.keys())
        
        for key in all_keys:
            val1 = genome1.parameters.get(key, 0)
            val2 = genome2.parameters.get(key, 0)
            
            if isinstance(val1, (int, float)) and isinstance(val2, (int, float)):
                # Normalizuj i oblicz roznice
                max_val = max(abs(val1), abs(val2), 1.0)
                diff = abs(val1 - val2) / max_val
                differences += diff
                max_diff += 1
        
        return (differences / max_diff) if max_diff > 0 else 0.0
    
    def _calculate_stats(self) -> None:
        """Oblicza statystyki populacji"""
        with self._lock:
            if not self.genomes:
                self.stats = PopulationStats(generation=self.generation)
                return
            
            fitness_values = [g.fitness_score for g in self.genomes.values()]
            
            self.stats = PopulationStats(
                size=len(self.genomes),
                best_fitness=max(fitness_values),
                worst_fitness=min(fitness_values),
                avg_fitness=sum(fitness_values) / len(fitness_values),
                total_fitness=sum(fitness_values),
                fitness_std=self._calculate_std(fitness_values),
                diversity=self.calculate_diversity(),
                generation=self.generation
            )
    
    def _calculate_std(self, values: List[float]) -> float:
        """Oblicza odchylenie standardowe"""
        if len(values) < 2:
            return 0.0
        
        mean = sum(values) / len(values)
        variance = sum((x - mean) ** 2 for x in values) / len(values)
        return variance ** 0.5
    
    def get_stats(self) -> PopulationStats:
        """Pobiera aktualne statystyki"""
        with self._lock:
            self._calculate_stats()
            return copy.deepcopy(self.stats)
    
    def get_selection_history(self, limit: int = 10) -> List[SelectionResult]:
        """Pobiera historiê selekcji"""
        with self._lock:
            return [copy.deepcopy(r) for r in self.selection_history[-limit:]]
    
    def get_generations(self, limit: int = 10) -> List[List[str]]:
        """Pobiera historiê generacji"""
        with self._lock:
            return [copy.deepcopy(gen) for gen in self.generations[-limit:]]
    
    def clear(self) -> None:
        """Czysci populacje"""
        with self._lock:
            self.genomes.clear()
            self.generations.clear()
            self.selection_history.clear()
            self.generation = 0
            self.stats = PopulationStats()
            
            self.logger.info("Wyczyszczono populacje")
    
    def clone(self) -> 'StrategyPopulation':
        """
        Tworzy kopie populacji.
        
        Returns:
            StrategyPopulation: Nowa populacja z kopiami genomow
        """
        with self._lock:
            new_population = StrategyPopulation()
            new_population.genomes = {gid: copy.deepcopy(g) for gid, g in self.genomes.items()}
            new_population.generation = self.generation
            new_population.generations = copy.deepcopy(self.generations)
            new_population.selection_history = copy.deepcopy(self.selection_history)
            new_population.stats = copy.deepcopy(self.stats)
            return new_population
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do slownika"""
        return {
            'population_id': self.population_id,
            'genomes': {gid: g.to_dict() for gid, g in self.genomes.items()},
            'generation': self.generation,
            'generations': [copy.deepcopy(gen) for gen in self.generations],
            'selection_history': [s.to_dict() for s in self.selection_history],
            'stats': self.stats.to_dict()
        }
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'StrategyPopulation':
        """Utworzenie z slownika"""
        population = cls(population_id=data.get('population_id'))
        
        for gid, genome_data in data.get('genomes', {}).items():
            genome = StrategyGenome.from_dict(genome_data)
            population.genomes[gid] = genome
        
        population.generation = data.get('generation', 0)
        population.generations = copy.deepcopy(data.get('generations', []))
        
        for selection_data in data.get('selection_history', []):
            selection = SelectionResult(
                selected=selection_data.get('selected', []),
                rejected=selection_data.get('rejected', []),
                elite=selection_data.get('elite', []),
                metrics=copy.deepcopy(selection_data.get('metrics', {}))
            )
            population.selection_history.append(selection)
        
        if 'stats' in data:
            population.stats = PopulationStats(**data['stats'])
        
        return population
    
    def to_json(self) -> str:
        """Konwersja do JSON"""
        return json.dumps(self.to_dict(), indent=2, default=str, ensure_ascii=False)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'StrategyPopulation':
        """Utworzenie z JSON"""
        data = json.loads(json_str)
        return cls.from_dict(data)
