# SSI V5 Feedback Module
# ========================
#
# ETAP: 5.2.8 - Strategy Evolution Integration + Feedback Learning Loop
# Data: 2026-08-04
#
# Odpowiedzialnosc:
# - Zamknięta pętla uczenia: STRATEGIA -> Prediction -> Result -> Evaluation -> Fitness -> Memory -> Evolution
# - Integracja istniejących modułów: Strategy Laboratory, Strategy Memory, Prediction Trace, Result Ingestion, Strategy Evolution
# - TYLKO WARSTWA INTEGRACYJNA - nie modyfikuje istniejących modułów
#
# ZASADY:
# 1. NIE MODYFIKUJE PRODUKCJI
# 2. Korzysta z kopii danych (nie oryginałów)
# 3. Wyniki są niezależne od systemu produkcyjnego
# 4. Tylko obserwacja - nie modyfikacja aktywnych strategii
#
# Architektura:
# Prediction Trace -> Result Ingestion -> Prediction Evaluator -> 
# Strategy Fitness Calculator -> Strategy Memory -> Evolution Engine
#
# Generated by Mistral Vibe.
# Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

from .feedback_models import (
    PredictionOutcome,
    StrategyFitness,
    FeedbackEvent,
    FeedbackEventType,
    EvaluationStatus
)

from .prediction_evaluator import (
    PredictionEvaluator,
    EvaluationResult,
    ExactScoreEvaluation,
    ResultEvaluation
)

from .fitness_calculator import (
    StrategyFitnessCalculator,
    FitnessComponents,
    FitnessWeights
)

from .feedback_engine import (
    FeedbackEngine,
    FeedbackConfig,
    FeedbackPipeline,
    FeedbackContext
)

# Wersja modułu
__version__ = "1.0.0"
__etap__ = "5.2.8"
__name__ = "SSI_V5_FEEDBACK"

# Eksport publiczny
__all__ = [
    # Models
    'PredictionOutcome',
    'StrategyFitness', 
    'FeedbackEvent',
    'FeedbackEventType',
    'EvaluationStatus',
    
    # Prediction Evaluator
    'PredictionEvaluator',
    'EvaluationResult',
    'ExactScoreEvaluation',
    'ResultEvaluation',
    
    # Fitness Calculator
    'StrategyFitnessCalculator',
    'FitnessComponents',
    'FitnessWeights',
    
    # Feedback Engine
    'FeedbackEngine',
    'FeedbackConfig',
    'FeedbackPipeline',
    'FeedbackContext',
    
    # Metadata
    '__version__',
    '__etap__',
    '__name__'
]

# Inicjalizacja - rejestracja modułu w systemie
print(f"[FEEDBACK] Moduł {__name__} v{__version__} (ETAP {__etap__}) załadowany")