# SSI V5 Feedback Module - Feedback Models
# =============================================
#
# ETAP: 5.2.8.3 - Feedback Models
# Data: 2026-08-04
#
# Odpowiedzialnosc:
# - Modele danych dla Feedback Learning Loop
# - PredictionOutcome: Wynik porównania predykcji z rzeczywistością
# - StrategyFitness: Fitness konkretnej strategii
# - FeedbackEvent: Zdarzenia w pętli feedback
#
# ZASADY:
# 1. NIE MODYFIKUJE PRODUKCJI
# 2. Tylko do użytku w Feedback Engine
# 3. Kompatybilne z istniejącymi modelami SSI V5
# 4. Serializowalne do JSON
#
# powiazania:
# PredictionOutcome <- Prediction Trace + Match Result
# StrategyFitness <- PredictionOutcome (agregacja)
# FeedbackEvent <- Wszystkie operacje w pętli
#
# Generated by Mistral Vibe.
# Co-Authored-By: Mistral Vibe <vibe@mistral.ai>

from dataclasses import dataclass, field
from typing import Dict, List, Any, Optional, Union
from datetime import datetime
from enum import Enum
import json
import uuid
import copy
from pathlib import Path


# ============================================================================
# ENUMY
# ============================================================================

class FeedbackEventType(Enum):
    """Typy zdarzeń w pętli feedback"""
    # Predykcja
    PREDICTION_CREATED = "prediction_created"
    PREDICTION_TRACE_RECEIVED = "prediction_trace_received"
    
    # Wynik
    RESULT_RECEIVED = "result_received"
    RESULT_PARSED = "result_parsed"
    
    # Ewaluacja
    EVALUATION_STARTED = "evaluation_started"
    EVALUATION_COMPLETED = "evaluation_completed"
    
    # Fitness
    FITNESS_CALCULATION_STARTED = "fitness_calculation_started"
    FITNESS_CALCULATION_COMPLETED = "fitness_calculation_completed"
    FITNESS_UPDATED = "fitness_updated"
    
    # Pamięć
    MEMORY_SAVE_STARTED = "memory_save_started"
    MEMORY_SAVE_COMPLETED = "memory_save_completed"
    MEMORY_LOAD_STARTED = "memory_load_started"
    MEMORY_LOAD_COMPLETED = "memory_load_completed"
    
    # Ewolucja
    EVOLUTION_TRIGGERED = "evolution_triggered"
    EVOLUTION_COMPLETED = "evolution_completed"
    
    # Błędy
    ERROR_PREDICTION_MISMATCH = "error_prediction_mismatch"
    ERROR_RESULT_MISSING = "error_result_missing"
    ERROR_CALCULATION_FAILED = "error_calculation_failed"
    ERROR_memory_FAILED = "error_memory_failed"
    
    # System
    FEEDBACK_LOOP_STARTED = "feedback_loop_started"
    FEEDBACK_LOOP_COMPLETED = "feedback_loop_completed"
    SYSTEM_INITIALIZED = "system_initialized"


class EvaluationStatus(Enum):
    """Status ewaluacji predykcji"""
    PENDING = "pending"           # Oczekuje na wynik
    COMPARING = "comparing"       # W trakcie porównywania
    CORRECT = "correct"           # Predykcja poprawna
    INCORRECT = "incorrect"       # Predykcja błędna
    PARTIAL = "partial"           # Częściowo poprawna (np. dobrze typ wynik, źle gol))
    EXACT = "exact"               # Dokładnie poprawna (wynik i gol)
    UNEVALUATED = "unevaluated"   # Nieoceniona (brak wyniku)


class OutcomeType(Enum):
    """Typ wyniku porównania"""
    RESULT_ONLY = "result_only"       # Tylko typ wyniku (1/X/2)
    GOALS_ONLY = "goals_only"         # Tylko liczba goli
    EXACT_SCORE = "exact_score"       # Dokładny wynik (2:1)
    GOAL_DIFFERENCE = "goal_difference"  # Różnica goli


# ============================================================================
# MODELE DANYCH
# ============================================================================

@dataclass
class PredictionOutcome:
    """
    Wynik porównania predykcji z rzeczywistym wynikiem.
    
    Przechowuje:
    - predykcja: co zostało przewidziane
    - wynik: co doszło faktycznie  
    - ocena: jak dobrze zostało przewidziane
    - metryki: szczegółowe metryki dokładności
    
    Powiązania:
    - prediction_trace_id: Referencja do PredictionTraceRecord
    - match_id: Referencja do MatchResult
    - strategy_id: Która strategia przewidziała
    """
    
    # ===== IDENTYFIKACJA =====
    outcome_id: str = field(default_factory=lambda: f"outcome_{uuid.uuid4().hex[:12]}")
    prediction_trace_id: str = ""
    prediction_id: str = ""
    match_id: str = ""
    strategy_id: str = ""
    
    # ===== DANE PREDYKCJI =====
    prediction_data: Dict[str, Any] = field(default_factory=dict)
    predicted_result: str = ""  # "1", "X", "2" lub specyficzny wynik
    predicted_home_goals: Optional[int] = None
    predicted_away_goals: Optional[int] = None
    prediction_confidence: float = 0.0
    prediction_timestamp: Optional[datetime] = None
    
    # ===== DANE RZECZYWISTE =====
    actual_result: str = ""  # "1", "X", "2"
    actual_home_goals: int = 0
    actual_away_goals: int = 0
    result_source: str = ""
    result_timestamp: Optional[datetime] = None
    
    # ===== OCENY =====
    outcome_type: OutcomeType = OutcomeType.RESULT_ONLY
    evaluation_status: EvaluationStatus = EvaluationStatus.PENDING
    
    # Metryki dokładności
    exact_score: bool = False         # Czy dokładnie ten sam wynik (2:1 == 2:1)
    result_correct: bool = False       # Czy poprawnie typ wyniku (1/X/2)
    goals_correct: bool = False        # Czy poprawnie typy goli
    home_goals_correct: bool = False   # Czy poprawnie home goals
    away_goals_correct: bool = False   # Czy poprawnie away goals
    
    # Metryki numeryczne (0.0 - 1.0)
    accuracy_score: float = 0.0        # Ogólna dokładność
    result_accuracy: float = 0.0        # Dokładność typu wyniku
    goals_accuracy: float = 0.0         # Dokładność goli
    score_accuracy: float = 0.0         # Dokładność wyniku
    
    # Dodatkowe informacje
    goal_difference_accuracy: float = 0.0  # Dokładność różnicy goli
    
    # ===== METADANE =====
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # ===== METODY =====
    
    def calculate_scores(self) -> None:
        """Oblicza wszystkie metryki na podstawie danych."""
        # Typ wyniku
        self._calculate_result_accuracy()
        
        # Dokładny wynik
        self._calculate_exact_score()
        
        # Dokładność goli
        self._calculate_goals_accuracy()
        
        # Dokładność różnicy goli
        self._calculate_goal_difference_accuracy()
        
        # Ogólna dokładność (waga: exact_score 40%, result 30%, goals 20%, diff 10%)
        result_weight = 0.30
        exact_weight = 0.40
        goals_weight = 0.20
        diff_weight = 0.10
        
        accuracy_components = []
        if self.exact_score:
            accuracy_components.append(exact_weight)
        if self.result_correct:
            accuracy_components.append(result_weight)
        if self.goals_correct:
            accuracy_components.append(goals_weight)
        
        self.accuracy_score = sum(accuracy_components)
        
        # Ustal status ewaluacji
        self._update_evaluation_status()
    
    def _calculate_result_accuracy(self) -> None:
        """Oblicza dokładność typu wyniku (1/X/2)."""
        if not self.predicted_result or not self.actual_result:
            self.result_correct = False
            self.result_accuracy = 0.0
            return
        
        self.result_correct = self.predicted_result == self.actual_result
        self.result_accuracy = 1.0 if self.result_correct else 0.0
    
    def _calculate_exact_score(self) -> None:
        """Oblicza czy wynik jest dokładnie taki sam."""
        if (self.predicted_home_goals is not None and 
            self.predicted_away_goals is not None):
            self.exact_score = (
                self.predicted_home_goals == self.actual_home_goals and
                self.predicted_away_goals == self.actual_away_goals
            )
        else:
            self.exact_score = False
            
        self.score_accuracy = 1.0 if self.exact_score else 0.0
    
    def _calculate_goals_accuracy(self) -> None:
        """Oblicza dokładność goli."""
        home_correct = (self.predicted_home_goals is not None and 
                       self.predicted_home_goals == self.actual_home_goals)
        away_correct = (self.predicted_away_goals is not None and 
                       self.predicted_away_goals == self.actual_away_goals)
        
        self.home_goals_correct = home_correct
        self.away_goals_correct = away_correct
        self.goals_correct = home_correct and away_correct
        
        # Dokładność goli (średnia z obu stron)
        goals_score = 0.0
        if self.predicted_home_goals is not None:
            goals_score += 0.5
        if self.predicted_away_goals is not None:
            goals_score += 0.5
            
        if home_correct:
            goals_score += 0.25
        if away_correct:
            goals_score += 0.25
            
        self.goals_accuracy = min(goals_score, 1.0)
    
    def _calculate_goal_difference_accuracy(self) -> None:
        """Oblicza dokładność różnicy goli."""
        predicted_diff = 0
        if self.predicted_home_goals is not None and self.predicted_away_goals is not None:
            predicted_diff = self.predicted_home_goals - self.predicted_away_goals
        
        actual_diff = self.actual_home_goals - self.actual_away_goals
        
        # Dokładność różnicy (0.0 - 1.0, im mniejsza różnica tym lepiej)
        if predicted_diff == actual_diff:
            self.goal_difference_accuracy = 1.0
        else:
            # Im mniejsza różnica w różnicy, tym wyższa dokładność
            max_possible_diff = 20  # Maksymalna możliwa różnica goli
            diff_error = abs(predicted_diff - actual_diff)
            self.goal_difference_accuracy = max(0.0, 1.0 - (diff_error / max_possible_diff))
    
    def _update_evaluation_status(self) -> None:
        """Uaktualnia status ewaluacji na podstawie wyników."""
        if not self.predicted_result or not self.actual_result:
            self.evaluation_status = EvaluationStatus.UNEVALUATED
            return
            
        if self.exact_score:
            self.evaluation_status = EvaluationStatus.EXACT
        elif self.result_correct and self.goals_correct:
            self.evaluation_status = EvaluationStatus.CORRECT
        elif self.result_correct:
            self.evaluation_status = EvaluationStatus.PARTIAL
        else:
            self.evaluation_status = EvaluationStatus.INCORRECT
    
    def is_correct(self) -> bool:
        """Czy predykcja była poprawna (co najmniej typ wyniku)."""
        return self.result_correct
    
    def is_exact(self) -> bool:
        """Czy predykcja była dokładna (wynik i gol)."""
        return self.exact_score
    
    def get_summary(self) -> Dict[str, Any]:
        """Podsumowanie wyniku."""
        return {
            "outcome_id": self.outcome_id,
            "strategy_id": self.strategy_id,
            "prediction": f"{self.predicted_result}",
            "actual": f"{self.actual_result}",
            "status": self.evaluation_status.value,
            "accuracy_score": round(self.accuracy_score, 4),
            "exact_score": self.exact_score,
            "result_correct": self.result_correct,
            "is_exact": self.is_exact(),
            "is_correct": self.is_correct()
        }
    
    # ===== SERIALIZACJA =====
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do słownika."""
        data = {
            'outcome_id': self.outcome_id,
            'prediction_trace_id': self.prediction_trace_id,
            'prediction_id': self.prediction_id,
            'match_id': self.match_id,
            'strategy_id': self.strategy_id,
            'prediction_data': copy.deepcopy(self.prediction_data),
            'predicted_result': self.predicted_result,
            'predicted_home_goals': self.predicted_home_goals,
            'predicted_away_goals': self.predicted_away_goals,
            'prediction_confidence': self.prediction_confidence,
            'actual_result': self.actual_result,
            'actual_home_goals': self.actual_home_goals,
            'actual_away_goals': self.actual_away_goals,
            'result_source': self.result_source,
            'outcome_type': self.outcome_type.value,
            'evaluation_status': self.evaluation_status.value,
            'exact_score': self.exact_score,
            'result_correct': self.result_correct,
            'goals_correct': self.goals_correct,
            'home_goals_correct': self.home_goals_correct,
            'away_goals_correct': self.away_goals_correct,
            'accuracy_score': self.accuracy_score,
            'result_accuracy': self.result_accuracy,
            'goals_accuracy': self.goals_accuracy,
            'score_accuracy': self.score_accuracy,
            'goal_difference_accuracy': self.goal_difference_accuracy,
            'timestamp': self.timestamp.isoformat(),
            'metadata': copy.deepcopy(self.metadata)
        }
        
        if self.prediction_timestamp:
            data['prediction_timestamp'] = self.prediction_timestamp.isoformat()
        if self.result_timestamp:
            data['result_timestamp'] = self.result_timestamp.isoformat()
            
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'PredictionOutcome':
        """Utworzenie z słownika."""
        prediction_timestamp = None
        result_timestamp = None
        
        if data.get('prediction_timestamp'):
            prediction_timestamp = datetime.fromisoformat(data['prediction_timestamp'])
        if data.get('result_timestamp'):
            result_timestamp = datetime.fromisoformat(data['result_timestamp'])
        if data.get('timestamp'):
            timestamp = datetime.fromisoformat(data['timestamp'])
        else:
            timestamp = datetime.now()
        
        outcome = cls(
            outcome_id=data.get('outcome_id', f"outcome_{uuid.uuid4().hex[:12]}"),
            prediction_trace_id=data.get('prediction_trace_id', ''),
            prediction_id=data.get('prediction_id', ''),
            match_id=data.get('match_id', ''),
            strategy_id=data.get('strategy_id', ''),
            prediction_data=copy.deepcopy(data.get('prediction_data', {})),
            predicted_result=data.get('predicted_result', ''),
            predicted_home_goals=data.get('predicted_home_goals'),
            predicted_away_goals=data.get('predicted_away_goals'),
            prediction_confidence=float(data.get('prediction_confidence', 0.0)),
            actual_result=data.get('actual_result', ''),
            actual_home_goals=int(data.get('actual_home_goals', 0)),
            actual_away_goals=int(data.get('actual_away_goals', 0)),
            result_source=data.get('result_source', ''),
            outcome_type=OutcomeType(data.get('outcome_type', 'result_only')),
            evaluation_status=EvaluationStatus(data.get('evaluation_status', 'pending')),
            exact_score=bool(data.get('exact_score', False)),
            result_correct=bool(data.get('result_correct', False)),
            goals_correct=bool(data.get('goals_correct', False)),
            home_goals_correct=bool(data.get('home_goals_correct', False)),
            away_goals_correct=bool(data.get('away_goals_correct', False)),
            accuracy_score=float(data.get('accuracy_score', 0.0)),
            result_accuracy=float(data.get('result_accuracy', 0.0)),
            goals_accuracy=float(data.get('goals_accuracy', 0.0)),
            score_accuracy=float(data.get('score_accuracy', 0.0)),
            goal_difference_accuracy=float(data.get('goal_difference_accuracy', 0.0)),
            timestamp=timestamp,
            prediction_timestamp=prediction_timestamp,
            result_timestamp=result_timestamp,
            metadata=copy.deepcopy(data.get('metadata', {}))
        )
        
        return outcome
    
    def to_json(self, indent: int = 4) -> str:
        """Konwersja do JSON."""
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'PredictionOutcome':
        """Utworzenie z JSON."""
        data = json.loads(json_str)
        return cls.from_dict(data)
    
    def __repr__(self) -> str:
        return (f"PredictionOutcome(strategy_id='{self.strategy_id}', "
                f"prediction='{self.predicted_result}', "
                f"actual='{self.actual_result}', "
                f"status={self.evaluation_status.value}, "
                f"accuracy={self.accuracy_score:.4f})")


@dataclass
class StrategyFitness:
    """
    Fitness konkretnej strategii.
    
    Przechowuje:
    - Historia ocen predykcji
    - Statystyki strategii
    - Waga i ranking strategii
    - Historia ewolucji fitness
    
    Fitness to wartość 0.0 - 1.0, gdzie:
    - 1.0 = idealna strategia
    - 0.0 = zupełnie nieudana strategia
    
    Składniki fitness:
    - accuracy: dokładność predykcji
    - profitability: opłacalność (ROI)
    - stability: stabilność wyników
    - risk: poziom ryzyka
    - consistency: spójność wyników
    """
    
    # ===== IDENTYFIKACJA =====
    fitness_id: str = field(default_factory=lambda: f"fitness_{uuid.uuid4().hex[:12]}")
    strategy_id: str = ""
    strategy_version: str = "1.0.0"
    
    # ===== STATYSTYKI OGÓLNE =====
    total_predictions: int = 0
    correct_predictions: int = 0
    exact_predictions: int = 0
    partial_predictions: int = 0
    failed_predictions: int = 0
    
    # ===== METRYKI =====
    # Dokładność (0.0 - 1.0)
    accuracy: float = 0.0
    exact_accuracy: float = 0.0  # Dokładne trafienia (wynik + gol)
    result_accuracy: float = 0.0  # Tylko typ wyniku
    goals_accuracy: float = 0.0   # Dokładność goli
    
    # Opłacalność (0.0 - 1.0) - NIE UŻYWAMY JESZCZE PIENIĘDZY PRODUKCYJNE
    profit_score: float = 0.0
    roi: float = 0.0  # Return on Investment (symulowany)
    
    # Stabilność (0.0 - 1.0)
    stability_score: float = 0.0
    variance: float = 0.0  # Wariancja wyników
    
    # Ryzyko (0.0 - 1.0, im niższe tym lepiej)
    risk_score: float = 0.0
    max_loss: float = 0.0
    loss_frequency: float = 0.0
    
    # Ogólny fitness (0.0 - 1.0)
    overall_fitness: float = 0.0
    
    # ===== WAGI SKŁADNIKÓW =====
    # Domyślne wagi dla obliczania fitness
    weights: Dict[str, float] = field(default_factory=lambda: {
        'accuracy': 0.40,
        'exact_accuracy': 0.25,
        'stability': 0.20,
        'profitability': 0.10,
        'low_risk': 0.05
    })
    
    # ===== HISTORIA =====
    prediction_history: List[str] = field(default_factory=list)  # Lista outcome_id
    accuracy_history: List[float] = field(default_factory=list)
    fitness_history: List[float] = field(default_factory=list)
    timestamps: List[str] = field(default_factory=list)
    
    # ===== METADANE =====
    created_at: datetime = field(default_factory=datetime.now)
    last_updated: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # ===== METODY =====
    
    def add_prediction_outcome(self, outcome: PredictionOutcome) -> None:
        """Dodaj wynik predykcji i zaktualizuj statystyki."""
        self.total_predictions += 1
        self.accuracy_history.append(outcome.accuracy_score)
        self.fitness_history.append(self.overall_fitness)
        self.timestamps.append(datetime.now().isoformat())
        self.prediction_history.append(outcome.outcome_id)
        
        if outcome.is_exact():
            self.exact_predictions += 1
        elif outcome.is_correct():
            self.correct_predictions += 1
            self.partial_predictions += 1
        else:
            self.failed_predictions += 1
        
        # Zaktualizuj metryki
        self._update_metrics()
        self._update_fitness()
        self.last_updated = datetime.now()
    
    def _update_metrics(self) -> None:
        """Uaktualnia metryki na podstawie historii."""
        if self.total_predictions == 0:
            return
        
        # Dokładność
        self.accuracy = self.correct_predictions / self.total_predictions
        self.exact_accuracy = self.exact_predictions / self.total_predictions
        
        # używana do obliczania średniej dokładności  
        if self.accuracy_history:
            self.result_accuracy = sum(self.accuracy_history) / len(self.accuracy_history)
        
        # Stabilność (odchylenie standardowe dokładności)
        if len(self.accuracy_history) > 1:
            mean_accuracy = sum(self.accuracy_history) / len(self.accuracy_history)
            self.variance = sum((x - mean_accuracy) ** 2 for x in self.accuracy_history) / len(self.accuracy_history)
            self.stability_score = max(0.0, 1.0 - self.variance)
        else:
            self.stability_score = 1.0  # Brak danych do obliczenia wariancji
        
        # Ryzyko
        self.loss_frequency = self.failed_predictions / self.total_predictions
        self.risk_score = min(1.0, self.loss_frequency * 2)  # Im więcej porażek, tym wyższe ryzyko
        
        # Symulowany ROI (0.0 - 2.0, gdzie 1.0 = break even)
        # Na tym etapie symulujemy opłacalność na podstawie dokładności
        if self.accuracy > 0:
            self.roi = 1.0 + (self.accuracy * 0.5)  # Im wyższa dokładność, tym wyższ ROI
            self.profit_score = min(1.0, self.roi / 2)  # Normalizacja do 0.0 - 1.0
    
    def _update_fitness(self) -> None:
        """Oblicza ogólny fitness na podstawie składników."""
        if self.total_predictions == 0:
            self.overall_fitness = 0.0
            return
            
        # Składniki fitness (0.0 - 1.0)
        accuracy_component = self.accuracy * self.weights.get('accuracy', 0.40)
        exact_component = self.exact_accuracy * self.weights.get('exact_accuracy', 0.25)
        stability_component = self.stability_score * self.weights.get('stability', 0.20)
        profitability_component = self.profit_score * self.weights.get('profitability', 0.10)
        low_risk_component = (1.0 - self.risk_score) * self.weights.get('low_risk', 0.05)
        
        # Sumowanie składników
        total_components = (
            accuracy_component +
            exact_component +
            stability_component +
            profitability_component +
            low_risk_component
        )
        
        self.overall_fitness = min(1.0, max(0.0, total_components))
    
    def get_ranking(self) -> str:
        """Klasyfikacja strategii na podstawie fitness."""
        if self.overall_fitness >= 0.9:
            return "A+ (EXCELLENT)"
        elif self.overall_fitness >= 0.8:
            return "A (GREAT)"
        elif self.overall_fitness >= 0.7:
            return "B (GOOD)"
        elif self.overall_fitness >= 0.6:
            return "C (AVERAGE)"
        elif self.overall_fitness >= 0.5:
            return "D (BELOW AVERAGE)"
        elif self.overall_fitness >= 0.4:
            return "E (POOR)"
        else:
            return "F (FAIL)"
    
    def get_summary(self) -> Dict[str, Any]:
        """Podsumowanie fitness strategii."""
        return {
            "fitness_id": self.fitness_id,
            "strategy_id": self.strategy_id,
            "strategy_version": self.strategy_version,
            "total_predictions": self.total_predictions,
            "correct_predictions": self.correct_predictions,
            "exact_predictions": self.exact_predictions,
            "overall_fitness": round(self.overall_fitness, 4),
            "ranking": self.get_ranking(),
            "accuracy": round(self.accuracy, 4),
            "exact_accuracy": round(self.exact_accuracy, 4),
            "stability": round(self.stability_score, 4),
            "profit_score": round(self.profit_score, 4),
            "risk_score": round(self.risk_score, 4),
            "created_at": self.created_at.isoformat(),
            "last_updated": self.last_updated.isoformat()
        }
    
    # ===== SERIALIZACJA =====
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do słownika."""
        data = {
            'fitness_id': self.fitness_id,
            'strategy_id': self.strategy_id,
            'strategy_version': self.strategy_version,
            'total_predictions': self.total_predictions,
            'correct_predictions': self.correct_predictions,
            'exact_predictions': self.exact_predictions,
            'partial_predictions': self.partial_predictions,
            'failed_predictions': self.failed_predictions,
            'accuracy': self.accuracy,
            'exact_accuracy': self.exact_accuracy,
            'result_accuracy': self.result_accuracy,
            'goals_accuracy': self.goals_accuracy,
            'profit_score': self.profit_score,
            'roi': self.roi,
            'stability_score': self.stability_score,
            'variance': self.variance,
            'risk_score': self.risk_score,
            'max_loss': self.max_loss,
            'loss_frequency': self.loss_frequency,
            'overall_fitness': self.overall_fitness,
            'weights': copy.deepcopy(self.weights),
            'prediction_history': copy.deepcopy(self.prediction_history),
            'accuracy_history': copy.deepcopy(self.accuracy_history),
            'fitness_history': copy.deepcopy(self.fitness_history),
            'timestamps': copy.deepcopy(self.timestamps),
            'created_at': self.created_at.isoformat(),
            'last_updated': self.last_updated.isoformat(),
            'metadata': copy.deepcopy(self.metadata)
        }
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'StrategyFitness':
        """Utworzenie z słownika."""
        created_at = data.get('created_at')
        last_updated = data.get('last_updated')
        
        if isinstance(created_at, str):
            created_at = datetime.fromisoformat(created_at)
        if isinstance(last_updated, str):
            last_updated = datetime.fromisoformat(last_updated)
        
        return cls(
            fitness_id=data.get('fitness_id', f"fitness_{uuid.uuid4().hex[:12]}"),
            strategy_id=data.get('strategy_id', ''),
            strategy_version=data.get('strategy_version', '1.0.0'),
            total_predictions=int(data.get('total_predictions', 0)),
            correct_predictions=int(data.get('correct_predictions', 0)),
            exact_predictions=int(data.get('exact_predictions', 0)),
            partial_predictions=int(data.get('partial_predictions', 0)),
            failed_predictions=int(data.get('failed_predictions', 0)),
            accuracy=float(data.get('accuracy', 0.0)),
            exact_accuracy=float(data.get('exact_accuracy', 0.0)),
            result_accuracy=float(data.get('result_accuracy', 0.0)),
            goals_accuracy=float(data.get('goals_accuracy', 0.0)),
            profit_score=float(data.get('profit_score', 0.0)),
            roi=float(data.get('roi', 0.0)),
            stability_score=float(data.get('stability_score', 0.0)),
            variance=float(data.get('variance', 0.0)),
            risk_score=float(data.get('risk_score', 0.0)),
            max_loss=float(data.get('max_loss', 0.0)),
            loss_frequency=float(data.get('loss_frequency', 0.0)),
            overall_fitness=float(data.get('overall_fitness', 0.0)),
            weights=copy.deepcopy(data.get('weights', {})),
            prediction_history=copy.deepcopy(data.get('prediction_history', [])),
            accuracy_history=copy.deepcopy(data.get('accuracy_history', [])),
            fitness_history=copy.deepcopy(data.get('fitness_history', [])),
            timestamps=copy.deepcopy(data.get('timestamps', [])),
            created_at=created_at or datetime.now(),
            last_updated=last_updated or datetime.now(),
            metadata=copy.deepcopy(data.get('metadata', {}))
        )
    
    def to_json(self, indent: int = 4) -> str:
        """Konwersja do JSON."""
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'StrategyFitness':
        """Utworzenie z JSON."""
        data = json.loads(json_str)
        return cls.from_dict(data)
    
    def __repr__(self) -> str:
        return (f"StrategyFitness(strategy_id='{self.strategy_id}', "
                f"fitness={self.overall_fitness:.4f}, "
                f"accuracy={self.accuracy:.4f}, "
                f"total={self.total_predictions})")


@dataclass
class FeedbackEvent:
    """
    Zdarzenie w pętli feedback.
    
    Rejestruje wszystkie ważne zdarzenia zachodzące podczas:
    - Odbierania predykcji
    - Odbierania wyników
    - Ewaluacji
    - Obliczania fitness
    - Zapisywania do pamięci
    - Ewolucji strategii
    
    Używane do:
    - Debugowania
    - Audytu
    - Analizy wydajności
    - Reprodukcji
    """
    
    # ===== IDENTYFIKACJA =====
    event_id: str = field(default_factory=lambda: f"event_{uuid.uuid4().hex[:12]}")
    strategy_id: str = ""
    feedback_loop_id: str = ""
    
    # ===== ZDARZENIE =====
    event_type: FeedbackEventType = FeedbackEventType.SYSTEM_INITIALIZED
    event_name: str = ""
    
    # ===== STAN PRZED I PO =====
    before_state: Dict[str, Any] = field(default_factory=dict)
    after_state: Dict[str, Any] = field(default_factory=dict)
    
    # ===== DETAL =====  
    reason: str = ""
    details: Dict[str, Any] = field(default_factory=dict)
    success: bool = True
    error_message: Optional[str] = None
    
    # ===== METRYKI ZDARZENIA =====
    processing_time_ms: float = 0.0
    memory_usage_bytes: int = 0
    
    # ===== METADANE =====
    timestamp: datetime = field(default_factory=datetime.now)
    metadata: Dict[str, Any] = field(default_factory=dict)
    
    # ===== METODY =====
    
    def mark_success(self, after_state: Dict[str, Any] = None, reason: str = "") -> None:
        """Zaznacz zdarzenie jako sukces."""
        self.success = True
        self.error_message = None
        if after_state:
            self.after_state = copy.deepcopy(after_state)
        if reason:
            self.reason = reason
    
    def mark_failure(self, error_message: str, reason: str = "") -> None:
        """Zaznacz zdarzenie jako porażka."""
        self.success = False
        self.error_message = error_message
        if reason:
            self.reason = reason
    
    def is_success(self) -> bool:
        """Czy zdarzenie zakończyło się sukcesem."""
        return self.success
    
    def is_failure(self) -> bool:
        """Czy zdarzenie zakończyło się porażką."""
        return not self.success
    
    def get_summary(self) -> Dict[str, Any]:
        """Podsumowanie zdarzenia."""
        return {
            "event_id": self.event_id,
            "strategy_id": self.strategy_id,
            "event_type": self.event_type.value,
            "event_name": self.event_name,
            "success": self.success,
            "timestamp": self.timestamp.isoformat(),
            "reason": self.reason,
            "processing_time_ms": round(self.processing_time_ms, 2),
            "error_message": self.error_message
        }
    
    # ===== SERIALIZACJA =====
    
    def to_dict(self) -> Dict[str, Any]:
        """Konwersja do słownika."""
        data = {
            'event_id': self.event_id,
            'strategy_id': self.strategy_id,
            'feedback_loop_id': self.feedback_loop_id,
            'event_type': self.event_type.value,
            'event_name': self.event_name,
            'before_state': copy.deepcopy(self.before_state),
            'after_state': copy.deepcopy(self.after_state),
            'reason': self.reason,
            'details': copy.deepcopy(self.details),
            'success': self.success,
            'error_message': self.error_message,
            'processing_time_ms': self.processing_time_ms,
            'memory_usage_bytes': self.memory_usage_bytes,
            'timestamp': self.timestamp.isoformat(),
            'metadata': copy.deepcopy(self.metadata)
        }
        return data
    
    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'FeedbackEvent':
        """Utworzenie z słownika."""
        timestamp = data.get('timestamp')
        if isinstance(timestamp, str):
            timestamp = datetime.fromisoformat(timestamp)
        
        return cls(
            event_id=data.get('event_id', f"event_{uuid.uuid4().hex[:12]}"),
            strategy_id=data.get('strategy_id', ''),
            feedback_loop_id=data.get('feedback_loop_id', ''),
            event_type=FeedbackEventType(data.get('event_type', 'system_initialized')),
            event_name=data.get('event_name', ''),
            before_state=copy.deepcopy(data.get('before_state', {})),
            after_state=copy.deepcopy(data.get('after_state', {})),
            reason=data.get('reason', ''),
            details=copy.deepcopy(data.get('details', {})),
            success=bool(data.get('success', True)),
            error_message=data.get('error_message'),
            processing_time_ms=float(data.get('processing_time_ms', 0.0)),
            memory_usage_bytes=int(data.get('memory_usage_bytes', 0)),
            timestamp=timestamp or datetime.now(),
            metadata=copy.deepcopy(data.get('metadata', {}))
        )
    
    def to_json(self, indent: int = 4) -> str:
        """Konwersja do JSON."""
        return json.dumps(self.to_dict(), indent=indent, ensure_ascii=False)
    
    @classmethod
    def from_json(cls, json_str: str) -> 'FeedbackEvent':
        """Utworzenie z JSON."""
        data = json.loads(json_str)
        return cls.from_dict(data)
    
    def __repr__(self) -> str:
        status = "SUCCESS" if self.success else "FAILED"
        return (f"FeedbackEvent({self.event_type.value}, "
                f"strategy='{self.strategy_id}', "
                f"{status})")


# ============================================================================
# FABRYKI I UTILITY
# ============================================================================

def create_prediction_outcome_from_trace_and_result(
    prediction_trace: Dict[str, Any],
    match_result: Dict[str, Any],
    strategy_id: str = ""
) -> PredictionOutcome:
    """
    Fabryka: Tworzy PredictionOutcome z PredictionTrace i MatchResult.
    
    Args:
        prediction_trace: Dane z PredictionTraceRecord
        match_result: Dane z MatchResult
        strategy_id: ID strategii (opcjonalnie)
    
    Returns:
        PredictionOutcome
    """
    # Pobierz dane predykcji
    predicted_result = prediction_trace.get('prediction', {}).get('result', '')
    predicted_confidence = prediction_trace.get('prediction', {}).get('confidence', 0.0)
    prediction_id = prediction_trace.get('prediction_id', '')
    trace_id = prediction_trace.get('trace_id', '')
    
    # Pobierz dane wyniku
    actual_result = match_result.get('result', '')
    actual_home_goals = int(match_result.get('home_goals', 0))
    actual_away_goals = int(match_result.get('away_goals', 0))
    match_id = match_result.get('match_id', '')
    
    # Stwórz outcome
    outcome = PredictionOutcome(
        prediction_trace_id=trace_id,
        prediction_id=prediction_id,
        match_id=match_id,
        strategy_id=strategy_id or prediction_trace.get('strategy_id', ''),
        prediction_data=copy.deepcopy(prediction_trace.get('prediction', {})),
        predicted_result=predicted_result,
        actual_result=actual_result,
        actual_home_goals=actual_home_goals,
        actual_away_goals=actual_away_goals,
        prediction_confidence=predicted_confidence
    )
    
    # Oblicz metryki
    outcome.calculate_scores()
    
    return outcome


def create_feedback_event(
    event_type: FeedbackEventType,
    strategy_id: str = "",
    feedback_loop_id: str = "",
    reason: str = "",
    before_state: Dict[str, Any] = None,
    event_name: str = ""
) -> FeedbackEvent:
    """
    Fabryka: Tworzy FeedbackEvent.
    
    Args:
        event_type: Typ zdarzenia
        strategy_id: ID strategii
        feedback_loop_id: ID pętli feedback
        reason: Powód zdarzenia
        before_state: Stan przed zdarzeniem
        event_name: Nazwa zdarzenia
    
    Returns:
        FeedbackEvent
    """
    return FeedbackEvent(
        event_type=event_type,
        strategy_id=strategy_id,
        feedback_loop_id=feedback_loop_id,
        reason=reason,
        before_state=copy.deepcopy(before_state) or {},
        event_name=event_name
    )


# ============================================================================
# TESTY MODUŁU (dla weryfikacji)
# ============================================================================

def test_feedback_models():
    """Testowanie modeli feedback."""
    print("\n" + "="*60)
    print("TEST: Feedback Models")
    print("="*60)
    
    results = []
    
    # Test 1: PredictionOutcome - stworzenie
    try:
        outcome = PredictionOutcome(
            strategy_id="test_strategy",
            predicted_result="1",
            actual_result="1",
            predicted_home_goals=2,
            predicted_away_goals=1,
            actual_home_goals=2,
            actual_away_goals=1
        )
        outcome.calculate_scores()
        assert outcome.exact_score == True
        assert outcome.result_correct == True
        assert outcome.accuracy_score > 0
        results.append(("PredictionOutcome creation", True))
        print("[OK] Test PredictionOutcome creation - zaliczony")
    except Exception as e:
        results.append(("PredictionOutcome creation", False))
        print(f"[FAIL] Test PredictionOutcome creation - error: {e}")
    
    # Test 2: PredictionOutcome - błędna predykcja
    try:
        outcome = PredictionOutcome(
            strategy_id="test_strategy",
            predicted_result="1",
            actual_result="2",
            predicted_home_goals=2,
            predicted_away_goals=1,
            actual_home_goals=1,
            actual_away_goals=2
        )
        outcome.calculate_scores()
        assert outcome.exact_score == False
        assert outcome.result_correct == False
        assert outcome.accuracy_score == 0.0
        results.append(("PredictionOutcome wrong prediction", True))
        print("[OK] Test PredictionOutcome wrong prediction - zaliczony")
    except Exception as e:
        results.append(("PredictionOutcome wrong prediction", False))
        print(f"[FAIL] Test PredictionOutcome wrong prediction - error: {e}")
    
    # Test 3: StrategyFitness - dodawanie outcome
    try:
        fitness = StrategyFitness(strategy_id="test_strategy")
        
        # Dobra predykcja
        outcome1 = PredictionOutcome(
            strategy_id="test_strategy",
            predicted_result="1",
            actual_result="1",
            predicted_home_goals=2,
            predicted_away_goals=1,
            actual_home_goals=2,
            actual_away_goals=1
        )
        outcome1.calculate_scores()
        
        # Zła predykcja
        outcome2 = PredictionOutcome(
            strategy_id="test_strategy",
            predicted_result="1",
            actual_result="2"
        )
        outcome2.calculate_scores()
        
        fitness.add_prediction_outcome(outcome1)
        fitness.add_prediction_outcome(outcome2)
        
        assert fitness.total_predictions == 2
        assert fitness.correct_predictions == 1
        assert fitness.overall_fitness > 0
        
        results.append(("StrategyFitness add outcomes", True))
        print("[OK] Test StrategyFitness add outcomes - zaliczony")
    except Exception as e:
        results.append(("StrategyFitness add outcomes", False))
        print(f"[FAIL] Test StrategyFitness add outcomes - error: {e}")
    
    # Test 4: FeedbackEvent
    try:
        event = FeedbackEvent(
            event_type=FeedbackEventType.PREDICTION_CREATED,
            strategy_id="test_strategy",
            feedback_loop_id="loop_001",
            reason="Test event"
        )
        event.mark_success(after_state={"status": "completed"})
        assert event.success == True
        assert event.event_type == FeedbackEventType.PREDICTION_CREATED
        
        results.append(("FeedbackEvent creation", True))
        print("[OK] Test FeedbackEvent creation - zaliczony")
    except Exception as e:
        results.append(("FeedbackEvent creation", False))
        print(f"[FAIL] Test FeedbackEvent creation - error: {e}")
    
    # Test 5: Serializacja
    try:
        outcome = PredictionOutcome(
            strategy_id="test_strategy",
            predicted_result="1",
            actual_result="1"
        )
        
        # to_dict
        data = outcome.to_dict()
        assert isinstance(data, dict)
        
        # from_dict
        outcome2 = PredictionOutcome.from_dict(data)
        assert outcome2.strategy_id == outcome.strategy_id
        
        # to_json
        json_str = outcome.to_json()
        assert isinstance(json_str, str)
        
        # from_json
        outcome3 = PredictionOutcome.from_json(json_str)
        assert outcome3.strategy_id == outcome.strategy_id
        
        results.append(("Serialization", True))
        print("[OK] Test Serialization - zaliczony")
    except Exception as e:
        results.append(("Serialization", False))
        print(f"[FAIL] Test Serialization - error: {e}")
    
    # Podsumowanie
    print("\n" + "="*60)
    print("PODSUMOWANIE TESTOW FEEDBACK MODELS")
    print("="*60)
    
    for test_name, passed in results:
        status = "ZALICZONY" if passed else "NIE ZALICZONY"
        print(f"{test_name}: {status}")
    
    all_passed = all(passed for _, passed in results)
    print(f"\nOgółem: {sum(1 for _, p in results if p)}/{len(results)} testów zaliczono")
    
    return all_passed


if __name__ == "__main__":
    success = test_feedback_models()
    if success:
        print("\n✅ Wszystkie testy feedback models zaliczone!")
    else:
        print("\n❌ Niektóre testy nie zostały zaliczone")
    
    exit(0 if success else 1)
